from models.constants import KEYWORD_ABILITIES

CREATURE_KW_ABILITIES = {
    "abbey-gargoyles": ["Flying", "Protection From Red"],
    "abyssal-specter": ["Flying"],
    "aerathi-berserker": ["Rampage 3"],
    "air-elemental": ["Flying"],
    "ambush-party": ["First Strike", "Haste"],
    "angry-mob": ["Trample"],
    "arcades-sabboth": ["Flying"],
    "aurochs": ["Trample"],
    "axelrod-gunnarson": ["Trample"],
    "ayesha-tanaka": ["Banding"],
    "azure-drake": ["Flying"],
    "ball-lightning": ["Trample", "Haste"],
    "bartel-runeaxe": ["Vigilance"],
    "beasts-of-bogardan": ["Protection From Red"],
    "benalish-hero": ["Banding"],
    "bird-maiden": ["Flying"],
    "birds-of-paradise": ["Flying"],
    "black-knight": ["First Strike", "Protection From White"],
    "bog-imp": ["Flying"],
    "bog-wraith": ["Swampwalk"],
    "bronze-horse": ["Trample"],
    "camel": ["Banding"],
    "carnivorous-plant": ["Defender"],
    "cat-warriors": ["Forestwalk"],
    "chromium": ["Flying", "Rampage 2"],
    "clockwork-avian": ["Flying"],
    "cockatrice": ["Flying"],
    "colossus-of-sardia": ["Trample"],
    "cosmic-horror": ["First Strike"],
    "craw-giant": ["Trample", "Rampage 2"],
    "crimson-manticore": ["Flying"],
    "dancing-scimitar": ["Flying"],
    "dandân": ["Islandhome"],
    "dark-maze": ["Defender"],
    "death-speakers": ["Protection From Black"],
    "devouring-deep": ["Islandwalk"],
    "dragon-whelp": ["Flying"],
    "elder-land-wurm": ["Defender", "Trample"],
    "elvish-archers": ["First Strike"],
    "emerald-dragonfly": ["Flying"],
    "fallen-angel": ["Flying"],
    "fire-drake": ["Flying"],
    "fire-sprites": ["Flying"],
    "firestorm-phoenix": ["Flying"],
    "flying-men": ["Flying"],
    "force-of-nature": ["Trample"],
    "frost-giant": ["Rampage 2"],
    "ghost-ship": ["Flying"],
    "giant-shark": ["Islandhome"],
    "giant-spider": ["Reach"],
    "glacial-wall": ["Defender"],
    "goblin-rock-sled": ["Trample"],
    "goblins-of-the-flarg": ["Mountainwalk"],
    "gosta-dirk": ["First Strike"],
    "granite-gargoyle": ["Flying"],
    "hornet-cobra": ["First Strike"],
    "hunding-gjornersen": ["Rampage 1"],
    "hypnotic-specter": ["Flying"],
    "icatian-phalanx": ["Banding"],
    "ifh-bíff-efreet": ["Flying"],
    "ivory-guardians": ["Protection From Red"],
    "juggernaut": ["Goad"],
    "junún-efreet": ["Flying"],
    "killer-bees": ["Flying"],
    "kjeldoran-skycaptain": ["Flying", "First Strike", "Banding"],
    "knight-of-stromgald": ["Protection From White"],
    "knights-of-thorn": ["Protection From Red", "Banding"],
    "kobold-overlord": ["First Strike"],
    "land-leeches": ["First Strike"],
    "leviathan": ["Trample", "Defender"],
    "living-wall": ["Defender"],
    "livonya-silone": ["First Strike"],
    "lord-magnus": ["First Strike"],
    "lord-of-the-pit": ["Flying", "Trample"],
    "lost-soul": ["Swampwalk"],
    "mahamoti-djinn": ["Flying"],
    "marhault-elsdragon": ["Rampage 1"],
    "marsh-goblins": ["Swampwalk"],
    "merchant-ship": ["Islandhome"],
    "mesa-falcon": ["Flying"],
    "mesa-pegasus": ["Flying", "Banding"],
    "mishras-war-machine": ["Banding"],
    "moorish-cavalry": ["Trample"],
    "mountain-goat": ["Mountainwalk"],
    "mountain-yeti": ["Mountainwalk", "Protection From White"],
    "nameless-race": ["Trample"],
    "necropolis": ["Defender"],
    "nether-shadow": ["Haste"],
    "nicol-bolas": ["Flying"],
    "nightmare": ["Flying"],
    "order-of-the-white-shield": ["Protection From Black"],
    "orgg": ["Trample"],
    "ornithopter": ["Flying"],
    "osai-vultures": ["Flying"],
    "palladia-mors": ["Flying", "Trample"],
    "phantasmal-forces": ["Flying"],
    "phantom-monster": ["Flying"],
    "pikemen": ["First Strike", "Banding"],
    "pirate-ship": ["Islandhome"],
    "pixie-queen": ["Flying"],
    "primordial-ooze": ["Goad"],
    "rabid-wombat": ["Vigilance"],
    "ramirez-depietro": ["First Strike"],
    "repentant-blacksmith": ["Protection From Red"],
    "righteous-avengers": ["Plainswalk"],
    "roc-of-kher-ridges": ["Flying"],
    "sabretooth-tiger": ["First Strike"],
    "scarwood-bandits": ["Forestwalk"],
    "scryb-sprites": ["Flying"],
    "sea-serpent": ["Islandhome"],
    "sea-sprite": ["Flying", "Protection From Red"],
    "segovian-leviathan": ["Islandwalk"],
    "sengir-vampire": ["Flying"],
    "seraph": ["Flying"],
    "serendib-djinn": ["Flying"],
    "serendib-efreet": ["Flying"],
    "serra-angel": ["Flying", "Vigilance"],
    "shanodin-dryads": ["Forestwalk"],
    "shield-bearer": ["Banding"],
    "shivan-dragon": ["Flying"],
    "sibilant-spirit": ["Flying"],
    "solkanar-the-swamp-king": ["Swampwalk"],
    "stone-throwing-devils": ["First Strike"],
    "tetravus": ["Flying"],
    "thunder-spirit": ["Flying", "First Strike"],
    "timber-wolves": ["Banding"],
    "tuknir-deathlock": ["Flying"],
    "tundra-wolves": ["First Strike"],
    "two-headed-giant-of-foriys": ["Trample"],
    "ur-drago": ["First Strike"],
    "vaevictis-asmadi": ["Flying"],
    "vampire-bats": ["Flying"],
    "wall-of-air": ["Defender", "Flying"],
    "wall-of-bone": ["Defender"],
    "wall-of-brambles": ["Defender"],
    "wall-of-caltrops": ["Defender"],
    "wall-of-dust": ["Defender"],
    "wall-of-earth": ["Defender"],
    "wall-of-fire": ["Defender"],
    "wall-of-heat": ["Defender"],
    "wall-of-ice": ["Defender"],
    "wall-of-light": ["Defender", "Protection From Black"],
    "wall-of-opposition": ["Defender"],
    "wall-of-putrid-flesh": ["Defender", "Protection From White"],
    "wall-of-shadows": ["Defender"],
    "wall-of-spears": ["Defender", "First Strike"],
    "wall-of-stone": ["Defender"],
    "wall-of-swords": ["Defender", "Flying"],
    "wall-of-tombstones": ["Defender"],
    "wall-of-vapor": ["Defender"],
    "wall-of-water": ["Defender"],
    "wall-of-wonder": ["Defender"],
    "wall-of-wood": ["Defender"],
    "war-elephant": ["Trample"],
    "war-mammoth": ["Trample"],
    "whirling-dervish": ["Protection From Black"],
    "white-knight": ["First Strike", "Protection From Black"],
    "will-o-the-wisp": ["Flying"],
    "wind-spirit": ["Flying", "Menace"],
    "wolverine-pack": ["Rampage 2"],
    "xira-arien": ["Flying"],
    "yawgmoth-demon": ["Flying", "First Strike"],
    "yotian-soldier": ["Vigilance"],
    "zephyr-falcon": ["Flying", "Vigilance"],
}


def get_creature_base_kwas(slug: str) -> tuple[str]:
    kwas = CREATURE_KW_ABILITIES.get(slug, [])
    if 'Defender' not in kwas:
        kwas.append("Attack")
    return tuple(kwas)


if __name__ == '__main__':
    for the_slug, the_kwas in CREATURE_KW_ABILITIES.items():
        for kwa in the_kwas:
            if kwa not in KEYWORD_ABILITIES:
                raise ValueError(f"{the_slug}'s {kwa} not found in KEYWORD_ABILITIES")