from models.effects.can_attack import *
from models.effects.can_block import *
from models.effects.can_be_blocked import *
from models.effects.cast import *
from models.effects.common import *
from models.effects.damage_prevention import *
from models.effects.leave import *
from models.effects.on_damage import *
from models.effects.tap import *
from models.effects.upkeep import *
from models.effects.untap import *

SLUG_EFFECTS: dict[str, list[Effect]] = {
        'acid-rain': [acid_rain_on_cast()],
        'akron-legionnaire': [akron_legionnaire_on_cast(), akron_legionnaire_on_leave()],
        'ancestral-recall': [ancestral_recall_on_cast()],
        'angelic-voices': [angelic_voices_on_cast(), global_on_leave()],
        'animate-wall': [animate_wall_on_cast()],
        'amrou-kithkin': [amrou_kithkin_can_be_blocked()],
        'argothian-pixies': [argothian_pixies_can_be_blocked(), argothian_pixies_damage_prevention()],
        'argothian-treefolk': [argothian_treefolk_damage_prevention()],
        'armageddon': [send_to_graveyard_all_lands()],
        'artifact-ward': [artifact_ward_can_be_blocked(), artifact_ward_damage_prevention()],
        'bad-moon': [bad_moon_on_cast(), global_on_leave()],
        'blood-lust': [blood_lust_on_cast()],
        'bog-rats': [bog_rats_can_be_blocked()],
        'boomerang': [boomerang_on_cast()],
        'brainwash': [brainwash_on_cast()],
        'burrowing': [burrowing_on_cast()],
        'castle': [castle_on_cast(), global_on_leave()],
        'cleanse': [cleanse_on_cast()],
        'copper-tablet': [copper_tablet_on_upkeep()],
        'creature-bond': [creature_bond_on_leave()],
        'crumble': [crumble_on_cast()],
        'crusade': [crusade_on_cast(), global_on_leave()],
        'cursed-land-on-upkeep': [cursed_land_on_upkeep()],
        'dark-ritual': [dark_ritual_on_cast()],
        'darkness': [darkness_or_fog_or_holy_day_on_cast()],
        'demonic-torment': [demonic_torment_on_cast()],
        'desert-twister': [desert_twister_on_cast()],
        'disenchant': [disenchant_on_cast()],
        'divine-offering': [divine_offering_on_cast()],
        'divine-transformation': [divine_transformation_on_cast()],
        'drain-power': [drain_power_on_cast()],
        'earthbind': [earthbind_on_cast()],
        'electric-eel': [electric_eel_on_cast()],
        'elven-riders': [elven_riders_can_be_blocked()],
        'enchanted-being': [enchanted_being_damage_prevention()],
        'energy-tap': [energy_tap_on_cast()],
        'eternal-flame': [eternal_flame_on_cast()],
        'evil-eye-of-orms-by-gore': [evil_eye_of_orms_by_gore_on_cast(), evil_eye_of_orms_by_gore_on_leave(),
                                     evil_eye_of_orms_by_gore_can_be_blocked()],
        'eye-for-an-eye': [eye_for_an_eye_on_cast()],
        'farmstead': [farmstead_on_cast()],
        'feedback': [feedback_on_upkeep()],
        'feint': [feint_on_cast()],
        'fishliver-oil': [fishliver_oil_on_cast()],
        'flashfires': [flashfires_on_cast()],
        'flight': [flight_on_cast()],
        'fog': [darkness_or_fog_or_holy_day_on_cast()],
        'forest': [forest_on_cast(), forest_on_leave(), forest_on_tap()],
        'gaseous-form': [gaseous_form_on_cast()],
        'giant-growth': [giant_growth_on_cast()],
        'giant-strength': [giant_strength_on_cast()],
        'giant-tortoise': [giant_tortoise_on_cast(), giant_tortoise_on_tap(), giant_tortoise_on_untap()],
        'goblin-king': [goblin_king_on_cast(), goblin_king_on_leave()],
        'great-defender': [great_defender_on_cast()],
        'holy-armor': [holy_armor_on_cast()],
        'holy-day': [darkness_or_fog_or_holy_day_on_cast()],
        'holy-strength': [holy_strength_on_cast()],
        'ice-storm': [ice_storm_on_cast()],
        'immolation': [immolation_on_cast()],
        'indestructible-aura': [indestructible_aura_on_cast()],
        'inferno': [inferno_on_cast()],
        'instill-energy': [instill_energy_on_cast()],
        'island': [island_on_leave()],
        'ivory-tower': [ivory_tower_on_upkeep()],
        'jovian-evil': [jovial_evil_on_cast()],
        'jump': [jump_on_cast()],
        'juzam-djinn': [juzam_djinn_on_upkeep()],
        'karma': [karma_on_upkeep()],
        'kobold-overlord': [kobold_overlord_on_cast(), kobold_overlord_and_taskmaster_on_leave()],
        'kobold-taskmaster': [kobold_taskmaster_on_cast(), kobold_overlord_and_taskmaster_on_leave()],
        'lance': [lance_on_cast()],
        'lightning-bolt': [lightning_bolt_on_cast()],
        'lord-of-atlantis': [lord_of_atlantis_on_cast(), lord_of_atlantis_on_leave()],
        'mana-short': [mana_short_on_cast()],
        'marble-priest': [marble_priest_damage_prevention()],  # NOT CODED!! All Walls able to block this creature do so
        'martyrs-cry': [martyrs_cry_on_cast()],
        'martyrs-on-korlis': [martyrs_of_korlis_on_damage()],
        'mountain': [mountain_on_tap()],
        'nevinyrrals-disk': [nevinyrrals_disk_on_cast()],
        'pirate-ship': [islandhome_can_attack_effect()],
        # 'plains': [tap_for_mana('W')],
        'reverse-damage': [reverse_damage_on_cast()],
        'sea-serpent': [islandhome_can_attack_effect()],
        'seeker': [seeker_enchanted_creature_can_be_blocked()],
        'serendib-efreet': [serendib_efreet_on_upkeep()],
        # 'swamp': [tap_for_mana('B')],
        'swords-to-plowshares': [swords_to_plowshares_on_cast()],
        'twiddle': [twiddle_on_cast()],
        'unsummon': [unsummon_on_cast()],
        'wrath-of-god': [wrath_of_god_on_cast()],

        '_default_leave': [default_clear_on_leave()],
    }
