KEYWORD_ABILITIES = ['Defender', 'First Strike', 'Flying', 'Forestwalk', 'Haste', 'Islandwalk', 'Menace',
                     'Mountainwalk',
                     'Protection from Black', 'Protection from Blue', 'Protection from Green', 'Protection from Red',
                     'Protection from White', 'Rampage', 'Reach', 'Swampwalk', 'Foresthome', 'Islandhome',
                     'Mountainhome', 'Swamphome', 'Trample', 'Vigilance']

creature_keyword_abilities = {
    'abbey-gargoyles': ['Flying', 'Protection from Red'],
    'abomination': [],
    'abyssal-specter': ['Flying'],
    'air-elemental': ['Flying'],
    'akron-legionnaire': [],
    'amrou-kithkin': [],
    'angry-mob': ['Trample'],
    'apprentice-wizard': [],
    'aysen-bureaucrats': [],
    'azure-drake': ['Flying'],
    'battering-ram': [],
    'benalish-hero': ['Banding'],
    'black-knight': ['First Strike', 'Protection from White'],
    'blinking-spirit': [],
    'bog-imp': ['Flying'],
    'bog-rats': [],
    'bog-wraith': ['Swampwalk'],
    'brass-man': [],
    'carrion-ants': [],
    'clay-statue': [],
    'clockwork-avian': ['Flying'],
    'clockwork-beast': [],
    'clockwork-steed': [],
    'clone': [],
    'colossus-of-sardia': ['Trample'],
    'cosmic-horror': ['First Strike'],
    'cyclopean-mummy': [],
    'dancing-scimitar': ['Flying'],
    'dandân': ['Islandhome'],
    'dark-maze': ['Defender'],
    'davenant-archer': [],
    'death-speakers': ['Protection from Black'],
    'demonic-hordes': [],
    'derelor': [],
    'diabolic-machine': [],
    'dragon-engine': [],
    'drudge-skeletons': [],
    'el-hajjâj': [],
    'elder-land-wurm': ['Defender', 'Trample'],
    'erg-raiders': [],
    'evil-eye-of-orms-by-gore': [],
    'fallen-angel': ['Flying'],
    'frozen-shade': [],
    'ghost-ship': ['Flying'],
    'giant-tortoise': [],
    'glacial-wall': ['Defender'],
    'grapeshot-catapult': [],
    'greater-werewolf': [],
    'hipparion': [],
    'homarid-warrior': [],
    'hypnotic-specter': ['Flying'],
    'icatian-phalanx': ['Banding'],
    'icatian-scout': [],
    'initiates-of-the-ebon-hand': [],
    'island-fish-jasconius': [],
    'ivory-guardians': ['Protection from Red'],
    'juggernaut': [],
    'junún-efreet': ['Flying'],
    'kjeldoran-dead': [],
    'kjeldoran-royal-guard': [],
    'kjeldoran-skycaptain': ['Flying', 'First Strike', 'Banding'],
    'knight-of-stromgald': ['Protection from White'],
    'krovikan-sorcerer': [],
    'labyrinth-minotaur': [],
    'leviathan': ['Trample'],
    'living-wall': ['Defender'],
    'lord-of-atlantis': [],
    'lord-of-the-pit': ['Flying', 'Trample'],
    'lost-soul': ['Swampwalk'],
    'magus-of-the-unseen': [],
    'mahamoti-djinn': ['Flying'],
    'merfolk-of-the-pearl-trident': [],
    'mesa-falcon': ['Flying'],
    'mesa-pegasus': ['Flying', 'Banding'],
    'mindstab-thrull': [],
    'mishras-war-machine': ['Banding'],
    'mole-worms': [],
    'murk-dwellers': [],
    'necrite': [],
    'nether-shadow': ['Haste'],
    'nettling-imp': [],
    'nightmare': ['Flying'],
    'northern-paladin': [],
    'obsianus-golem': [],
    'onulet': [],
    'order-of-the-sacred-torch': [],
    'order-of-the-white-shield': [],
    'ornithopter': ['Flying'],
    'osai-vultures': ['Flying'],
    'pearled-unicorn': [],
    'personal-incarnation': [],
    'phantasmal-forces': ['Flying'],
    'phantom-monster': ['Flying'],
    'pikemen': ['First Strike', 'Banding'],
    'pirate-ship': ['Islandhome'],
    'pit-scorpion': [],
    'plague-rats': [],
    'primal-clay': [],
    'prodigal-sorcerer': [],
    'psionic-entity': [],
    'rag-man': [],
    'reef-pirates': [],
    'repentant-blacksmith': ['Protection from Red'],
    'royal-assassin': [],
    'samite-healer': [],
    'savannah-lions': [],
    'scathe-zombies': [],
    'scavenging-ghoul': [],
    'sea-serpent': ['Islandhome'],
    'sea-spirit': [],
    'sea-sprite': ['Flying', 'Protection from Red'],
    'seasinger': [],
    'segovian-leviathan': ['Islandwalk'],
    'sengir-autocrat': [],
    'sengir-vampire': ['Flying'],
    'seraph': ['Flying'],
    'serendib-efreet': ['Flying'],
    'serra-angel': ['Flying', 'Vigilance'],
    'serra-paladin': [],
    'shapeshifter': [],
    'shield-bearer': ['Banding'],
    'sibilant-spirit': ['Flying'],
    'sindbad': [],
    'sorceress-queen': [],
    'stromgald-cabal': [],
    'tetravus': ['Flying'],
    'the-wretched': [],
    'time-elemental': [],
    'triskelion': [],
    'tundra-wolves': ['First Strike'],
    'uncle-istvan': [],
    'urzas-avenger': [],
    'vampire-bats': ['Flying'],
    'vesuvan-doppelganger': [],
    'veteran-bodyguard': [],
    'vodalian-soldiers': [],
    'wall-of-air': ['Defender'],
    'wall-of-bone': ['Defender'],
    'wall-of-spears': ['Defender'],
    'wall-of-swords': ['Defender'],
    'wall-of-water': ['Defender'],
    'water-elemental': [],
    'white-knight': ['First Strike', 'Protection from Black'],
    'will-o-the-wisp': ['Flying'],
    'wind-spirit': ['Flying', 'Menace'],
    'xenic-poltergeist': [],
    'yotian-soldier': ['Vigilance'],
    'zephyr-falcon': ['Flying', 'Vigilance'],
    'zombie-master': []
}

