KEYWORD_ABILITIES = ['Defender', 'First Strike', 'Flying', 'Forestwalk', 'Haste', 'Islandwalk', 'Menace',
                     'Mountainwalk',
                     'Protection from Black', 'Protection from Blue', 'Protection from Green', 'Protection from Red',
                     'Protection from White', 'Rampage', 'Reach', 'Swampwalk', 'Foresthome', 'Islandhome',
                     'Mountainhome', 'Swamphome', 'Trample', 'Vigilance']

CREATURE_KW_ABILITIES = {
    'shield-bearer': 'Banding u003ciu003e(Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creatures combat damage, not its controller, among any of the creatures its being blocked by or is blocking.)u003c/iu003e',
    'icatian-phalanx': 'Banding u003ciu003e(Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creatures combat damage, not its controller, among any of the creatures its being blocked by or is blocking.)u003c/iu003e',
    'timber-wolves': 'Banding u003ciu003e(Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creatures combat damage, not its controller, among any of the creatures its being blocked by or is blocking.)u003c/iu003e',
    'benalish-hero': 'Banding u003ciu003e(Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creatures combat damage, not its controller, among any of the creatures its being blocked by or is blocking.)u003c/iu003e',
    'camel': 'Banding u003ciu003e(Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creatures combat damage, not its controller, among any of the creatures its being blocked by or is blocking.)u003c/iu003e As long as this creature is attacking, prevent all damage Deserts would deal to this creature and to creatures banded with this creature.',
    'mishras-war-machine': 'Banding u003ciu003e(Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creatures combat damage, not its controller, among any of the creatures its being blocked by or is blocking.)u003c/iu003e At the beginning of your upkeep, this creature deals 3 damage to you unless you discard a card. If it deals damage to you this way, tap it.',
    'ayesha-tanaka': 'Banding u003ciu003e(Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creatures combat damage, not its controller, among any of the creatures its being blocked by or is blocking.)u003c/iu003e {T}: Counter target activated ability from an artifact source unless that abilitys controller pays {W}. u003ciu003e(Mana abilities cant be targeted.)u003c/iu003e',
    'carnivorous-plant': 'Defender',
    'wall-of-earth': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e',
    'wall-of-stone': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e',
    'wall-of-ice': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e',
    'wall-of-wood': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e',
    'glacial-wall': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e',
    'wall-of-heat': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e',
    'wall-of-tombstones': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e At the beginning of your upkeep, change this creatures base toughness to 1 plus the number of creature cards in your graveyard. u003cIu003e(This effect lasts indefinitely.)u003c/Iu003e',
    'necropolis': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e Exile a creature card from your graveyard: Put X +0/+1 counters on this creature, where X is the exiled cards mana value.',
    'wall-of-spears': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e First strike',
    'wall-of-swords': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e Flying',
    'wall-of-vapor': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e Prevent all damage that would be dealt to this creature by creatures its blocking.',
    'wall-of-shadows': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e Prevent all damage that would be dealt to this creature by creatures its blocking. This creature cant be the target of spells that can target only Walls or of abilities that can target only Walls.',
    'wall-of-light': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e Protection from black',
    'wall-of-putrid-flesh': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e Protection from white Prevent all damage that would be dealt to this creature by enchanted creatures.',
    'wall-of-caltrops': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e Whenever this creature blocks a creature, if at least one other Wall creature is blocking that creature and no non-Wall creatures are blocking that creature, this creature gains banding until end of turn. u003ciu003e(If any creatures with banding you control are blocking a creature, you divide that creatures combat damage, not its controller, among any of the creatures its being blocked by.)u003c/iu003e',
    'wall-of-dust': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e Whenever this creature blocks a creature, that creature cant attack during its controllers next turn.',
    'dark-maze': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e {0}: This creature can attack this turn as though it didnt have defender. Exile it at the beginning of the next end step.',
    'living-wall': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e {1}: Regenerate this creature.',
    'wall-of-opposition': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e {1}: This creature gets +1/+0 until end of turn.',
    'wall-of-wonder': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e {2UU}: This creature gets +4/-4 until end of turn and can attack this turn as though it didnt have defender.',
    'wall-of-bone': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e {B}: Regenerate this creature. u003ciu003e(The next time this creature would be destroyed this turn, instead tap it, remove it from combat, and heal all damage on it.)u003c/iu003e',
    'wall-of-brambles': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e {G}: Regenerate this creature.',
    'wall-of-fire': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e {R}: This creature gets +1/+0 until end of turn.',
    'wall-of-water': 'Defender u003ciu003e(This creature cant attack.)u003c/iu003e {U}: This creature gets +1/+0 until end of turn.',
    'wall-of-air': 'Defender, flying u003ciu003e(This creature cant attack, and it can block creatures with flying.)u003c/iu003e',
    'elder-land-wurm': 'Defender, trample When this creature blocks, it loses defender.',
    'land-leeches': 'First strike',
    'stone-throwing-devils': 'First strike',
    'sabretooth-tiger': 'First strike',
    'elvish-archers': 'First strike',
    'ramirez-depietro': 'First strike',
    'hornet-cobra': 'First strike',
    'cosmic-horror': 'First strike At the beginning of your upkeep, destroy this creature unless you pay {3BBB}. If this creature is destroyed this way, it deals 7 damage to you.',
    'gosta-dirk': 'First strike Creatures with islandwalk can be blocked as though they didnt have islandwalk.',
    'lord-magnus': 'First strike Creatures with plainswalk can be blocked as though they didnt have plainswalk. Creatures with forestwalk can be blocked as though they didnt have forestwalk.',
    'ur-drago': 'First strike Creatures with swampwalk can be blocked as though they didnt have swampwalk.',
    'kobold-overlord': 'First strike Other Kobold creatures you control have first strike.',
    'tundra-wolves': 'First strike u003ciu003e(This creature deals combat damage before creatures without first strike.)u003c/iu003e',
    'white-knight': 'First strike u003ciu003e(This creature deals combat damage before creatures without first strike.)u003c/iu003e Protection from black u003ciu003e(This creature cant be blocked, targeted, dealt damage, or enchanted by anything black.)u003c/iu003e',
    'black-knight': 'First strike u003ciu003e(This creature deals combat damage before creatures without first strike.)u003c/iu003e Protection from white u003ciu003e(This creature cant be blocked, targeted, dealt damage, or enchanted by anything white.)u003c/iu003e',
    'ambush-party': 'First strike, haste',
    'pikemen': 'First strike; banding u003ciu003e(Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creatures combat damage, not its controller, among any of the creatures its being blocked by or is blocking.)u003c/iu003e',
    'livonya-silone': 'First strike; legendary landwalk u003ciu003e(This creature cant be blocked as long as defending player controls a legendary land.)u003c/iu003e',
    'azure-drake': 'Flying',
    'phantom-monster': 'Flying',
    'bird-maiden': 'Flying',
    'flying-men': 'Flying',
    'ornithopter': 'Flying',
    'scryb-sprites': 'Flying',
    'roc-of-kher-ridges': 'Flying',
    'air-elemental': 'Flying',
    'osai-vultures': 'Flying At the beginning of each end step, if a creature died this turn, put a carrion counter on this creature. Remove two carrion counters from this creature: This creature gets +1/+1 until end of turn.',
    'arcades-sabboth': 'Flying At the beginning of your upkeep, sacrifice Arcades Sabboth unless you pay {GWU}. Each untapped creature you control gets +0/+2 as long as its not attacking. {W}: Arcades Sabboth gets +0/+1 until end of turn.',
    'nicol-bolas': 'Flying At the beginning of your upkeep, sacrifice Nicol Bolas unless you pay {UBR}. Whenever Nicol Bolas deals damage to an opponent, that player discards their hand.',
    'vaevictis-asmadi': 'Flying At the beginning of your upkeep, sacrifice Vaevictis Asmadi unless you pay {BRG}. {B}: Vaevictis Asmadi gets +1/+0 until end of turn. {R}: Vaevictis Asmadi gets +1/+0 until end of turn. {G}: Vaevictis Asmadi gets +1/+0 until end of turn.',
    'serendib-djinn': 'Flying At the beginning of your upkeep, sacrifice a land. If you sacrifice an Island this way, this creature deals 3 damage to you. When you control no lands, sacrifice this creature.',
    'junún-efreet': 'Flying At the beginning of your upkeep, sacrifice this creature unless you pay {BB}.',
    'phantasmal-forces': 'Flying At the beginning of your upkeep, sacrifice this creature unless you pay {U}.',
    'serendib-efreet': 'Flying At the beginning of your upkeep, this creature deals 1 damage to you.',
    'firestorm-phoenix': 'Flying If this creature would die, return it to its owners hand instead. Until that players next turn, that player plays with that card revealed in their hand and cant play it.',
    'wind-spirit': 'Flying Menace u003ciu003e(This creature cant be blocked except by two or more creatures.)u003c/iu003e',
    'chromium': 'Flying Rampage 2 u003cIu003e(Whenever this creature becomes blocked, it gets +2/+2 until end of turn for each creature blocking it beyond the first.)u003c/Iu003e At the beginning of your upkeep, sacrifice Chromium unless you pay {WUB}.',
    'fallen-angel': 'Flying Sacrifice a creature: This creature gets +2/+1 until end of turn.',
    'clockwork-avian': 'Flying This creature enters with four +1/+0 counters on it. At end of combat, if this creature attacked or blocked this combat, remove a +1/+0 counter from it. {X}, {T}: Put up to X +1/+0 counters on this creature. This ability cant cause the total number of +1/+0 counters on this creature to be greater than four. Activate only during your upkeep.',
    'tetravus': 'Flying This creature enters with three +1/+1 counters on it. At the beginning of your upkeep, you may remove any number of +1/+1 counters from this creature. If you do, create that many 1/1 colorless Tetravite artifact creature tokens. They each have flying and This token cant be enchanted. At the beginning of your upkeep, you may exile any number of tokens created with this creature. If you do, put that many +1/+1 counters on this creature.',
    'serra-angel': 'Flying Vigilance u003ciu003e(Attacking doesnt cause this creature to tap.)u003c/iu003e',
    'seraph': 'Flying Whenever a creature dealt damage by this creature this turn dies, put that card onto the battlefield under your control at the beginning of the next end step. Sacrifice the creature when you lose control of this creature.',
    'sibilant-spirit': 'Flying Whenever this creature attacks, defending player may draw a card.',
    'cockatrice': 'Flying Whenever this creature blocks or becomes blocked by a non-Wall creature, destroy that creature at end of combat.',
    'abyssal-specter': 'Flying Whenever this creature deals damage to a player, that player discards a card.',
    'hypnotic-specter': 'Flying Whenever this creature deals damage to an opponent, that player discards a card at random.',
    'mahamoti-djinn': 'Flying u003ciu003e(This creature cant be blocked except by creatures with flying or reach.)u003c/iu003e',
    'bog-imp': 'Flying u003ciu003e(This creature cant be blocked except by creatures with flying or reach.)u003c/iu003e',
    'dancing-scimitar': 'Flying u003ciu003e(This creature cant be blocked except by creatures with flying or reach.)u003c/iu003e',
    'yawgmoth-demon': 'Flying u003ciu003e(This creature cant be blocked except by creatures with flying or reach.)u003c/iu003e First strike u003ciu003e(This creature deals combat damage before creatures without first strike.)u003c/iu003e At the beginning of your upkeep, you may sacrifice an artifact. If you dont, tap this creature and it deals 2 damage to you.',
    'nightmare': 'Flying u003ciu003e(This creature cant be blocked except by creatures with flying or reach.)u003c/iu003e Nightmares power and toughness are each equal to the number of Swamps you control.',
    'sengir-vampire': 'Flying u003ciu003e(This creature cant be blocked except by creatures with flying or reach.)u003c/iu003e Whenever a creature dealt damage by this creature this turn dies, put a +1/+1 counter on this creature.',
    'will-o-the-wisp': 'Flying u003ciu003e(This creature cant be blocked except by creatures with flying or reach.)u003c/iu003e {B}: Regenerate this creature. u003ciu003e(The next time this creature would be destroyed this turn, instead tap it, remove it from combat, and heal all damage on it.)u003c/iu003e',
    'vampire-bats': 'Flying u003ciu003e(This creature cant be blocked except by creatures with flying or reach.)u003c/iu003e {B}: This creature gets +1/+0 until end of turn. Activate no more than twice each turn.',
    'mesa-falcon': 'Flying {1W}: This creature gets +0/+1 until end of turn.',
    'xira-arien': 'Flying {BRG}, {T}: Target player draws a card.',
    'pixie-queen': 'Flying {GGG}, {T}: Target creature gains flying until end of turn.',
    'emerald-dragonfly': 'Flying {GG}: This creature gains first strike until end of turn.',
    'fire-sprites': 'Flying {G}, {T}: Add {R}.',
    'ifh-bíff-efreet': 'Flying {G}: This creature deals 1 damage to each creature with flying and each player. Any player may activate this ability.',
    'killer-bees': 'Flying {G}: This creature gets +1/+1 until end of turn.',
    'tuknir-deathlock': 'Flying {RG}, {T}: Target creature gets +2/+2 until end of turn.',
    'crimson-manticore': 'Flying {R}, {T}: This creature deals 1 damage to target attacking or blocking creature.',
    'granite-gargoyle': 'Flying {R}: This creature gets +0/+1 until end of turn.',
    'shivan-dragon': 'Flying {R}: This creature gets +1/+0 until end of turn.',
    'fire-drake': 'Flying {R}: This creature gets +1/+0 until end of turn. Activate only once each turn.',
    'dragon-whelp': 'Flying {R}: This creature gets +1/+0 until end of turn. If this ability has been activated four or more times this turn, sacrifice this creature at the beginning of the next end step.',
    'birds-of-paradise': 'Flying {T}: Add one mana of any color.',
    'ghost-ship': 'Flying {UUU}: Regenerate this creature.',
    'thunder-spirit': 'Flying, first strike',
    'sea-sprite': 'Flying, protection from red',
    'abbey-gargoyles': 'Flying, protection from red',
    'palladia-mors': 'Flying, trample At the beginning of your upkeep, sacrifice Palladia-Mors unless you pay {RGW}.',
    'lord-of-the-pit': 'Flying, trample At the beginning of your upkeep, sacrifice a creature other than this creature. If you cant, this creature deals 7 damage to you.',
    'zephyr-falcon': 'Flying, vigilance',
    'mesa-pegasus': 'Flying; banding u003ciu003e(Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creatures combat damage, not its controller, among any of the creatures its being blocked by or is blocking.)u003c/iu003e',
    'kjeldoran-skycaptain': 'Flying; first strike; banding u003ciu003e(Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creatures combat damage, not its controller, among any of the creatures its being blocked by or is blocking.)u003c/iu003e',
    'shanodin-dryads': 'Forestwalk u003ciu003e(This creature cant be blocked as long as defending player controls a Forest.)u003c/iu003e',
    'cat-warriors': 'Forestwalk u003ciu003e(This creature cant be blocked as long as defending player controls a Forest.)u003c/iu003e',
    'scarwood-bandits': 'Forestwalk u003ciu003e(This creature cant be blocked as long as defending player controls a Forest.)u003c/iu003e {2G}, {T}: Unless an opponent pays {2}, gain control of target artifact for as long as this creature remains on the battlefield.',
    'nether-shadow': 'Haste At the beginning of your upkeep, if this card is in your graveyard with three or more creature cards above it, you may put this card onto the battlefield.',
    'devouring-deep': 'Islandwalk u003ciu003e(This creature cant be blocked as long as defending player controls an Island.)u003c/iu003e',
    'segovian-leviathan': 'Islandwalk u003ciu003e(This creature cant be blocked as long as defending player controls an Island.)u003c/iu003e',
    'mountain-goat': 'Mountainwalk u003ciu003e(This creature cant be blocked as long as defending player controls a Mountain.)u003c/iu003e',
    'mountain-yeti': 'Mountainwalk u003ciu003e(This creature cant be blocked as long as defending player controls a Mountain.)u003c/iu003e Protection from white',
    'goblins-of-the-flarg': 'Mountainwalk u003ciu003e(This creature cant be blocked as long as defending player controls a Mountain.)u003c/iu003e When you control a Dwarf, sacrifice this creature.',
    'righteous-avengers': 'Plainswalk u003ciu003e(This creature cant be blocked as long as defending player controls a Plains.)u003c/iu003e',
    'death-speakers': 'Protection from black',
    'whirling-dervish': 'Protection from black At the beginning of each end step, if this creature dealt damage to an opponent this turn, put a +1/+1 counter on it.',
    'order-of-the-white-shield': 'Protection from black {W}: This creature gains first strike until end of turn. {WW}: This creature gets +1/+0 until end of turn.',
    'repentant-blacksmith': 'Protection from red',
    'ivory-guardians': 'Protection from red Creatures named Ivory Guardians get +1/+1 as long as an opponent controls a nontoken red permanent.',
    'beasts-of-bogardan': 'Protection from red This creature gets +1/+1 as long as an opponent controls a nontoken white permanent.',
    'knights-of-thorn': 'Protection from red; banding u003ciu003e(Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creatures combat damage, not its controller, among any of the creatures its being blocked by or is blocking.)u003c/iu003e',
    'knight-of-stromgald': 'Protection from white {B}: This creature gains first strike until end of turn. {BB}: This creature gets +1/+0 until end of turn.',
    'marhault-elsdragon': 'Rampage 1 u003cIu003e(Whenever this creature becomes blocked, it gets +1/+1 until end of turn for each creature blocking it beyond the first.)u003c/Iu003e',
    'hunding-gjornersen': 'Rampage 1 u003cIu003e(Whenever this creature becomes blocked, it gets +1/+1 until end of turn for each creature blocking it beyond the first.)u003c/Iu003e',
    'wolverine-pack': 'Rampage 2 u003cIu003e(Whenever this creature becomes blocked, it gets +2/+2 until end of turn for each creature blocking it beyond the first.)u003c/Iu003e',
    'frost-giant': 'Rampage 2 u003cIu003e(Whenever this creature becomes blocked, it gets +2/+2 until end of turn for each creature blocking it beyond the first.)u003c/Iu003e',
    'aerathi-berserker': 'Rampage 3 u003cIu003e(Whenever this creature becomes blocked, it gets +3/+3 until end of turn for each creature blocking it beyond the first.)u003c/Iu003e',
    'giant-spider': 'Reach u003ciu003e(This creature can block creatures with flying.)u003c/iu003e',
    'marsh-goblins': 'Swampwalk u003ciu003e(This creature cant be blocked as long as defending player controls a Swamp.)u003c/iu003e',
    'bog-wraith': 'Swampwalk u003ciu003e(This creature cant be blocked as long as defending player controls a Swamp.)u003c/iu003e',
    'lost-soul': 'Swampwalk u003ciu003e(This creature cant be blocked as long as defending player controls a Swamp.)u003c/iu003e',
    'solkanar-the-swamp-king': 'Swampwalk u003ciu003e(This creature cant be blocked as long as defending player controls a Swamp.)u003c/iu003e Whenever a player casts a black spell, you gain 1 life.',
    'orcish-conscripts': 'This creature cant attack unless at least two other creatures attack. This creature cant block unless at least two other creatures block.',
    'dandân': 'Islandhome',
    'sea-serpent': 'Islandhome',
    'merchant-ship': 'Islandhome. Whenever this creature attacks and isnt blocked, you gain 2 life.',
    'giant-shark': 'Islandhome. Whenever this creature blocks or becomes blocked by a creature that has been dealt damage this turn, This creature gets +2/+0 and gains trample until end of turn.',
    'pirate-ship': 'Islandhome. {T}: This creature deals 1 damage to any target',
    'war-mammoth': 'Trample',
    'moorish-cavalry': 'Trample',
    'bronze-horse': 'Trample As long as you control another creature, prevent all damage that would be dealt to this creature by spells that target it.',
    'nameless-race': 'Trample As this creature enters, pay any amount of life. The amount you pay cant be more than the total number of white nontoken permanents your opponents control plus the total number of white cards in their graveyards. Nameless Races power and toughness are each equal to the life paid as it entered.',
    'angry-mob': 'Trample During your turn, Angry Mobs power and toughness are each equal to 2 plus the number of Swamps your opponents control. During turns other than yours, Angry Mobs power and toughness are each 2.',
    'craw-giant': 'Trample Rampage 2 u003ciu003e(Whenever this creature becomes blocked, it gets +2/+2 until end of turn for each creature blocking it beyond the first.)u003c/iu003e',
    'two-headed-giant-of-foriys': 'Trample This creature can block an additional creature each combat.',
    'orgg': 'Trample This creature cant attack if defending player controls an untapped creature with power 3 or greater. This creature cant block creatures with power 3 or greater.',
    'goblin-rock-sled': 'Trample This creature doesnt untap during your untap step if it attacked during your last turn. This creature cant attack unless defending player controls a Mountain.',
    'leviathan': 'Trample This creature enters tapped and doesnt untap during your untap step. At the beginning of your upkeep, you may sacrifice two Islands. If you do, untap this creature. This creature cant attack unless you sacrifice two Islands. u003ciu003e(This cost is paid as attackers are declared.)u003c/iu003e',
    'axelrod-gunnarson': 'Trample Whenever a creature dealt damage by Axelrod Gunnarson this turn dies, you gain 1 life and Axelrod Gunnarson deals 1 damage to target player or planeswalker.',
    'aurochs': 'Trample Whenever this creature attacks, it gets +1/+0 until end of turn for each other attacking Aurochs.',
    'force-of-nature': 'Trample u003ciu003e(This creature can deal excess combat damage to the player or planeswalker its attacking.)u003c/iu003e At the beginning of your upkeep, this creature deals 8 damage to you unless you pay {GGGG}.',
    'ball-lightning': 'Trample u003ciu003e(This creature can deal excess combat damage to the player or planeswalker its attacking.)u003c/iu003e Haste u003ciu003e(This creature can attack and {T} as soon as it comes under your control.)u003c/iu003e At the beginning of the end step, sacrifice this creature.',
    'colossus-of-sardia': 'Trample u003ciu003e(This creature can deal excess combat damage to the player or planeswalker its attacking.)u003c/iu003e This creature doesnt untap during your untap step. {9}: Untap this creature. Activate only during your upkeep.',
    'war-elephant': 'Trample',
    'yotian-soldier': 'Vigilance',
    'bartel-runeaxe': 'Vigilance',
    'rabid-wombat': 'Vigilance',
}

