KEYWORD_ABILITIES = ['Attack', 'Banding', 'Defender', 'First Strike', 'Flying', 'Forestwalk', 'Haste', 'Islandwalk',
                     'Menace',
                     'Mountainwalk', 'Protection From Black', 'Protection From Blue', 'Protection From Green',
                     'Protection From Red', 'Protection From White', 'Rampage 1', 'Rampage 2', 'Rampage 3', 'Reach',
                     'Swampwalk', 'Foresthome', 'Islandhome', 'Mountainhome', 'Plainswalk', 'Swamphome', 'Trample',
                     'Vigilance']

CREATURE_KW_ABILITIES = {
    "abbey-gargoyles": ["Flying", "Protection From Red", "Attack"],
    "abyssal-specter": ["Flying", "Attack"],
    "aerathi-berserker": ["Rampage 3", "Attack"],
    "air-elemental": ["Flying", "Attack"],
    "ambush-party": ["First Strike", "Haste", "Attack"],
    "angry-mob": ["Trample", "Attack"],
    "arcades-sabboth": ["Flying", "Attack"],
    "aurochs": ["Trample", "Attack"],
    "axelrod-gunnarson": ["Trample", "Attack"],
    "ayesha-tanaka": ["Banding", "Attack"],
    "azure-drake": ["Flying", "Attack"],
    "ball-lightning": ["Trample", "Haste", "Attack"],
    "bartel-runeaxe": ["Vigilance", "Attack"],
    "beasts-of-bogardan": ["Protection From Red", "Attack"],
    "benalish-hero": ["Banding", "Attack"],
    "bird-maiden": ["Flying", "Attack"],
    "birds-of-paradise": ["Flying", "Attack"],
    "black-knight": ["First Strike", "Protection From White", "Attack"],
    "bog-imp": ["Flying", "Attack"],
    "bog-wraith": ["Swampwalk", "Attack"],
    "bronze-horse": ["Trample", "Attack"],
    "camel": ["Banding", "Attack"],
    "carnivorous-plant": ["Defender"],
    "cat-warriors": ["Forestwalk", "Attack"],
    "chromium": ["Flying", "Rampage 2", "Attack"],
    "clockwork-avian": ["Flying", "Attack"],
    "cockatrice": ["Flying", "Attack"],
    "colossus-of-sardia": ["Trample", "Attack"],
    "cosmic-horror": ["First Strike", "Attack"],
    "craw-giant": ["Trample", "Rampage 2", "Attack"],
    "crimson-manticore": ["Flying", "Attack"],
    "dancing-scimitar": ["Flying", "Attack"],
    "dandân": ["Islandhome", "Attack"],
    "dark-maze": ["Defender"],
    "death-speakers": ["Protection From Black", "Attack"],
    "devouring-deep": ["Islandwalk", "Attack"],
    "dragon-whelp": ["Flying", "Attack"],
    "elder-land-wurm": ["Defender", "Trample"],
    "elvish-archers": ["First Strike", "Attack"],
    "emerald-dragonfly": ["Flying", "Attack"],
    "fallen-angel": ["Flying", "Attack"],
    "fire-drake": ["Flying", "Attack"],
    "fire-sprites": ["Flying", "Attack"],
    "firestorm-phoenix": ["Flying", "Attack"],
    "flying-men": ["Flying", "Attack"],
    "force-of-nature": ["Trample", "Attack"],
    "frost-giant": ["Rampage 2", "Attack"],
    "ghost-ship": ["Flying", "Attack"],
    "giant-shark": ["Islandhome", "Attack"],
    "giant-spider": ["Reach", "Attack"],
    "glacial-wall": ["Defender"],
    "goblin-rock-sled": ["Trample", "Attack"],
    "goblins-of-the-flarg": ["Mountainwalk", "Attack"],
    "gosta-dirk": ["First Strike", "Attack"],
    "granite-gargoyle": ["Flying", "Attack"],
    "hornet-cobra": ["First Strike", "Attack"],
    "hunding-gjornersen": ["Rampage 1", "Attack"],
    "hypnotic-specter": ["Flying", "Attack"],
    "icatian-phalanx": ["Banding", "Attack"],
    "ifh-bíff-efreet": ["Flying", "Attack"],
    "ivory-guardians": ["Protection From Red", "Attack"],
    "junún-efreet": ["Flying", "Attack"],
    "killer-bees": ["Flying", "Attack"],
    "kjeldoran-skycaptain": ["Flying", "First Strike", "Banding", "Attack"],
    "knight-of-stromgald": ["Protection From White", "Attack"],
    "knights-of-thorn": ["Protection From Red", "Banding", "Attack"],
    "kobold-overlord": ["First Strike", "Attack"],
    "land-leeches": ["First Strike", "Attack"],
    "leviathan": ["Trample", "Defender"],
    "living-wall": ["Defender"],
    "livonya-silone": ["First Strike", "Attack"],
    "lord-magnus": ["First Strike", "Attack"],
    "lord-of-the-pit": ["Flying", "Trample", "Attack"],
    "lost-soul": ["Swampwalk", "Attack"],
    "mahamoti-djinn": ["Flying", "Attack"],
    "marhault-elsdragon": ["Rampage 1", "Attack"],
    "marsh-goblins": ["Swampwalk", "Attack"],
    "merchant-ship": ["Islandhome", "Attack"],
    "mesa-falcon": ["Flying", "Attack"],
    "mesa-pegasus": ["Flying", "Banding", "Attack"],
    "mishras-war-machine": ["Banding", "Attack"],
    "moorish-cavalry": ["Trample", "Attack"],
    "mountain-goat": ["Mountainwalk", "Attack"],
    "mountain-yeti": ["Mountainwalk", "Protection From White", "Attack"],
    "nameless-race": ["Trample", "Attack"],
    "necropolis": ["Defender"],
    "nether-shadow": ["Haste", "Attack"],
    "nicol-bolas": ["Flying", "Attack"],
    "nightmare": ["Flying", "Attack"],
    "order-of-the-white-shield": ["Protection From Black", "Attack"],
    "orgg": ["Trample", "Attack"],
    "ornithopter": ["Flying", "Attack"],
    "osai-vultures": ["Flying", "Attack"],
    "palladia-mors": ["Flying", "Trample", "Attack"],
    "phantasmal-forces": ["Flying", "Attack"],
    "phantom-monster": ["Flying", "Attack"],
    "pikemen": ["First Strike", "Banding", "Attack"],
    "pirate-ship": ["Islandhome", "Attack"],
    "pixie-queen": ["Flying", "Attack"],
    "rabid-wombat": ["Vigilance", "Attack"],
    "ramirez-depietro": ["First Strike", "Attack"],
    "repentant-blacksmith": ["Protection From Red", "Attack"],
    "righteous-avengers": ["Plainswalk", "Attack"],
    "roc-of-kher-ridges": ["Flying", "Attack"],
    "sabretooth-tiger": ["First Strike", "Attack"],
    "scarwood-bandits": ["Forestwalk", "Attack"],
    "scryb-sprites": ["Flying", "Attack"],
    "sea-serpent": ["Islandhome", "Attack"],
    "sea-sprite": ["Flying", "Protection From Red", "Attack"],
    "segovian-leviathan": ["Islandwalk", "Attack"],
    "sengir-vampire": ["Flying", "Attack"],
    "seraph": ["Flying", "Attack"],
    "serendib-djinn": ["Flying", "Attack"],
    "serendib-efreet": ["Flying", "Attack"],
    "serra-angel": ["Flying", "Vigilance", "Attack"],
    "shanodin-dryads": ["Forestwalk", "Attack"],
    "shield-bearer": ["Banding", "Attack"],
    "shivan-dragon": ["Flying", "Attack"],
    "sibilant-spirit": ["Flying", "Attack"],
    "solkanar-the-swamp-king": ["Swampwalk", "Attack"],
    "stone-throwing-devils": ["First Strike", "Attack"],
    "tetravus": ["Flying", "Attack"],
    "thunder-spirit": ["Flying", "First Strike", "Attack"],
    "timber-wolves": ["Banding", "Attack"],
    "tuknir-deathlock": ["Flying", "Attack"],
    "tundra-wolves": ["First Strike", "Attack"],
    "two-headed-giant-of-foriys": ["Trample", "Attack"],
    "ur-drago": ["First Strike", "Attack"],
    "vaevictis-asmadi": ["Flying", "Attack"],
    "vampire-bats": ["Flying", "Attack"],
    "wall-of-air": ["Defender", "Flying"],
    "wall-of-bone": ["Defender"],
    "wall-of-brambles": ["Defender"],
    "wall-of-caltrops": ["Defender"],
    "wall-of-dust": ["Defender"],
    "wall-of-earth": ["Defender"],
    "wall-of-fire": ["Defender"],
    "wall-of-heat": ["Defender"],
    "wall-of-ice": ["Defender"],
    "wall-of-light": ["Defender", "Protection From Black"],
    "wall-of-opposition": ["Defender"],
    "wall-of-putrid-flesh": ["Defender", "Protection From White"],
    "wall-of-shadows": ["Defender"],
    "wall-of-spears": ["Defender", "First Strike"],
    "wall-of-stone": ["Defender"],
    "wall-of-swords": ["Defender", "Flying"],
    "wall-of-tombstones": ["Defender"],
    "wall-of-vapor": ["Defender"],
    "wall-of-water": ["Defender"],
    "wall-of-wonder": ["Defender"],
    "wall-of-wood": ["Defender"],
    "war-elephant": ["Trample", "Attack"],
    "war-mammoth": ["Trample", "Attack"],
    "whirling-dervish": ["Protection From Black", "Attack"],
    "white-knight": ["First Strike", "Protection From Black", "Attack"],
    "will-o-the-wisp": ["Flying", "Attack"],
    "wind-spirit": ["Flying", "Menace", "Attack"],
    "wolverine-pack": ["Rampage 2", "Attack"],
    "xira-arien": ["Flying", "Attack"],
    "yawgmoth-demon": ["Flying", "First Strike", "Attack"],
    "yotian-soldier": ["Vigilance", "Attack"],
    "zephyr-falcon": ["Flying", "Vigilance", "Attack"],
}

def get_base_kwas(slug: str) -> list[str | None]:
    return CREATURE_KW_ABILITIES.get(slug, [])


if __name__ == '__main__':
    for the_slug, kwas in CREATURE_KW_ABILITIES.items():
        for kwa in kwas:
            if kwa not in KEYWORD_ABILITIES:
                raise ValueError(f"{the_slug}'s {kwa} not found in KEYWORD_ABILITIES")
