from __future__ import annotations
from itertools import combinations

from .card_filter_funcs import C_FUNCS, A_FUNCS, TF
from models.constants import COLOR_LETTERS, KW
from models.cost import SacSelfCost, DiscardAtRandomCost, SacCardCost
from models.game_card.counter_tokens import PLUS_ONE_ZERO, PLUS_ONE, DOOM
from models.effects.base import EffSpec, Activated, Triggered, Static, Spell
from ..target import TargetSpec
from ..effects.resolvers_a_to_e import Disharmony, CityOfShadowsAddCounter, CityOfShadowsAddMana, CocoonCast, Banshee, \
    Earthquake, EternalFlame, AshesToAshes, DustToDust, EaterOfTheDead, BazaarOfBaghdad, Braingeyser, \
    DemonicTutor, Clone, CopyArtifact, EvilPresence, DrainPower, EnergyTap, Berserk, BloodLust, \
    AshnodsTransmogrant, ActiveVolcano, Amnesia, AnimateDead, BookOfRass, BottleOfSuleiman, ChaosOrb, \
    Crumble, DivineOffering, Earthbind, ElectricEel, ElvesOfTheDeepShadow, ArenaOfTheAncientsCast, \
    EnchantmentAlteration, DanceOfMany, Disintegrate, CuombajjWitches, Cleansing, DrafnasRestoration, Eureka, \
    DiamondValley, ConsecrateLand
from models.effects.resolvers_generic import AddCounter, DealDamage, DealDamageToTargetAndYou, Destroy, DestroyAll, \
    Regenerate, SacAll, DrawCards, Discard, SetColor, KWAModEffect, GainLife, AddMana, Bounce, Steal, \
    Pump, CreateTokenCreature, RemoveHostAuras, TapCardEffect, UntapCardEffect, UntapCardsEffect, RemoveFromCombat, \
    CounterSpell, AddStunCounter, BecomeCreaturePTEqualsManaValue, EmptyResolver, RemoveCounter
from .effect_spec_templates import dual_land_specs, MANA_BATTERY_ADD_CHARGE, mana_battery_add_mana, self_pump, \
    clockwork_avian_x, clockwork_beast_x, max_x_from_printed_card, your_tapped_land_cnt_and_max_x
from ..effects.listeners_misc import AliFromCairo, ArtifactPossessionActivation
from ..effects.listeners_state_change import GlobalSac
from ..effects.listeners_zone_change import AnkhOfMishra, CitanulDruid, DingusEgg
from ..effects.listeners_upkeep import BlackVise, CocoonUpkeep, CosmicHorror, CurseArtifact, Cyclone, \
    DemonicHordesUpkeep, DropOfHoney, ElderSpawnUpkeep, EnergyFlux, ErhnamDjinn, ErosionUpkeep
from ..effects.listeners_tap_untap import Blight, CityOfBrassDamageOnTap, ArtifactPossessionTap
from ..effects.listeners_end_step import DragonWhelpEndStep, ErgRaiders
from ..effects.listeners_draw_discard import CursedRack, ArmageddonClockDrawStep
from ..effects.listeners_dies import AbuJafar, AxelrodGunnarson, CreatureBond, CyclopeanMummy, BlazingEffigy, BrineHag
from ..effects.listeners_damage import Backfire, ElHajjaj, EyeForAnEye, BloodOfTheMartyr
from ..effects.listeners_combat import CavePeopleAttackPump, ElderLandWurm, AislingLeprechaun, Arboria, \
    ClockworkCombatEnd
from ..effects.listeners_generic import OnColorSpellPayOneColorlessForOneLifeChoice, \
    UntapRemovesPumpFromAnotherCard, OptionalUntap, DealDamageOnHostUpkeep, PayManaOrSacAtUpkeep, \
    DestroyAtEndStep, DealDamageOnEveryUpkeep, DestroyCombatantAtCombatEnd, PreventAllDamage, PreventAllDamageEOT, \
    PreventNextDamageTo, PreventNextDamageBy, PayManaToUntapUpkeep, AddCounterAtTargetUpkeep
from models.effects.listeners_permission import ArtifactWardCanBeTargeted, AkronLegionnaire, \
    EvilEyeOfOrmsByGoreMyNonEyeNoAttack, CantBeTargetedByAuras, HostCantAttack, \
    WalkRuleRemoved, DampingField, DoesntUntapAtUntap, CocoonUntap, HostCanAttack, UnblockableCondition, \
    UnblockableEOT, PreventRegenerationEOT, RegenerateSelf, AttackerCountMax, BlockerCountMax, CantCastAppliesTo, \
    HostCantBeTargetedBySpells
from models.effects.listeners_mod_queries import AngelicVoices, AngryMobPT, \
    AspectOfWolfPT, Conversion, PumpApplies, SelfPTEqualsFuncLen, KWAApplies, PumpAppliesEOT, BloodMoon, ManaProdAlter
from models.systems.phase import Phase

MAP: dict[str, list[EffSpec]] = {
    'abomination': [Triggered(DestroyCombatantAtCombatEnd(TF.self(), TF.green_and_white_creatures()))],
    'abu-jafar': [Triggered(AbuJafar())],
    'acid-rain': [Spell(DestroyAll(TF.forests()))],
    'active-volcano': [Spell(ActiveVolcano(), TF.active_volcano_targets())],
    'adun-oakenshield': [Activated('BRGT', Bounce(), TF.creatures_in_your_graveyard())],
    'aisling-leprechaun': [Triggered(AislingLeprechaun())],
    'akron-legionnaire': [Static(AkronLegionnaire())],
    'al-abaras-carpet': [Activated('5T', PreventAllDamageEOT(TF.owner(), TF.non_fliers(), True))],
    'alabaster-potion': [Spell(GainLife(), TF.all_players(), max_x_func=max_x_from_printed_card,
                               text="Target player gains X life"),
                         Spell(PreventNextDamageTo(), TF.all_creatures_and_players(),
                               max_x_func=max_x_from_printed_card,
                               text="Prevent the next X damage that would be dealt to any target this turn")],
    'aladdin': [Activated('1RRT', Steal(), TF.opp_artifacts())],
    'aladdins-ring': [Activated('8T', DealDamage(4), TF.all_creatures_and_players())],
    'ali-baba': [Activated('R', TapCardEffect(), TF.walls())],
    'ali-from-cairo': [Static(AliFromCairo())],
    'alchors-tomb': [Activated('2T', SetColor(c), TF.your_permanents(), text=f'Set color to {{{c}}}')
                     for c in COLOR_LETTERS],
    'amnesia': [Spell(Amnesia(), TF.all_players())],
    'amrou-kithkin': [Static(UnblockableCondition(TF.self(), TF.creatures_power_three_or_more()))],
    'amulet-of-kroog': [Activated('2T', PreventNextDamageBy(preventable_amt=1), TF.all_creatures_and_players())],
    'ancestral-recall': [Spell(DrawCards(3), TF.all_players())],
    'angelic-voices': [Static(AngelicVoices())],
    'angus-mackenzie': [Activated('GWUT', PreventAllDamageEOT(combat_only=True),
                                  allowed_phases=[p for p in Phase if p < Phase.COMBAT_DAMAGE])],
    'angry-mob': [Static(AngryMobPT())],
    'animate-artifact': [Spell(BecomeCreaturePTEqualsManaValue(), TF.non_creature_artifacts())],
    'animate-dead': [Spell(AnimateDead(), TF.creatures_in_your_graveyard())],
    'animate-wall': [Spell(HostCanAttack(), TF.walls())],
    'ankh-of-mishra': [Triggered(AnkhOfMishra())],
    'anti-magic-aura': [Static(CantBeTargetedByAuras(TF.host())), Static(HostCantBeTargetedBySpells()),
                        Spell(RemoveHostAuras(), TF.creatures())],
    'apprentice-wizard': [Activated('UT', AddMana('C', 3), TF.owner(), is_mana_ability=True)],
    'arboria': [Static(Arboria())],
    'arcades-sabboth': [Triggered(PayManaOrSacAtUpkeep('GWU')), self_pump('W', 0, 1),
                        Static(PumpApplies(TF.your_untapped_non_attacking_creatures(), (0, 2)))],
    'arena-of-the-ancients': [Triggered(DoesntUntapAtUntap(TF.legendary_creatures())),
                              Spell(ArenaOfTheAncientsCast())],
    'argivian-archaeologist': [Activated('WWT', Bounce(), TF.artifacts_in_your_graveyard())],
    'argivian-blacksmith': [Activated('T', PreventNextDamageBy(preventable_amt=2), TF.artifact_creatures())],
    'argothian-pixies': [Static(UnblockableCondition(TF.self(), TF.artifact_creatures())),
                         Static(PreventAllDamage(TF.self(), TF.artifact_creatures()))],
    'argothian-treefolk': [Static(PreventAllDamage(TF.self(), TF.artifacts()))],
    'armageddon': [Spell(DestroyAll(TF.lands()))],
    'armageddon-clock': [Activated('4', RemoveCounter(DOOM),
                                   allowed_phases=[Phase.UPKEEP], allowed_activators=A_FUNCS['all_players']),
                         Triggered(AddCounterAtTargetUpkeep(TF.self(), DOOM)),
                         Triggered(ArmageddonClockDrawStep())],
    'army-of-allah': [Spell(PumpAppliesEOT(TF.attackers(), (2, 0)))],
    'artifact-blast': [Spell(CounterSpell(), TF.artifact_spells())],
    'artifact-possession': [Triggered(ArtifactPossessionActivation()), Triggered(ArtifactPossessionTap()),
                            Spell(EmptyResolver(), TF.artifacts())],
    'artifact-ward': [Spell(EmptyResolver(), TF.creatures()), Static(ArtifactWardCanBeTargeted()),
                      Static(UnblockableCondition(TF.host(), TF.artifact_creatures())),
                      Static(PreventAllDamage(TF.host(), TF.artifacts()))],
    'ashes-to-ashes': [Spell(AshesToAshes(), TargetSpec(TF.non_artifact_creatures(), 2, 2))],
    'ashnods-altar': [Activated('', AddMana('C', 2), is_mana_ability=True
                                , extra_costs=[SacCardCost(TF.your_creatures())])],
    'ashnods-battle-gear': [Activated('2T', Pump(2, -2), TF.your_creatures()),
                            Triggered(OptionalUntap()), Triggered(UntapRemovesPumpFromAnotherCard())],
    'ashnods-transmogrant': [Activated('T', AshnodsTransmogrant(), TF.non_artifact_creatures(),
                                       extra_costs=[SacSelfCost()])],
    'aspect-of-wolf': [Static(AspectOfWolfPT())],
    'atog': [Activated('', Pump(2, 2), TF.self(), extra_costs=[SacCardCost(TF.your_artifacts())])],
    'avoid-fate': [Spell(CounterSpell(), TF.spells_aura_or_instant_targeting_your_perm())],
    'axelrod-gunnarson': [Triggered(AxelrodGunnarson())],
    'backfire': [Triggered(Backfire())],
    'bad-moon': [Static(PumpApplies(TF.black_creatures(), (1, 1)))],
    'badlands': dual_land_specs('BR'),
    'ball-lightning': [Triggered(DestroyAtEndStep(TF.self()))],
    'banshee': [Activated('XT', Banshee(), TF.all_creatures_and_players(), max_x_func=max_x_from_printed_card)],
    'barls-cage': [Activated('3', AddStunCounter(), TF.creatures())],
    'bartel-runeaxe': [Static(CantBeTargetedByAuras(TF.self()))],
    'basalt-monolith': [Triggered(DoesntUntapAtUntap(TF.self())),
                        Activated('T', AddMana('C', 3), is_mana_ability=True),
                        Activated('3', UntapCardEffect(), TF.self())],
    'bayou': dual_land_specs('BG'),
    'bazaar-of-baghdad': [Activated('2T', BazaarOfBaghdad(), text='Draw 2 cards; discard 3 cards')],
    'beasts-of-bogardan': [Static(PumpApplies(TF.self(), (1, 1), C_FUNCS['opp_has_non_token_white_perm']))],
    'berserk': [Spell(Berserk(), TF.creatures(), allowed_phases=[p for p in Phase if p < Phase.COMBAT_DAMAGE])],
    'birds-of-paradise': [Activated('T', AddMana(c), is_mana_ability=True, text=f'Add {{{c}}}') for c in COLOR_LETTERS],
    'black-lotus': [Activated('T', AddMana(c, 3), is_mana_ability=True, extra_costs=[SacSelfCost()],
                              text=f'Add {{3{c}}}') for c in COLOR_LETTERS],
    'black-mana-battery': [MANA_BATTERY_ADD_CHARGE, mana_battery_add_mana('B')],
    'black-vise': [Triggered(BlackVise())],
    'black-ward': [Spell(KWAModEffect('add', KW.PROTECTION_FROM_BLACK), TF.creatures())],
    'blazing-effigy': [Triggered(BlazingEffigy())],
    'blessing': [Activated('W', Pump(1, 1, True), TF.host())],
    'blight': [Spell(Blight(), TF.lands())],
    'blood-lust': [Spell(BloodLust(), TF.creatures())],
    'blood-moon': [Static(BloodMoon())],
    'blood-of-the-martyr': [Triggered(BloodOfTheMartyr())],
    'blue-elemental-blast': [Spell(CounterSpell(), TF.red_spells()), Spell(Destroy(), TF.red_permanents())],
    'blue-mana-battery': [MANA_BATTERY_ADD_CHARGE, mana_battery_add_mana('U')],
    'blue-ward': [Spell(KWAModEffect('add', KW.PROTECTION_FROM_BLUE), TF.creatures())],
    'bog-rats': [Static(UnblockableCondition(TF.self(), TF.walls()))],
    'bone-flute': [Activated('2T', PumpAppliesEOT(TF.creatures(), (-1, 0)))],
    'book-of-rass': [Activated('2', BookOfRass())],
    'boomerang': [Spell(Bounce(), TF.permanents())],
    'boris-devilboon': [Activated('2BRTT', CreateTokenCreature('minor-demon'))],
    'bottle-of-suleiman': [Activated('1', BottleOfSuleiman(), extra_costs=[SacSelfCost()])],
    'braingeyser': [Spell(Braingeyser(), TF.all_players())],
    'brainwash': [Spell(HostCantAttack(), TF.creatures()),
                  Activated('3', HostCanAttack(TF.host()), allowed_activators=A_FUNCS['host_owner'])],
    'brass-man': [Triggered(DoesntUntapAtUntap(TF.self())),
                  Triggered(PayManaToUntapUpkeep('1', TF.self()))],
    'brine-hag': [Triggered(BrineHag())],
    'brothers-of-fire': [Activated('T', DealDamageToTargetAndYou(1, 1), TF.all_creatures_and_players())],
    'burrowing': [Spell(KWAModEffect('add', KW.ISLANDWALK), TF.creatures())],
    'candelabra-of-tawnos': [Activated('XT', UntapCardsEffect(), TargetSpec(TF.your_tapped_lands(), 1, None),
                                       max_x_func=your_tapped_land_cnt_and_max_x)],
    'carrion-ants': [self_pump('1', 1, 1)],
    'castle': [Static(PumpApplies(TF.your_untapped_white_creatures(), (0, 2)))],
    'cave-people': [Triggered(CavePeopleAttackPump(), TF.self()),
                    Activated('1RRT', KWAModEffect('add', KW.ISLANDWALK, True), TF.creatures())],
    'caverns-of-despair': [Static(AttackerCountMax(2)), Static(BlockerCountMax(2))],
    'celestial-prism': [Activated('2T', AddMana(c), TF.owner(), is_mana_ability=True, text=f'Add 1 {c}')
                        for c in COLOR_LETTERS],
    'chaos-orb': [Activated('1T', ChaosOrb(), TF.opp_non_token_perms(), extra_costs=[SacSelfCost()],
                            text='If random di roll is 1-4, destroy target')],
    'chaoslace': [Spell(SetColor('R'), TF.cards())],
    'chromium': [Triggered(PayManaOrSacAtUpkeep('WUB'))],
    'circle-of-protection-artifacts': [Activated('1', PreventNextDamageTo(protected=TF.owner()), TF.artifacts())],
    'circle-of-protection-black': [Activated('1', PreventNextDamageTo(protected=TF.owner()), TF.black())],
    'circle-of-protection-blue': [Activated('1', PreventNextDamageTo(protected=TF.owner()), TF.blue())],
    'circle-of-protection-green': [Activated('1', PreventNextDamageTo(protected=TF.owner()), TF.green())],
    'circle-of-protection-red': [Activated('1', PreventNextDamageTo(protected=TF.owner()), TF.red())],
    'circle-of-protection-white': [Activated('1', PreventNextDamageTo(protected=TF.owner()), TF.white())],
    'citanul-druid': [Triggered(CitanulDruid())],
    'city-in-a-bottle': [Static(GlobalSac(TF.city_in_a_bottle())), Static(CantCastAppliesTo(TF.city_in_a_bottle())),
                         Spell(SacAll(TF.city_in_a_bottle()))],
    'city-of-brass': [Activated('T', AddMana(c), is_mana_ability=True, text=f'Add {{{c}}}') for c in COLOR_LETTERS] +
                     [Triggered(CityOfBrassDamageOnTap())],
    'city-of-shadows': [Activated('T', CityOfShadowsAddCounter(), extra_costs=[SacCardCost(TF.your_creatures())]),
                        Activated('T', CityOfShadowsAddMana(), is_mana_ability=True)],
    'clay-statue': [Activated('2', Regenerate(), TF.self())],
    'cleanse': [Spell(DestroyAll(TF.black_creatures()))],
    'cleansing': [Spell(Cleansing())],
    'clergy-of-the-holy-nimbus': [Static(RegenerateSelf()), Activated('1', PreventRegenerationEOT(), TF.self(),
                                                                      allowed_activators=A_FUNCS['opponent'])],
    'clockwork-avian': [Static(ClockworkCombatEnd()),
                        Activated('XT', AddCounter(PLUS_ONE_ZERO), TF.self(), allowed_phases=[Phase.UPKEEP],
                                  allowed_p_turn_func=TF.owner(), max_x_func=clockwork_avian_x),
                        Spell(AddCounter(PLUS_ONE_ZERO, 4))],
    'clockwork-beast': [Static(ClockworkCombatEnd()),
                        Activated('XT', AddCounter(PLUS_ONE_ZERO), TF.self(), allowed_phases=[Phase.UPKEEP],
                                  allowed_p_turn_func=TF.owner(), max_x_func=clockwork_beast_x),
                        Spell(AddCounter(PLUS_ONE_ZERO, 7))],
    'clone': [Spell(Clone())],
    'coal-golem': [Activated('3', AddMana('R', 3), TF.owner(), is_mana_ability=True,
                             extra_costs=[SacSelfCost()])],
    'cockatrice': [Triggered(DestroyCombatantAtCombatEnd(TF.self(), TF.non_wall_creatures()))],
    'cocoon': [Spell(CocoonCast(), TF.your_creatures()), Static(CocoonUntap()), Static(CocoonUpkeep())],
    'colossus-of-sardia': [Triggered(DoesntUntapAtUntap(TF.self())), Triggered(PayManaToUntapUpkeep('9', TF.self()))],
    'concordant-crossroads': [Static(KWAApplies(TF.creatures(), 'add', KW.HASTE))],
    'consecrate-land': [Spell(ConsecrateLand(), TF.lands())],
    'conservator': [Activated('3T', PreventNextDamageTo(protected=TF.owner()))],
    'control-magic': [Spell(Steal(), TF.opp_creatures())],
    'conversion': [Triggered(PayManaOrSacAtUpkeep('WW')), Static(Conversion())],
    'copper-tablet': [Static(DealDamageOnEveryUpkeep(TF.in_turn_player(), 1))],
    'copy-artifact': [Spell(CopyArtifact())],
    'coral-helm': [Activated('3', Pump(2, 2, True), TF.creatures(), extra_costs=[DiscardAtRandomCost()])],
    'cosmic-horror': [Static(CosmicHorror())],
    'counterspell': [Spell(CounterSpell(), TF.spells())],
    'crevasse': [Static(WalkRuleRemoved(KW.ISLANDWALK))],
    'creature-bond': [Triggered(CreatureBond())],
    'crimson-manticore': [Activated('RT', DealDamage(1), TF.combatants())],
    'crumble': [Spell(Crumble(), TF.artifacts())],
    'crusade': [Static(PumpApplies(TF.white_creatures(), (1, 1)))],
    'crystal-rod': [Static(OnColorSpellPayOneColorlessForOneLifeChoice('U'))],
    'cuombajj-witches': [Activated('T', CuombajjWitches(), TF.all_creatures_and_players())],
    'curse-artifact': [Spell(CurseArtifact(), TF.artifacts())],
    'cursed-land': [Spell(DealDamageOnHostUpkeep(1), TF.lands())],
    'cursed-rack': [Triggered(CursedRack())],
    'cyclone': [Triggered(Cyclone())],
    'cyclopean-mummy': [Triggered(CyclopeanMummy())],
    'dakkon-blackblade': [Static(SelfPTEqualsFuncLen(TF.your_lands()))],
    'damping-field': [Triggered(DampingField())],
    'dance-of-many': [Triggered(PayManaOrSacAtUpkeep('UU')), Spell(DanceOfMany(), TF.non_token_creatures())],
    'dark-heart-of-the-wood': [Activated('', GainLife(3), extra_costs=[SacCardCost(TF.your_forests())])],
    'dark-ritual': [Spell(AddMana('B', 3))],
    'dark-sphere': [Activated('T', PreventNextDamageTo(protected=TF.owner()), TF.artifacts(),
                              extra_costs=[SacSelfCost()])],
    'darkness': [Spell(PreventAllDamageEOT(combat_only=True))],
    'davenant-archer': [Activated('T', DealDamage(1), TF.combatants())],
    'deadfall': [Static(WalkRuleRemoved(KW.FORESTWALK))],
    'deathgrip': [Activated('BB', CounterSpell(), TF.green_spells())],
    'deathlace': [Spell(SetColor('B'), TF.cards())],
    'death-ward': [Spell(Regenerate(), TF.creatures())],
    'deep-water': [Activated('T', ManaProdAlter('U', TF.your_lands(), eot=True))],
    'demonic-hordes': [Activated('T', Destroy(), TF.lands()), Triggered(DemonicHordesUpkeep())],
    'demonic-torment': [Spell(HostCantAttack(), TF.creatures()),
                        Static(PreventAllDamageEOT(dealer_func=TF.host(), combat_only=True))],
    'demonic-tutor': [Spell(DemonicTutor())],
    'desert': [Activated('T', AddMana('C'), is_mana_ability=True),
               Activated('T', DealDamage(1), TF.attackers(), allowed_phases=[Phase.COMBAT_END])],
    'desert-twister': [Spell(Destroy(), TF.permanents())],
    'diabolic-machine': [Activated('3', Regenerate(), TF.self())],
    'diamond-valley': [Activated('T', DiamondValley(), extra_costs=[SacCardCost(TF.your_creatures())])],
    'dingus-egg': [Triggered(DingusEgg())],
    'disharmony': [Spell(Disharmony(), TF.attackers(), allowed_phases=[Phase.DECLARE_COMBAT, Phase.DECLARE_ATTACKERS])],
    'disintegrate': [Spell(Disintegrate(), TF.all_creatures_and_players())],
    'disrupting-scepter': [Activated('3T', Discard(), TF.all_players(), allowed_p_turn_func=TF.owner())],
    'disenchant': [Spell(Destroy(), TF.artifacts_and_enchantments())],
    'divine-offering': [Spell(DivineOffering(), TF.artifacts())],
    'divine-transformation': [Spell(Pump(3, 3), TF.creatures())],
    'drafnas-restoration': [Spell(DrafnasRestoration(), TF.all_players())],
    'dragon-engine': [self_pump('2', 1, 0)],
    'dragon-whelp': [self_pump('R', 1, 0), Triggered(DragonWhelpEndStep())],
    'drain-power': [Spell(DrainPower(), TF.opp())],
    'dream-coat': [Spell(EmptyResolver(), TF.creatures())] +
                  [Activated('', SetColor(''.join(combo)), TF.host(), max_activations_per_turn=1, text=f'{{{combo}}}')
                   for r in range(1, len(COLOR_LETTERS) + 1) for combo in combinations(COLOR_LETTERS, r)],
    'drop-of-honey': [Triggered(DropOfHoney())],
    'drowned': [Activated('B', Regenerate(), TF.self())],
    'drudge-skeletons': [Activated('B', Regenerate(), TF.self())],
    'dust-to-dust': [Spell(DustToDust(), TargetSpec(TF.artifacts(), 2, 2))],
    'dwarven-demolition-team': [Activated('T', Destroy(), TF.walls())],
    'dwarven-song': [Spell(SetColor('R', 'EOT'), TargetSpec(TF.creatures(), 1, None))],
    'dwarven-warriors': [Activated('T', UnblockableEOT(), TF.creatures_power_two_or_less())],
    'dwarven-weaponsmith': [Activated('T', AddCounter(PLUS_ONE), TF.creatures(),
                                      extra_costs=[SacCardCost(TF.your_artifacts())],
                                      allowed_phases=[Phase.UPKEEP], allowed_p_turn_func=TF.owner())],
    'earthbind': [Spell(Earthbind(), TF.creatures())],
    'earthquake': [Spell(Earthquake())],
    'eater-of-the-dead': [Activated('', EaterOfTheDead(), TF.creatures_in_all_graveyards())],
    'ebony-horse': [Activated('2T', RemoveFromCombat(), TF.attackers())],
    'el-hajjaj': [Triggered(ElHajjaj(), TF.self())],
    'elder-land-wurm': [Triggered(ElderLandWurm())],
    'elder-spawn': [Triggered(ElderSpawnUpkeep()), Static(UnblockableCondition(TF.self(), TF.red()))],
    'electric-eel': [Spell(DealDamage(1), TF.owner()), Activated('RR', ElectricEel())],
    'elephant-graveyard': [Activated('T', AddMana('C'), is_mana_ability=True),
                           Activated('T', Regenerate(), TF.elephants())],
    'elven-riders': [Static(UnblockableCondition(TF.self(), TF.non_wall_non_fliers()))],
    'elves-of-deep-shadow': [Activated('T', ElvesOfTheDeepShadow(), is_mana_ability=True)],
    'emerald-dragonfly': [Activated('GG', KWAModEffect('add', KW.FIRST_STRIKE, True), TF.self())],
    'enchanted-being': [Static(PreventAllDamage(TF.self(), TF.enchanted_creatures(), combat_only=True))],
    'enchantment-alteration': [Spell(EnchantmentAlteration(), TF.auras_on_creatures_or_lands())],
    'energy-flux': [Triggered(EnergyFlux())],
    'energy-tap': [Spell(EnergyTap(), TF.your_untapped_creatures())],
    'erg-raiders': [Triggered(ErgRaiders())],
    'erhnam-djinn': [Triggered(ErhnamDjinn(), TF.opp_non_wall_creatures())],
    'erosion': [Spell(ErosionUpkeep(), TF.lands())],
    'eternal-flame': [Spell(EternalFlame())],
    'eternal-warrior': [Spell(KWAModEffect('add', KW.VIGILANCE), TF.creatures())],
    'eureka': [Spell(Eureka())],
    'evil-eye-of-orms-by-gore': [Static(UnblockableCondition(TF.self(), TF.non_wall_creatures())),
                                 Static(EvilEyeOfOrmsByGoreMyNonEyeNoAttack())],
    'evil-presence': [Spell(EvilPresence(), TF.lands())],
    'exorcist': [Activated('1W', Destroy(), TF.black_creatures())],
    'eye-for-an-eye': [Spell(EyeForAnEye(), TF.cards())],
}
