from __future__ import annotations

from .effect_spec_templates import dual_land_specs, MANA_BATTERY_ADD_CHARGE, mana_battery_add_mana, self_pump, \
    voodoo_doll_x, max_x_from_printed_card
from .card_filter_funcs import T_FUNCS, C_FUNCS
from models.constants import COLOR_LETTERS, BASIC_LANDS
from models.cost import SacSelfCost, PayLifeCost, RemoveCounterCost, SacCardCost
from models.counter_tokens import PLUS_ONE, CORPSE, MINUS_ONE, SLEEP, PIN, DREAM, HATCHLING
from models.effects.base import EffSpec, Activated, Triggered, Static, Spell
from ..effects.listeners_misc import PowerleechActivation, VerduranEnchantress
from ..target import TargetSpec
from ..effects.resolvers_p_to_z import ReversePolarity, Simulacrum, TangleKelp, Telekinesis, TowerOfCoireall, \
    RockHydraCast, Sandstorm, StormSeeker, Tracker, Typhoon, RagMan, UntamedWilds, Visions, WheelOfFortune, \
    PhantasmalTerrain, PrimalClay, VesuvanDoppelgangerCast, RapidFire, SandalsOfAbdallahIslandWalk, \
    UrborgLoseFirstStrike, UrborgLoseSwampwalk, StreamOfLife, UrzasTrio, TimeElementalBounce, TriassicEggA, \
    SingingTree, Rakalite, RocketLauncher, \
    SacrificeOnCast, SafeHaven, ShapeshifterCast, StoneGiant, Subdue, SwordsToPlowshares, SyphonSoul, \
    Timetwister, UrzasAvengerFlying, UrzasAvengerFirstStrike, UrzasAvengerTrample, WallOfWonder, WandOfIth, Web, \
    WindsOfChange, WinterBlast, WoodElemental, WormwoodTreefolkForestwalk, WormwoodTreefolkSwampwalk, Reset, Riptide, \
    Twiddle, Sindbad, SirensCall, VenarianGoldCast, TriassicEggB
from models.effects.resolvers_generic import AddCounter, DealDamage, DealOneDamageToTargetList, \
    DealDamageToAllCreaturesAndPlayers, DealDamageToTargetAndSelf, DealDamageToTargetAndYou, Destroy, DestroyAll, \
    ExileAllCreatures, Regenerate, DrawCards, SetColor, KWAModEffect, AddMana, Bounce, Reanimate, Steal, \
    GraveyardToExileInItsEntirety, Pump, CreateTokenCreature, TapCardEffect, TapCardsEffect, UntapCardEffect, \
    DeclareAColor, CounterSpell, RevealHands, BecomeCreaturePTEqualsManaValue
from ..effects.listeners_state_change import GlobalSac
from ..effects.listeners_zone_change import Revelation, StanggOnLeave, TawnossCoffinZoneChange, TheWretchedUnsteal
from ..effects.listeners_upkeep import PowerSurge, PsychicAllergyDamage, PsychicAllergySac, RasputinDreamweaverUpkeep, \
    RogahhOfKherKeepUpkeep, SafeHavenUpkeep, SeasonOfTheWitchUpkeep, SpiritualSanctuary, StormWorld, TheAbyss, \
    TheFallen, TheRack, TheTabernacleAtPendrellVale, VesuvanDoppelgangerUpkeep, XenicPoltergeistRelease, YawgmothDemon, \
    PowerLeak, SerendibDjinn, ShapeshifterUpkeep
from ..effects.listeners_tap_untap import PsychicVenom, SpiritShackle, WildGrowth, TawnossCoffinUntap, \
    RasputinDreamweaverUntap, TimeVaultOption, PowerleechTap
from ..effects.listeners_end_step import PestilenceEndStep, SeasonOfTheWitchEndStep, VoodooDollEndStep, WhirlingDervish
from ..effects.listeners_draw_discard import PsychicPurgeDiscard
from ..effects.listeners_dies import PersonalIncarnationDies, RukhEgg, SengirVampire, SuChi, SoulNet, TabletOfEpityr, \
    UrzasMiter
from ..effects.listeners_damage import RockHydraAutoDamagePrevent, VeteranBodyguard, SpiritLink, ReverseDamage
from ..effects.listeners_cost import PlanarGate, PowerArtifact, StoneCalendar
from ..effects.listeners_combat import Sentinel, WallOfDust, YdwenEfreet, TimeElementalAttackedOrBlocked, \
    TheWretchedSteal
from ..effects.listeners_generic import OnColorSpellGainLife, OnColorSpellPayOneColorlessForOneLifeChoice, \
    AddPoisonCounter, ReturnToOwnerOnUntap, UntapRemovesPumpFromAnotherCard, OptionalUntap, \
    DealDamageToOwnerOnUpkeep, DealDamageOnHostUpkeep, ReturnToOwnerOnLTB, \
    PreventCombatDamageFromItsAttackers, PayManaOrSacAtUpkeep, \
    AddCounterPerCreatureDeathAtEndStep, AddCounterAtTargetUpkeep, RemoveCounterAtTargetUpkeep, PayManaToUntapUpkeep, \
    DestroyCombatantAtCombatEnd, PreventAllDamage, PreventAllDamageEOT, PreventAllDamageToEOT, PreventNextDamageTo, \
    PreventNextDamageBy, RedirectNextDamageFromCardToOwnerEOT, TakeAnotherTurn
from models.effects.listeners_permission import CantBeTargetedByAuras, SpectralCloak, \
    WalkRuleRemoved, Smoke, WinterOrb, DoesntUntapAtUntap, SkipUntapPhase, VenarianGoldAtUntap, UnblockableCondition, \
    UnblockableEOT
from models.effects.listeners_mod_queries import RabidWombat, WallOfTombstonesPT, PTModEqualsManaValue, \
    PumpApplies, SelfPTEquals, KWAApplies, PumpAppliesEOT, Transmutation
from models.systems.phase import Phase

MAP: dict[str, list[EffSpec]] = {
    'palladia-mors': [Triggered(PayManaOrSacAtUpkeep('RGW'))],
    'paralyze': [Triggered(DoesntUntapAtUntap(T_FUNCS['host'])), Static(PayManaToUntapUpkeep('4', T_FUNCS['host'])),
                 Spell(TapCardEffect(), T_FUNCS['host'])],
    'part-water': [Spell(KWAModEffect('add', 'Islandwalk', True), T_FUNCS['creatures'],
                         max_x_func=max_x_from_printed_card)],
    'pavel-maliki': [self_pump('BR', 1, 0)],
    'pendelhaven': [Activated('T', AddMana('G'), T_FUNCS['owner']),
                    Activated('T', Pump(1, 2, True), T_FUNCS['one_one_creatures'])],
    'people-of-the-woods': [Static(SelfPTEquals(T_FUNCS['your_forests'], t_only=True))],
    'personal-incarnation': [Triggered(PersonalIncarnationDies()),
                             Activated('', RedirectNextDamageFromCardToOwnerEOT(T_FUNCS['self'], 1))],
    'pestilence': [Activated('B', DealDamageToAllCreaturesAndPlayers(1)), Triggered(PestilenceEndStep())],
    'phantasmal-forces': [Triggered(PayManaOrSacAtUpkeep('U'))],
    'phantasmal-terrain': [Spell(PhantasmalTerrain(), T_FUNCS['lands'])],
    'phyrexian-gremlins': [Triggered(OptionalUntap())],  # more to code
    'piety': [Spell(PumpAppliesEOT(T_FUNCS['blockers'], (0, 3)))],
    'pirate-ship': [Activated('T', DealDamage(1), T_FUNCS['all_creatures_and_players'])],
    'pit-scorpion': [Triggered(AddPoisonCounter())],
    'pixie-queen': [Activated('GGGT', KWAModEffect('add', 'Flying'), T_FUNCS['creatures'])],
    'plague-rats': [Static(SelfPTEquals(T_FUNCS['plague_rats']))],
    'planar-gate': [Static(PlanarGate())],
    'plateau': dual_land_specs('RW'),
    'power-artifact': [Spell(PowerArtifact(), T_FUNCS['artifacts'])],
    'power-leak': [Static(PowerLeak())],
    'power-surge': [Triggered(PowerSurge())],
    'powerleech': [Triggered(PowerleechActivation()), Triggered(PowerleechTap())],
    'pradesh-gypsies': [Activated('1GT', Pump(-2, 0, True), T_FUNCS['creatures'])],
    'preacher': [Activated('T', Steal(), T_FUNCS['opp_creatures']), Triggered(OptionalUntap()),
                 Triggered(ReturnToOwnerOnUntap())],
    'primal-clay': [Spell(PrimalClay())],
    'primordial-ooze': [Static(AddCounterAtTargetUpkeep(T_FUNCS['self'], PLUS_ONE))],  # more to code
    'princess-lucrezia': [Activated('T', AddMana('U'))],
    'prodigal-sorcerer': [Activated('T', DealDamage(1), T_FUNCS['all_creatures_and_players'], text="Deal 1 Damage}")],
    'psionic-blast': [Spell(DealDamageToTargetAndYou(4, 2), T_FUNCS['all_creatures_and_players'])],
    'psionic-entity': [Activated('T', DealDamageToTargetAndSelf(2, 3), T_FUNCS['all_creatures_and_players'])],
    'psychic-allergy': [Triggered(PsychicAllergySac()), Triggered(DeclareAColor()), Spell(PsychicAllergyDamage())],
    'psychic-purge': [Triggered(PsychicPurgeDiscard()), Spell(DealDamage(1), T_FUNCS['all_creatures_and_players'])],
    'psychic-venom': [Spell(PsychicVenom(), T_FUNCS['lands'])],
    'purelace': [Spell(SetColor('W'), T_FUNCS['cards'])],
    'pyrotechnics': [Spell(DealOneDamageToTargetList(), TargetSpec(T_FUNCS['all_creatures_and_players'], 1, 4,
                                                                   allow_duplicate_targets=True))],
    'quagmire': [Static(WalkRuleRemoved('Swampwalk'))],
    'rabid-wombat': [Static(RabidWombat())],
    'radjan-spirit': [Activated('T', KWAModEffect('remove', 'Flying', True), T_FUNCS['creatures'])],
    'rag-man': [Activated('BBBT', RagMan(), T_FUNCS['opp'], allowed_p_turn_func=T_FUNCS['owner'])],
    'ragnar': [Activated('GWUT', Regenerate(), T_FUNCS['creatures'])],
    'raise-dead': [Spell(Bounce(), T_FUNCS['creatures_in_your_graveyard'])],
    'rakalite': [Activated('2', Rakalite(), T_FUNCS['all_creatures_and_players'])],
    'ramses-overdark': [Activated('T', Destroy(), T_FUNCS['enchanted_creatures'])],
    'rapid-fire': [Spell(RapidFire(), T_FUNCS['creatures'],
                         allowed_phases=[p for p in Phase if p < Phase.DECLARE_BLOCKERS])],
    'rasputin-dreamweaver': [Activated('', AddMana('C'), extra_costs=[RemoveCounterCost(DREAM)]),
                             Activated('', PreventNextDamageTo(1), T_FUNCS['self'],
                                       extra_costs=[RemoveCounterCost(DREAM)]),
                             Triggered(RasputinDreamweaverUntap()), Triggered(RasputinDreamweaverUpkeep()),
                             Spell(AddCounter(DREAM, 7))],
    'reconstruction': [Spell(Bounce(), T_FUNCS['artifacts_in_your_graveyard'])],
    'red-elemental-blast': [Spell(CounterSpell(), T_FUNCS['blue_spells']),
                            Spell(Destroy(), T_FUNCS['blue_permanents'])],
    'red-mana-battery': [MANA_BATTERY_ADD_CHARGE, mana_battery_add_mana('R')],
    'red-ward': [Spell(KWAModEffect('add', 'Protection From Red'), T_FUNCS['creatures'])],
    'regeneration': [Activated('G', Regenerate(), T_FUNCS['host'])],
    'regrowth': [Spell(Bounce(), T_FUNCS['cards_in_your_graveyard'])],
    'relic-barrier': [Activated('T', TapCardEffect(), T_FUNCS['untapped_artifacts'])],
    'remove-soul': [Spell(CounterSpell(), T_FUNCS['creature_spells'])],
    'reset': [Spell(Reset(), allowed_p_turn_func=T_FUNCS['opp'],
                    allowed_phases=[p for p in Phase if p >= Phase.UPKEEP])],
    'resurrection': [Spell(Reanimate(), T_FUNCS['creatures_in_your_graveyard'])],
    'revelation': [Static(Revelation()), Spell(RevealHands())],
    'reverse-damage': [Spell(ReverseDamage(), T_FUNCS['cards'])],
    'reverse-polarity': [Spell(ReversePolarity())],
    'righteousness': [Spell(Pump(7, 7, True), T_FUNCS['blockers'])],
    'riptide': [Spell(Riptide())],
    'riven-turnbull': [Activated('T', AddMana('B'))],
    'rock-hydra': [Static(RockHydraAutoDamagePrevent()),
                   Activated('R', PreventNextDamageTo(1), T_FUNCS['self']),
                   Activated('RRR', AddCounter(PLUS_ONE)),
                   Spell(RockHydraCast(), T_FUNCS['self'], max_x_func=max_x_from_printed_card)],
    'rocket-launcher': [Activated('2', RocketLauncher(), T_FUNCS['all_creatures_and_players'])],
    'rod-of-ruin': [Activated('3T', DealDamage(1), T_FUNCS['all_creatures_and_players'])],
    'rohgahh-of-kher-keep': [Static(PumpApplies(T_FUNCS['your_kobolds_of_kher_keep'], (2, 2))),
                             Triggered(RogahhOfKherKeepUpkeep())],
    'royal-assassin': [Activated('T', Destroy(), T_FUNCS['tapped_creatures'])],
    'rubinia-soulsinger': [Activated('T', Steal(), T_FUNCS['opp_creatures']),
                           Triggered(OptionalUntap()), Triggered(ReturnToOwnerOnUntap()),
                           Triggered(ReturnToOwnerOnLTB())],
    'rukh-egg': [Triggered(RukhEgg())],
    'sacrifice': [Spell(SacrificeOnCast(), extra_costs=[SacCardCost(T_FUNCS['your_creatures'])])],
    'safe-haven': [Activated('2T', SafeHaven(), T_FUNCS['your_creatures']), Triggered(SafeHavenUpkeep())],
    'sage-of-lat-nam': [Activated('T', DrawCards(), T_FUNCS['owner'],
                                  extra_costs=[SacCardCost(T_FUNCS['your_artifacts'])])],
    'samite-healer': [Activated('T', PreventNextDamageBy(preventable_amt=1), T_FUNCS['cards'])],
    'sandals-of-abdallah': [Activated('2', SandalsOfAbdallahIslandWalk(), T_FUNCS['creatures'])],
    'sandstorm': [Spell(Sandstorm())],
    'savaen-elves': [Activated('GGT', Destroy(), T_FUNCS['auras_on_lands'])],
    'savannah': dual_land_specs('GW'),
    'scarecrow': [Activated('6T', PreventAllDamageEOT(T_FUNCS['owner'], T_FUNCS['fliers']))],
    'scarwood-hag': [Activated('GGGGT', KWAModEffect('add', 'Forestwalk', True), T_FUNCS['creatures_wo_forestwalk']),
                     Activated('T', KWAModEffect('remove', 'Forestwalk', True), T_FUNCS['forestwalkers'])],
    'scavenger-folk': [Activated('GT', Destroy(), T_FUNCS['artifacts'], extra_costs=[SacSelfCost()])],
    'scavenging-ghoul': [Triggered(AddCounterPerCreatureDeathAtEndStep(CORPSE)),
                         Activated('', Regenerate(), T_FUNCS['self'], extra_costs=[RemoveCounterCost(CORPSE)])],
    'scrubland': dual_land_specs('BW'),
    'sea-kings-blessing': [Spell(SetColor('U', 'EOT'), TargetSpec(T_FUNCS['creatures'], 1, None))],
    'season-of-the-witch': [Triggered(SeasonOfTheWitchUpkeep()), Triggered(SeasonOfTheWitchEndStep())],
    'sedge-troll': [Static(PumpApplies(T_FUNCS['self'], (1, 2), C_FUNCS['you_have_a_swamp'])),
                    Activated('B', Regenerate(), T_FUNCS['self'])],
    'seeker': [Static(UnblockableCondition(T_FUNCS['host'], T_FUNCS['non_artifact_non_white_creatures']))],
    'sengir-vampire': [Triggered(SengirVampire())],
    'sentinel': [Activated('', Sentinel())],
    'serendib-djinn': [Triggered(SerendibDjinn()), Static(GlobalSac(T_FUNCS['self'], C_FUNCS['you_have_no_lands']))],
    'serendib-efreet': [Triggered(DealDamageToOwnerOnUpkeep(1), T_FUNCS['self'])],
    'serpent-generator': [Activated('4T', CreateTokenCreature('snake'))],
    'shapeshifter': [Spell(ShapeshifterCast()), Static(ShapeshifterUpkeep())],
    'shatter': [Spell(Destroy(), T_FUNCS['artifacts'])],
    'shatterstorm': [Spell(DestroyAll(T_FUNCS['artifacts'], False))],
    'shield-wall': [Spell(PumpAppliesEOT(T_FUNCS['your_creatures'], (0, 2)))],
    'shivan-dragon': [self_pump('R', 1, 0)],
    'silhouette': [Triggered(PreventAllDamageToEOT(combat_only=True), T_FUNCS['creatures'])],
    'simulacrum': [Spell(Simulacrum())],
    'sindbad': [Activated('T', Sindbad())],
    'singing-tree': [Activated('T', SingingTree(), T_FUNCS['attackers'])],
    'sinkhole': [Spell(Destroy(), T_FUNCS['lands'])],
    'sirens-call': [Spell(SirensCall(), allowed_p_turn_func=T_FUNCS['opp'],
                          allowed_phases=[p for p in Phase if p < Phase.DECLARE_ATTACKERS])],
    'sisters-of-the-flame': [Activated('T', AddMana('R'), T_FUNCS['owner'])],
    'skull-of-orm': [Activated('5T', Bounce(), T_FUNCS['enchants_in_your_graveyard'])],
    'smoke': [Triggered(Smoke())],
    'snake': [Triggered(AddPoisonCounter())],  # token creature created by serpent-generator
    'sol-ring': [Activated('T', AddMana('C', 2), T_FUNCS['owner'])],
    'solkanar-the-swamp-king': [Spell(OnColorSpellGainLife('B'))],
    'soul-net': [Triggered(SoulNet())],
    'spectral-cloak': [Spell(SpectralCloak(), T_FUNCS['creatures'])],
    'spinal-villain': [Activated('T', Destroy(), T_FUNCS['blue_creatures'])],
    'spirit-link': [Spell(SpiritLink(), T_FUNCS['creatures'])],
    'spirit-shackle': [Spell(SpiritShackle(), T_FUNCS['creatures'])],
    'spiritual-sanctuary': [Triggered(SpiritualSanctuary())],
    'staff-of-zegon': [Activated('3T', Pump(-2, 0, True), T_FUNCS['creatures'])],
    'standing-stones': [Activated('1T', AddMana(c), text=f'Add {{{c}}}', extra_costs=PayLifeCost())
                        for c in COLOR_LETTERS],
    'stangg': [Spell(CreateTokenCreature('stangg-twin')), Static(StanggOnLeave())],
    'stasis': [Triggered(PayManaOrSacAtUpkeep('U')), Static(SkipUntapPhase())],
    'steal-artifact': [Triggered(ReturnToOwnerOnLTB()), Spell(Steal(), T_FUNCS['opp_artifacts'])],
    'stone-calendar': [Static(StoneCalendar())],
    'stone-giant': [Activated('T', StoneGiant(), T_FUNCS['stone_giant'])],
    'stone-rain': [Spell(Destroy(), T_FUNCS['lands'])],
    'storm-seeker': [Spell(StormSeeker(), T_FUNCS['all_players'])],
    'storm-world': [Triggered(StormWorld())],
    'stream-of-life': [Spell(StreamOfLife(), T_FUNCS['all_players'], max_x_func=max_x_from_printed_card)],
    'strip-mine': [Activated('T', AddMana('C'), T_FUNCS['owner']),
                   Activated('T', Destroy(), T_FUNCS['lands'], extra_costs=[SacSelfCost()])],
    'su-chi': [Triggered(SuChi())],
    'subdue': [Spell(Subdue(), T_FUNCS['creatures'])],
    'sunastian-falconer': [Activated('T', AddMana('C', 2))],
    'sunken-city': [Static(PumpApplies(T_FUNCS['blue_creatures'], (1, 1))), Triggered(PayManaOrSacAtUpkeep('UU'))],
    'swords-to-plowshares': [Spell(SwordsToPlowshares(), T_FUNCS['creatures'])],
    'sylvan-paradise': [Spell(SetColor('G', 'EOT'), TargetSpec(T_FUNCS['creatures'], 1, None))],
    'syphon-soul': [Spell(SyphonSoul(), T_FUNCS['opp'])],
    'tablet-of-epityr': [Triggered(TabletOfEpityr())],
    'taiga': dual_land_specs('RG'),
    'tangle-kelp': [Spell(TangleKelp(), T_FUNCS['creatures'])],
    'tawnoss-coffin': [Triggered(OptionalUntap()), Triggered(TawnossCoffinUntap()),
                       Triggered(TawnossCoffinZoneChange())],  # TODO: code the actual exiling part
    'tawnoss-wand': [Activated('2T', UnblockableEOT(), T_FUNCS['creatures_power_two_or_less'])],
    'tawnoss-weaponry': [Triggered(OptionalUntap()),
                         Activated('2T', Pump(1, 1, True), T_FUNCS['creatures']),
                         (Triggered(UntapRemovesPumpFromAnotherCard(), None, UntapCardEffect))],
    'telekinesis': [Spell(Telekinesis(), T_FUNCS['creatures'])],
    'teleport': [Spell(UnblockableEOT(), T_FUNCS['creatures'], allowed_phases=[Phase.DECLARE_COMBAT])],
    'terror': [Spell(Destroy(allow_regen=False), T_FUNCS['non_artifact_non_black_creatures'])],
    'tetravus': [Spell(AddCounter(PLUS_ONE, 3), T_FUNCS['self'])],
    'tetsuo-umezawa': [Activated('UBBRT', Destroy(), T_FUNCS['tapped_or_blocking_creatures']),
                       Static(CantBeTargetedByAuras())],
    'the-abyss': [Triggered(TheAbyss())],
    'the-brute': [Activated('RRR', Regenerate(), T_FUNCS['host']), Spell(Pump(1, 0), T_FUNCS['creatures'])],
    'the-fallen': [Static(TheFallen())],
    'the-hive': [Activated('5T', CreateTokenCreature('wasp'))],
    'the-rack': [Static(TheRack())],
    'the-tabernacle-at-pendrell-vale': [Triggered(TheTabernacleAtPendrellVale())],
    'the-wretched': [Triggered(TheWretchedSteal()), Triggered(TheWretchedUnsteal())],
    'thicket-basilisk': [Triggered(DestroyCombatantAtCombatEnd(T_FUNCS['self'], T_FUNCS['non_wall_creatures']))],
    'thoughtlace': [Spell(SetColor('U'), T_FUNCS['cards'])],
    'throne-of-bone': [Static(OnColorSpellPayOneColorlessForOneLifeChoice('B'))],
    'time-elemental': [Triggered(TimeElementalAttackedOrBlocked()),
                       Activated('2UUT', TimeElementalBounce(), T_FUNCS['unenchanted_perms'])],
    'time-vault': [Triggered(DoesntUntapAtUntap(T_FUNCS['self'])), Triggered(TimeVaultOption()),
                   Activated('T', TakeAnotherTurn()), Spell(TapCardEffect(), T_FUNCS['self'])],
    'time-walk': [Spell(TakeAnotherTurn())],
    'timetwister': [Spell(Timetwister())],
    'tivadars-crusade': [Spell(DestroyAll(T_FUNCS['goblins']))],
    'tor-wauki': [Activated('T', DealDamage(2), T_FUNCS['combatants'])],
    'tormods-crypt': [Activated('T', GraveyardToExileInItsEntirety(), T_FUNCS['all_players'],
                                extra_costs=[SacSelfCost()])],
    'touch-of-darkness': [Spell(SetColor('B', 'EOT'), TargetSpec(T_FUNCS['creatures'], 1, None))],
    'tower-of-coireall': [Activated('T', TowerOfCoireall(), T_FUNCS['creatures'])],
    'tracker': [Activated('GGT', Tracker(), T_FUNCS['creatures'])],
    'tranquility': [Spell(DestroyAll(T_FUNCS['enchants']))],
    'transmutation': [Spell(Transmutation(), T_FUNCS['creatures'])],
    'triassic-egg': [Activated('3T', AddCounter(HATCHLING)),
                     Activated('', TriassicEggA(), extra_costs=[SacSelfCost()],
                               text='Sac to move a creature card from your hand to the battlefield'),
                     Activated('', TriassicEggB(), extra_costs=[SacSelfCost()],
                               text='Sac to reanimate a creature card from your graveyard')],
    'triskelion': [Activated('', DealDamage(1), T_FUNCS['all_creatures_and_players'],
                             extra_costs=[RemoveCounterCost(PLUS_ONE)]),
                   Spell(AddCounter(PLUS_ONE, 3), T_FUNCS['self'])],
    'tropical-island': dual_land_specs('GU'),
    'tsunami': [Spell(DestroyAll(T_FUNCS['islands']))],
    'tuknir-deathlock': [Activated('RGT', Pump(2, 2, True), T_FUNCS['creatures'])],
    'tundra': dual_land_specs('WU'),
    'tunnel': [Spell(Destroy(False), T_FUNCS['walls'])],
    'twiddle': [Spell(Twiddle(), T_FUNCS['artifacts_creatures_lands'])],
    'typhoon': [Spell(Typhoon(), T_FUNCS['opp'])],
    'uncle-istvan': [Static(PreventAllDamage(T_FUNCS['self'], T_FUNCS['creatures']))],
    'undertow': [Static(WalkRuleRemoved('Islandwalk'))],
    'underground-sea': dual_land_specs('BU'),
    'unholy-strength': [Spell(Pump(2, 1), T_FUNCS['creatures'])],
    'unstable-mutation': [Static(AddCounterAtTargetUpkeep(T_FUNCS['host'], MINUS_ONE)),
                          Spell(Pump(3, 3), T_FUNCS['creatures'])],
    'unsummon': [Spell(Bounce(), T_FUNCS['creatures'])],
    'ur-drago': [Static(WalkRuleRemoved('Swampwalk'))],
    'urborg': [Activated('T', AddMana('B')),
               Activated('T', UrborgLoseFirstStrike(), T_FUNCS['creatures_with_first_strike']),
               Activated('T', UrborgLoseSwampwalk(), T_FUNCS['creatures_with_swampwalk'])],
    'untamed-wilds': [Spell(UntamedWilds())],
    'urzas-avenger': [Activated('', UrzasAvengerFlying()), Activated('', UrzasAvengerFirstStrike()),
                      Activated('', UrzasAvengerTrample())],
    'urzas-chalice': [Static(OnColorSpellPayOneColorlessForOneLifeChoice('C'))],
    'urzas-mine': [Activated('T', UrzasTrio())],
    'urzas-miter': [Triggered(UrzasMiter())],
    'urzas-power-plant': [Activated('T', UrzasTrio())],
    'urzas-tower': [Activated('T', UrzasTrio())],
    'uthden-troll': [Activated('R', Regenerate(), T_FUNCS['self'])],
    'vaevictis-asmadi': [Triggered(PayManaOrSacAtUpkeep('BRG')),
                         self_pump('B', 1, 0),
                         self_pump('R', 1, 0),
                         self_pump('G', 1, 0)],
    'vampire-bats': [Activated('B', Pump(1, 0, True), T_FUNCS['self'], max_activations_per_turn=2)],
    'venarian-gold': [Triggered(RemoveCounterAtTargetUpkeep(T_FUNCS['host'], SLEEP)), Static(VenarianGoldAtUntap()),
                      Spell(VenarianGoldCast(), T_FUNCS['creatures'], max_x_func=max_x_from_printed_card)],
    'venom': [Spell(DestroyCombatantAtCombatEnd(T_FUNCS['host'], T_FUNCS['non_wall_creatures']), T_FUNCS['creatures'])],
    'verduran-enchantress': [Static(VerduranEnchantress())],
    'vesuvan-doppelganger': [Triggered(VesuvanDoppelgangerUpkeep()), Spell(VesuvanDoppelgangerCast())],
    # TODO: despite being the same code, VesuvanDoppelgangerUpkeep doesn't trigger;
    #  the card goes to the graveyard during cast as well but gets pulled out somehow;
    #  the SBA looking at 0 toughness may be the culprit
    'veteran-bodyguard': [Triggered(VeteranBodyguard())],
    'visions': [Spell(Visions(), T_FUNCS['all_players'])],
    'volcanic-island': dual_land_specs('RU'),
    'voodoo-doll': [Triggered(AddCounterAtTargetUpkeep(T_FUNCS['self'], PIN)), Triggered(VoodooDollEndStep()),
                    Activated('XXT', DealDamage(), T_FUNCS['all_creatures_and_players'],
                              min_x_func=voodoo_doll_x, max_x_func=voodoo_doll_x)],
    'walking-dead': [Activated('B', Regenerate(), T_FUNCS['self'])],
    'wall-of-bone': [Activated('B', Regenerate(), T_FUNCS['self'])],
    'wall-of-brambles': [Activated('G', Regenerate(), T_FUNCS['self'])],
    'wall-of-dust': [Triggered(WallOfDust())],
    'wall-of-opposition': [self_pump('1', 1, 0)],
    'wall-of-putrid-flesh': [Static(PreventAllDamage(T_FUNCS['self'], T_FUNCS['enchanted_creatures']))],
    'wall-of-tombstones': [Static(WallOfTombstonesPT())],
    'wall-of-vapor': [PreventCombatDamageFromItsAttackers()],
    'wall-of-water': [self_pump('U', 1, 0)],
    'wall-of-wonder': [Activated('2UU', WallOfWonder())],
    'wand-of-ith': [Activated('3T', WandOfIth(), allowed_p_turn_func=T_FUNCS['owner'])],
    'wanderlust': [Spell(DealDamageOnHostUpkeep(1), T_FUNCS['creatures'])],
    'warp-artifact': [Spell(DealDamageOnHostUpkeep(1), T_FUNCS['artifacts'])],
    'water-wurm': [Static(PumpApplies(T_FUNCS['self'], (0, 1), C_FUNCS['opp_has_island']))],
    'weakness': [Spell(Pump(-2, -1), T_FUNCS['creatures'])],
    'weakstone': [Static(PumpApplies(T_FUNCS['attackers'], (-1, 0)))],
    'web': [Spell(Web(), T_FUNCS['creatures'])],
    'wheel-of-fortune': [Spell(WheelOfFortune())],
    'whirling-dervish': [Triggered(WhirlingDervish())],
    'white-mana-battery': [MANA_BATTERY_ADD_CHARGE, mana_battery_add_mana('W')],
    'white-ward': [Spell(KWAModEffect('add', 'Protection From White'), T_FUNCS['creatures'])],
    'wild-growth': [Spell(WildGrowth(), T_FUNCS['lands'])],
    'will-o-the-wisp': [Activated('B', Regenerate(), T_FUNCS['self'])],
    'willow-satyr': [Activated('T', Steal(), T_FUNCS['opp_legendary_creatures']),
                     Static(OptionalUntap()), Static(ReturnToOwnerOnUntap())],
    'winds-of-change': [Spell(WindsOfChange())],
    'winter-blast': [Spell(WinterBlast(), TargetSpec(T_FUNCS['untapped_creatures'], 1, None),
                           max_x_func=max_x_from_printed_card)],
    'winter-orb': [Static(WinterOrb())],
    'witch-hunter': [Activated('T', DealDamage(1), T_FUNCS['all_players']),
                     Activated('1WWT', Bounce(), T_FUNCS['opp_creatures'])],
    'wood-elemental': [Spell(WoodElemental())],
    'wooden-sphere': [Static(OnColorSpellPayOneColorlessForOneLifeChoice('G'))],
    'word-of-binding': [Spell(TapCardsEffect(), TargetSpec(T_FUNCS['untapped_creatures'], 1, None),
                              max_x_func=max_x_from_printed_card)],
    'wormwood-treefolk': [Activated('GG', WormwoodTreefolkForestwalk()), Activated('BB', WormwoodTreefolkSwampwalk())],
    'wrath-of-god': [Spell(ExileAllCreatures())],
    'wyluli-wolf': [Activated('T', Pump(1, 1, True), T_FUNCS['creatures'])],
    'xira-arien': [Activated('BRGT', DrawCards(3), T_FUNCS['all_players'])],
    'yawgmoth-demon': [Static(YawgmothDemon())],
    'ydwen-efreet': [Static(YdwenEfreet())],
    'xenic-poltergeist': [Activated('T', BecomeCreaturePTEqualsManaValue(), T_FUNCS['non_creature_artifacts']),
                          Triggered(XenicPoltergeistRelease())],
    'zombie-master': [Static(KWAApplies(T_FUNCS['other_zombies'], 'add', 'Swampwalk'))],
    # TODO: giving other zombies an activated ability
}
