from __future__ import annotations

from models.cost import SacSelfCost, ExileSelfCost, RemoveCounterCost, SacCardCost, DiscardLastCardDrawnThisTurn, \
    ExileCardCost, DiscardACard
from models.game_card.counter_tokens import CARRION, PLUS_ONE
from models.effects.base import EffSpec, Activated, Triggered, Static, Spell, GenTrig
from models.target import TargetSpec
from models.effects.listeners_mod_queries import GaeasAvengerPT, GaeasLiegePT, IvoryGuardians, KormusBell, \
    LivingLands, LivingPlane, JihadPT, PumpApplies, SelfPTEqualsFuncLen, KWAApplies, BecomeBasicLand
from models.effects.listeners_permission import Moat, Meekstone, IronclawOrcs, LivonyaSilone, WalkRuleRemoved, \
    DoesntUntapAtUntap, GoblinRockSledUntap, UnblockableCondition, NoAttacksAllowedEOT, CantAttack, \
    PreventRegenerationEOT, CantBeTargetedByAuras, GoblinRockSledCanAttack, Lure, MarblePriestForcesBlock, \
    CantAttackIfAttackedLastTurn
from .event_conditions import EC
from ..constants import KW
from ..effects.modifiers_generic import PreventDamage, RedirectToSource
from ..effects.resolvers_f_to_o import FalseOrders, JovialEvil, Millstone, GlassesOfUrza, GwendlynDiCorci, JalumTome, \
    MindTwist, NaturalSelection, GreatDefender, HowlFromBeyond, LesserWerewolf, FallingStar, Feint, \
    FeldonsCane, GoblinKing, GlyphOfDestruction, HurkylsRecall, Inquisition, \
    KoboldDrillSergeant, KryShield, ManaClash, MartyrsCry, NamelessRace, ManaShort, \
    FireAndBrimstone, LibraryOfAlexandria, FellwarStone, NettlingImp, MoldDemon, ManaDrain, IfhBiffEfreet, \
    GlyphOfDelusion, GlyphOfReincarnation, GuardianAngel, Necropolis, LifeChisel
from models.effects.resolvers_generic import XZeroOneCountersByManaValue, DealDamage, \
    DealDamageToAllCreaturesAndPlayers, Destroy, DestroyAll, Regenerate, SacAll, DrawCards, \
    BecomeCreature, SetColor, AllWalksRemoved, KWAModEffect, GainLife, AddMana, Bounce, Reanimate, Steal, HandToBoard, \
    Pump, TapCardEffect, UntapCardEffect, DeclareAColor, CounterSpell, RevealTopLibraryCard, EmptyResolver, \
    CounterSpellUnlessManaPaid, RemoveFromCombat, BasePT, PumpSelf, AddCounter, DestroySelf, MayPayMana, \
    ExchangeLifeTotals, Do, GraveyardToExile, DealDamageToSourceOwner, PayManaOr, SacSelf, DealDamageToHostOwner, \
    DiscardAtRandom, DestroySelfCombatants, AddPoisonCounter, AddCounterPerCreatureDeath, DiscardHand, \
    DrawCardsActivePlayer
from models.systems.phase import Phase
from .card_filter_funcs import C_FUNCS, A_FUNCS, TF
from .effect_spec_templates import MANA_BATTERY_ADD_CHARGE, mana_battery_add_mana, mox_specs, self_pump, \
    max_x_from_printed_card, On
from ..effects.listeners_misc import IchneumonDruid, HauntingWindActivation, LeviathanAttack, InTheEyeOfChaos, \
    InvokePrejudice
from ..effects.listeners_state_change import JihadSac, OldManOfTheSeaPowerCheck, GlobalSac
from ..effects.listeners_zone_change import FieldOfDreams, GoblinShrineOnLeave, HazezonTamarLTB, Kismet, \
    LandEquilibrium
from ..effects.listeners_upkeep import Fasting, GabrielAngelfire, GhazbanOgre, \
    HazezonTamarTokenCreation, IvoryTower, Karma, LandTax, LordOfThePitUpkeep, ManaVortexUpkeep, GiantSlugUpkeep, \
    LeviathanUpkeep, Halfdane, LivingArtifactUpkeep
from ..effects.listeners_tap_untap import Kudzu, HauntingWindTap
from ..effects.listeners_end_step import InfiniteAuthorityEndStep
from ..effects.listeners_combat import MijaeDjinn, GiantShark, Johan, \
    InfiniteAuthorityCombatEnd, FloralSpuzzem, GlyphOfDoom
from ..effects.listeners_cost import Gloom, ManaMatrix
from ..effects.listeners_damage import GaseousForm, LivingArtifactOnDamage, ForethoughtAmulet, Forcefield, GlyphOfLife
from ..effects.listeners_dies import FirestormPhoenix
from ..effects.listeners_draw_discard import IslandSanctuary
from ..effects.listeners_generic import OptionalUntap, PreventAllDamageToEOT, PreventNextDamageTo, \
    PreventAllDamageByEOT, PreventNextDamageBy, PayManaToUntapUpkeep, RedirectNextDamageFromCardToOwnerEOT, PayManaOrCounterSpellListener
from ..events_all import DiesEvent, UnblockedAttackerEvent, DamageResolvedEvent, DrawCardEvent, CastResolvedEvent, \
    TapCardEvent, AttackEvent, UpkeepEvent, CombatEndEvent, DamageProposedEvent, EndStepEvent, DrawStepEvent

MAP: dict[str: list[EffSpec]] = {
    'fallen-angel': [Activated('', Pump(2, 1, True), TF.self(),
                     extra_costs=[SacCardCost(TF.your_other_creatures())])],
    'falling-star': [Spell(FallingStar(), TF.opp_creatures(), text='If a di roll is 1-5, deal 3 damage to it')],
    'false-orders': [Spell(FalseOrders(), TF.blockers(), allowed_phases=[Phase.DECLARE_BLOCKERS])],
    'farmstead': [Spell(EmptyResolver(), TF.lands()),
                  Activated('WW', GainLife(), TF.host_owner(), allowed_phases=[Phase.UPKEEP],
                            allowed_p_turn_func=TF.host_owner(), max_activations_per_turn=1)],
    'fasting': [Triggered(Fasting(), TF.self()),
                GenTrig(On(DrawCardEvent).where(EC.you_are_drawer()).then(DestroySelf()))],
    'fear': [Spell(UnblockableCondition(TF.host(), TF.non_artifact_non_black_creatures()), TF.creatures())],
    'feedback': [Spell(EmptyResolver(), TF.enchants()),
                 GenTrig(On(UpkeepEvent).where(EC.is_host_turn()).then(DealDamageToHostOwner()))],
    'feint': [Spell(Feint(), TF.attackers())],
    'feldons-cane': [Activated('T', FeldonsCane(), None, extra_costs=[ExileSelfCost()])],
    'fellwar-stone': [Activated('T', FellwarStone(), is_mana_ability=True)],
    'festival': [Spell(NoAttacksAllowedEOT(), None, allowed_phases=[Phase.UPKEEP], allowed_p_turn_func=TF.opp())],
    'field-of-dreams': [Static(FieldOfDreams()), Spell(RevealTopLibraryCard())],
    'fire-and-brimstone': [Spell(FireAndBrimstone(),)],
    'fire-drake': [Activated('R', Pump(1, 0, True), TF.self(), max_activations_per_turn=1)],
    'fire-sprites': [Activated('GT', AddMana('R'), TF.owner(), is_mana_ability=True)],
    'firebreathing': [Spell(EmptyResolver(), TF.creatures()), self_pump('R', 1, 0)],
    'firestorm-phoenix': [Triggered(FirestormPhoenix())],
    'fishliver-oil': [Spell(KWAModEffect('add', KW.ISLANDWALK), TF.creatures())],
    'fissure': [Spell(Destroy(False), TF.creatures_and_lands())],
    'flash-counter': [Spell(CounterSpell(), TF.instant_spells())],
    'flash-flood': [Spell(Destroy(), TF.red_permanents()), Spell(Bounce(), TF.mountains())],
    'flashfires': [Spell(DestroyAll(TF.plains()))],
    'flight': [Spell(KWAModEffect('add', KW.FLYING), TF.creatures())],
    'flood': [Activated('UU', TapCardEffect(), TF.untapped_creatures_without_flying())],
    'floral-spuzzem': [Triggered(FloralSpuzzem())],
    'flying-carpet': [Activated('2T', KWAModEffect('add', KW.FLYING, True), TF.creatures())],
    'fog': [GenTrig(On(DamageProposedEvent, expires='EOT').where(EC.is_combat_damage()).modify(PreventDamage()))],
    'force-of-nature': [GenTrig(On(UpkeepEvent).where(EC.is_your_turn()).
                                then(PayManaOr('GGGG', DealDamageToSourceOwner(8))))],
    'force-spike': [Spell(CounterSpellUnlessManaPaid('1'), TF.spells())],
    'forcefield': [Activated('1', Forcefield(), TF.unblocked_attackers())],
    'forethought-amulet': [GenTrig(On(UpkeepEvent).where(EC.is_your_turn()).then(PayManaOr('3', SacSelf()))),
                           Static(ForethoughtAmulet())],
    'fountain-of-youth': [Activated('2T', GainLife(), TF.owner())],
    'frozen-shade': [self_pump('B', 1, 1)],
    'fungusaur': [GenTrig(On(DamageResolvedEvent).where(EC.self_is_damage_receiver()).then(AddCounter(PLUS_ONE)))],
    'gabriel-angelfire': [Triggered(GabrielAngelfire())],
    'gaeas-avenger': [Static(GaeasAvengerPT())],
    'gaeas-liege': [Static(GaeasLiegePT()), Activated('T', BecomeBasicLand('forest'), TF.lands())],
    'gaeas-touch': [Activated('', AddMana('G', 2), TF.owner(), is_mana_ability=True, extra_costs=[SacSelfCost()],
                              text='Exile for {GG}'),
                    Activated('', HandToBoard(), TF.forests_in_your_hand(), text='Play extra forest',
                              allowed_p_turn_func=TF.owner(), max_activations_per_turn=1)],
    'gaseous-form': [Spell(GaseousForm(), TF.creatures())],
    'gate-to-phyrexia': [Activated('', Destroy(), TF.artifacts(), extra_costs=[SacCardCost(TF.your_creatures())],
                                   allowed_phases=[Phase.UPKEEP], max_activations_per_turn=1,
                                   allowed_p_turn_func=TF.owner())],
    'ghazban-ogre': [Triggered(GhazbanOgre())],
    'ghost-ship': [Activated('UUU', Regenerate(), TF.self())],
    'ghosts-of-the-damned': [Activated('T', Pump(-1, 0, True), TF.creatures())],
    'giant-growth': [Spell(Pump(3, 3, True), TF.creatures())],
    'giant-shark': [Triggered(GiantShark())],
    'giant-slug': [Activated('5', GiantSlugUpkeep())],
    'giant-strength': [Spell(Pump(2, 2), TF.creatures())],
    'giant-tortoise': [Static(PumpApplies(TF.self(), (0, 3), cond=C_FUNCS['self_is_untapped']))],
    'giant-turtle': [Triggered(CantAttackIfAttackedLastTurn())],
    'glasses-of-urza': [Activated('T', GlassesOfUrza())],
    'gloom': [Static(Gloom())],
    'glyph-of-delusion': [Spell(GlyphOfDelusion(), TF.walls())],
    'glyph-of-destruction': [Spell(GlyphOfDestruction(), TF.your_walls())],
    'glyph-of-doom': [Spell(GlyphOfDoom(), TF.walls())],
    'glyph-of-life': [Spell(GlyphOfLife(), TF.walls())],
    'glyph-of-reincarnation': [Spell(GlyphOfReincarnation(), TF.walls(),
                                     allowed_phases=[p for p in Phase if p >= Phase.COMBAT_END])],
    'goblin-balloon-brigade': [Activated('R', KWAModEffect('add', KW.FLYING, True), TF.self())],
    'goblin-caves': [Static(PumpApplies(TF.goblins(), (0, 2), cond=C_FUNCS['host_is_basic_mountain']))],
    'goblin-digging-team': [Activated('T', Destroy(), TF.walls(), extra_costs=[SacSelfCost()])],
    'goblin-king': [Spell(GoblinKing())],
    'goblin-rock-sled': [Static(GoblinRockSledUntap()), Static(GoblinRockSledCanAttack())],
    'goblin-shrine': [Static(PumpApplies(TF.goblins(), (1, 0), cond=C_FUNCS['host_is_basic_mountain'])),
                      Triggered(GoblinShrineOnLeave())],
    'goblin-wizard': [Activated('T', HandToBoard(), TF.goblin_permanents_in_your_hand()),
                      Activated('T', KWAModEffect('add', KW.PROTECTION_FROM_WHITE, True), TF.goblins())],
    'goblins-of-the-flarg': [Static(GlobalSac(TF.self(), C_FUNCS['you_have_a_dwarf']))],
    'golgothian-sylex': [Activated('1T', SacAll(TF.golgothian_sylex()))],
    'gosta-dirk': [Static(WalkRuleRemoved(KW.ISLANDWALK))],
    'granite-gargoyle': [self_pump('R', 0, 1)],
    'grapeshot-catapult': [Activated('T', DealDamage(4), TF.fliers())],
    'grave-robbers': [Activated('BT', Do(GraveyardToExile(), GainLife(2)), TF.artifacts_in_graveyards())],
    'gravity-sphere': [Static(KWAApplies(TF.creatures(), 'remove', KW.FLYING))],
    'great-defender': [Spell(GreatDefender(), TF.creatures())],
    'great-wall': [Static(WalkRuleRemoved(KW.PLAINSWALK))],
    'greater-realm-of-preservation': [Activated('1W', PreventNextDamageTo(protected=TF.owner()), TF.black_and_red())],
    'greed': [Activated('B', Do(DrawCards(), DealDamageToSourceOwner(2)))],
    'green-mana-battery': [MANA_BATTERY_ADD_CHARGE, mana_battery_add_mana('G')],
    'green-ward': [Spell(KWAModEffect('add', KW.PROTECTION_FROM_GREEN), TF.creatures())],
    'guardian-angel': [Spell(GuardianAngel(), TF.all_creatures_and_players())],
    'guardian-beast': [Static(KWAApplies(TF.your_non_creature_artifacts(), 'add', KW.INDESTRUCTIBLE,
                                         C_FUNCS['self_is_untapped'])),
                       Static(CantBeTargetedByAuras(TF.your_non_creature_artifacts(),
                                                    condition_func=C_FUNCS['self_is_untapped']))],
    'gwendlyn-di-corci': [Activated('T', GwendlynDiCorci(), TF.all_players(), allowed_p_turn_func=TF.owner())],
    'halfdane': [Triggered(Halfdane())],
    'hammerheim': [Activated('T', AddMana('R'), TF.owner(), is_mana_ability=True),
                   Activated('T', AllWalksRemoved(), TF.creatures())],
    'hasran-ogress': [GenTrig(On(AttackEvent).where(EC.self_is_attacker()).
                              then(PayManaOr('2', DealDamageToSourceOwner(3))))],
    'haunting-wind': [Triggered(HauntingWindActivation()), Triggered(HauntingWindTap())],
    'hazezon-tamar': [Triggered(HazezonTamarTokenCreation(TF.owner())), Triggered(HazezonTamarLTB())],
    'healing-salve': [Spell(GainLife(3)), Spell(PreventNextDamageTo(3), TF.all_creatures_and_players())],
    'heavens-gate': [Spell(SetColor('W', 'EOT'), TargetSpec(TF.creatures(), 1, None))],
    'hell-swarm': [Spell(PumpApplies(TF.creatures(), (-1, 0), True))],
    'hells-caretaker': [Activated('T', Reanimate(), TF.creatures_in_your_graveyard(), allowed_phases=[Phase.UPKEEP],
                                  allowed_p_turn_func=TF.owner(), extra_costs=[SacCardCost(TF.your_creatures())])],
    'hidden-path': [Static(KWAApplies(TF.green_creatures(), 'add', KW.FORESTWALK))],
    'holy-armor': [Spell(Pump(0, 2), TF.creatures()),
                   Activated('W', Pump(0, 1, True), TF.host())],
    'holy-day': [GenTrig(On(DamageProposedEvent, expires='EOT').where(EC.is_combat_damage()).modify(PreventDamage()))],
    'holy-light': [Spell(PumpApplies(TF.non_white_creatures(), (-1, -1), True))],
    'holy-strength': [Spell(Pump(1, 2), TF.creatures())],
    'horn-of-deafening': [Activated('2T', PreventNextDamageTo(protected=TF.owner(), combat_only=True), TF.creatures())],
    'horror-of-horrors': [Activated('', Regenerate(), TF.black_creatures(),
                                    extra_costs=[SacCardCost(TF.your_swamps())])],
    'howl-from-beyond': [Spell(HowlFromBeyond(), TF.creatures())],
    'howling-mine': [GenTrig(On(DrawStepEvent).where(EC.self_is_untapped()).then(DrawCardsActivePlayer()))],
    'hurkyls-recall': [Spell(HurkylsRecall(), TF.all_players())],
    'hurr-jackal': [Activated('T', PreventRegenerationEOT(), TF.creatures())],
    'hyperion-blacksmith': [Activated('T', TapCardEffect(), TF.opp_untapped_artifacts()),
                            Activated('T', UntapCardEffect(), TF.opp_tapped_artifacts())],
    'hypnotic-specter': [GenTrig(On(DamageResolvedEvent).
                                 where(EC.self_is_damager(), EC.opp_is_damage_receiver()).then(DiscardAtRandom()))],
    'ichneumon-druid': [Triggered(IchneumonDruid())],
    'icy-manipulator': [Activated('1T', TapCardEffect(), TF.untapped_artifacts_creatures_lands())],
    'ice-storm': [Spell(Destroy(), TF.lands())],
    'ifh-biff-efreet': [Activated('G', IfhBiffEfreet(), allowed_activators=A_FUNCS['all_players'])],
    'immolation': [Spell(Pump(2, -2), TF.creatures())],
    'in-the-eye-of-chaos': [Static(InTheEyeOfChaos())],
    'indestructible-aura': [Spell(PreventAllDamageToEOT(), TF.creatures())],
    'infernal-medusa': [GenTrig(On(CombatEndEvent).where(EC.self_is_attacker()).
                                then(DestroySelfCombatants(filter_func=TF.non_wall_creatures()))),
                        GenTrig(On(CombatEndEvent).where(EC.self_is_blocker()).then(DestroySelfCombatants()))],
    'inferno': [Spell(DealDamageToAllCreaturesAndPlayers(6))],
    'infinite-authority': [Triggered(InfiniteAuthorityCombatEnd()), Triggered(InfiniteAuthorityEndStep())],
    'instill-energy': [Spell(KWAModEffect('add', KW.HASTE), TF.creatures()),
                       Activated('', UntapCardEffect(), TF.host(), allowed_p_turn_func=TF.host_owner(),
                                 max_activations_per_turn=1)],
    'invisibility': [Spell(UnblockableCondition(TF.host(), TF.non_wall_creatures()), TF.creatures())],
    'inquisition': [Spell(Inquisition(), TF.all_players())],
    'invoke-prejudice': [Static(InvokePrejudice())],
    'iron-star': [GenTrig(On(CastResolvedEvent).where(EC.card_is_color('R')).then(MayPayMana('1', GainLife(1))))],
    'ironclaw-orcs': [Static(IronclawOrcs())],
    'island-fish-jasconius': [Triggered(DoesntUntapAtUntap(TF.self())),
                              Triggered(PayManaToUntapUpkeep('UU', TF.self()))],
    'island-of-wak-wak': [Activated('T', BasePT(base_p=0, base_t=None, eot=True), TF.fliers())],
    'island-sanctuary': [Static(IslandSanctuary())],
    'ivory-cup': [GenTrig(On(CastResolvedEvent).where(EC.card_is_color('W')).then(MayPayMana('1', GainLife(1))))],
    'ivory-guardians': [Static(IvoryGuardians())],
    'ivory-tower': [Triggered(IvoryTower())],
    'jacques-le-vert': [Static(PumpApplies(TF.your_green_creatures(), (0, 2)))],
    'jade-monolith': [Activated('1', RedirectNextDamageFromCardToOwnerEOT(), TF.creatures())],
    'jade-statue': [Activated('2', BecomeCreature(3, 6, 'Golem', True), TF.self(), allowed_phases=[Phase.MAIN])],
    'jalum-tome': [Activated('2T', JalumTome(), text='Draw one card; discard one card')],
    'jandors-ring': [Activated('2T', DrawCards(), TF.owner(), extra_costs=[DiscardLastCardDrawnThisTurn()])],
    'jandors-saddlebags': [Activated('3T', UntapCardEffect(), TF.tapped_creatures())],
    'jayemdae-tome': [Activated('4T', DrawCards(), TF.owner())],
    'jihad': [Static(JihadPT()), Static(JihadSac()), Spell(DeclareAColor())],
    'johan': [Triggered(Johan())],
    'jovial-evil': [Spell(JovialEvil(), TF.opp())],
    'juggernaut': [Static(UnblockableCondition(TF.self(), TF.walls()))],
    'jump': [Spell(KWAModEffect('add', KW.FLYING, True), TF.creatures())],
    'junun-efreet': [GenTrig(On(UpkeepEvent).where(EC.is_your_turn()).then(PayManaOr('BB', SacSelf())))],
    'juzam-djinn': [GenTrig(On(UpkeepEvent).where(EC.is_your_turn()).then(DealDamageToSourceOwner()))],
    'karakas': [Activated('T', AddMana('W'), is_mana_ability=True), Activated('T', Bounce(), TF.legendary_creatures())],
    'karma': [Triggered(Karma())],
    'kei-takahashi': [Activated('T', PreventNextDamageBy(preventable_amt=2), TF.creatures())],
    'keldon-warlord': [Static(SelfPTEqualsFuncLen(TF.your_non_wall_creatures()))],
    'khabal-ghoul': [GenTrig(On(EndStepEvent).where(EC.any_creature_died_this_turn()).
                             then(AddCounterPerCreatureDeath(PLUS_ONE)))],
    'killer-bees': [self_pump('G', 1, 1)],
    'king-suleiman': [Activated('T', Destroy(), TF.djinns_and_efreets())],
    'kird-ape': [Static(PumpApplies(TF.self(), (1, 2), cond=C_FUNCS['you_have_a_forest']))],
    'kismet': [Static(Kismet())],
    'kobold-drill-sergeant': [Spell(KoboldDrillSergeant())],
    'kobold-overlord': [Static(KWAApplies(TF.your_other_kobolds(), 'add', KW.FIRST_STRIKE))],
    'kobold-taskmaster': [Static(PumpApplies(TF.your_other_kobolds(), (0, 1)))],
    'kormus-bell': [Static(KormusBell())],
    'kry-shield': [Activated('2T', KryShield(), TF.your_creatures())],
    'kudzu': [Spell(Kudzu(), TF.lands())],
    'lady-caleria': [Activated('T', DealDamage(3), TF.combatants())],
    'lady-evangela': [Activated('WBT', PreventAllDamageByEOT(combat_only=True), TF.creatures())],
    'lance': [Spell(KWAModEffect('add', KW.FIRST_STRIKE), TF.creatures())],
    'land-equilibrium': [Static(LandEquilibrium())],
    'land-tax': [Triggered(LandTax())],
    'lands-edge': [Activated('', DealDamage(2), TF.all_players(), allowed_activators=A_FUNCS['all_players'],
                             extra_costs=[DiscardACard(TF.cards_in_your_hand())])],
    'lesser-werewolf': [Activated('B', LesserWerewolf(), TF.combating_against(),
                                  allowed_phases=[Phase.DECLARE_BLOCKERS])],
    'leviathan': [Static(DoesntUntapAtUntap(TF.self())), Static(CantAttack(TF.self())),
                  Triggered(LeviathanUpkeep()), Triggered(LeviathanAttack()), Spell(TapCardEffect(), TF.self())],
    'ley-druid': [Activated('T', UntapCardEffect(), TF.tapped_lands())],
    'library-of-alexandria': [Activated('T', AddMana('C'), is_mana_ability=True),
                              Activated('T', LibraryOfAlexandria())],
    'life-chisel': [Spell(LifeChisel(), allowed_phases=[Phase.UPKEEP], allowed_p_turn_func=TF.owner(),
                          extra_costs=[SacCardCost(TF.your_artifacts())])],
    'lifeblood': [GenTrig(On(TapCardEvent).where(EC.card_is_mountain(), EC.card_is_opponents()).then(GainLife()))],
    'lifeforce': [Activated('GG', CounterSpell(), TF.black_spells())],
    'lifelace': [Spell(SetColor('G'), TF.cards())],
    'lifetap': [GenTrig(On(TapCardEvent).where(EC.card_is_forest(), EC.card_is_opponents()).then(GainLife()))],
    'lightning-bolt': [Spell(DealDamage(3), TF.all_creatures_and_players())],
    'living-armor': [Activated('T', XZeroOneCountersByManaValue(), TF.creatures(), extra_costs=[SacSelfCost()])],
    'living-artifact': [Spell(EmptyResolver(), TF.artifacts()), Triggered(LivingArtifactOnDamage()),
                        Triggered(LivingArtifactUpkeep())],
    'living-lands': [Static(LivingLands())],
    'living-plane': [Static(LivingPlane())],
    'living-wall': [Activated('1', Regenerate(), TF.self())],
    'livonya-silone': [Static(LivonyaSilone())],
    'llanowar-elves': [Activated('T', AddMana('G'), TF.owner(), is_mana_ability=True)],
    'lord-of-atlantis': [Static(PumpApplies(TF.other_merfolk(), (1, 1))),
                         Static(KWAApplies(TF.other_merfolk(), 'add', KW.ISLANDWALK))],
    'lord-of-the-pit': [Triggered(LordOfThePitUpkeep())],
    'lord-magnus': [Static(WalkRuleRemoved(KW.PLAINSWALK)), Static(WalkRuleRemoved(KW.FORESTWALK))],
    'lure': [Spell(Lure(), TF.creatures())],
    'magnetic-mountain': [Triggered(DoesntUntapAtUntap(TF.in_turn_player_tapped_blue_creatures())),
                          Triggered(PayManaToUntapUpkeep('4', TF.in_turn_player_tapped_blue_creatures()))],
    'mana-clash': [Spell(ManaClash())],
    'mana-drain': [Spell(ManaDrain(), TF.spells())],
    'mana-matrix': [Static(ManaMatrix())],
    'mana-short': [Spell(ManaShort(), TF.all_players())],
    'mana-vault': [Triggered(DoesntUntapAtUntap(TF.self())), Triggered(PayManaToUntapUpkeep('4', TF.self())),
                   Activated('T', AddMana('C', 3), TF.owner(), is_mana_ability=True),
                   GenTrig(On(DrawStepEvent).where(EC.is_your_turn(), EC.self_is_tapped()).
                           then(DealDamageToSourceOwner()))],
    'mana-vortex': [Spell(Destroy(), TF.your_lands()), Static(ManaVortexUpkeep()),
                    Static(GlobalSac(TF.self(), C_FUNCS['no_lands']))],
    'marble-priest': [GenTrig(On(DamageProposedEvent).
                              where(EC.damage_target_in(TF.self()), EC.damage_source_in(TF.walls()),
                                    EC.is_combat_damage()).modify(PreventDamage())),
                      Static(MarblePriestForcesBlock())],
    'marsh-gas': [Spell(PumpApplies(TF.creatures(), (-2, 0), True))],
    'marsh-viper': [GenTrig(On(DamageResolvedEvent).where(EC.source_damaged_opp()).then(AddPoisonCounter(2)))],
    'martyrs-cry': [Spell(MartyrsCry())],
    'martyrs-of-korlis': [GenTrig(On(DamageProposedEvent).
                                  where(EC.self_is_untapped(), EC.damage_source_in(TF.artifacts()),
                                        EC.damage_target_in(TF.owner())).modify(RedirectToSource()))],
    'maze-of-ith': [Activated('T', RemoveFromCombat(), TF.attackers())],
    'meekstone': [Static(Meekstone())],
    'merchant-ship': [GenTrig(On(UnblockedAttackerEvent).where(EC.self_is_unblocked_attacker()).then(GainLife(2)))],
    'merfolk-assassin': [Activated('T', Destroy(), TF.islandwalkers())],
    'mightstone': [Static(PumpApplies(TF.attackers(), (1, 0)))],
    'mijae-djinn': [Triggered(MijaeDjinn())],
    'millstone': [Activated('2T', Millstone(), TF.all_players())],
    'mind-twist': [Spell(MindTwist(), TF.all_players(), max_x_func=max_x_from_printed_card)],
    'miracle-worker': [Activated('T', Destroy(), TF.auras_on_owners_creatures())],
    'mirror-universe': [Activated('T', ExchangeLifeTotals(), allowed_phases=[Phase.UPKEEP],
                                  allowed_p_turn_func=TF.owner(), extra_costs=[SacSelfCost()])],
    'mishras-factory': [Activated('T', AddMana('C'), TF.owner(), is_mana_ability=True, text='Add {C}'),
                        Activated('1', BecomeCreature(2, 2, 'Assembly-Worker', True), TF.self(), text='Become 2/2'),
                        Activated('T', Pump(1, 1, True), TF.assembly_workers(), text='Pump Assembly-Worker')],
    'moat': [Static(Moat())],
    'mold-demon': [Spell(MoldDemon())],
    'morale': [Spell(PumpApplies(TF.attackers(), (1, 1), True))],
    'mox-emerald': mox_specs('G'),
    'mox-jet': mox_specs('B'),
    'mox-pearl': mox_specs('W'),
    'mox-ruby': mox_specs('R'),
    'mox-sapphire': mox_specs('U'),
    'murk-dwellers': [GenTrig(On(UnblockedAttackerEvent).where(EC.self_is_unblocked_attacker()).then(PumpSelf(2, 0, True)))],
    'nameless-race': [Spell(NamelessRace())],
    'natural-selection': [Spell(NaturalSelection(), TF.all_players())],
    'necropolis': [Activated('', Necropolis(), extra_costs=[ExileCardCost(TF.creatures_in_your_graveyard())])],
    'nether-void': [Triggered(PayManaOrCounterSpellListener('3'))],
    'nettling-imp': [Activated('T', NettlingImp(), TF.non_wall_creatures_wo_summoning_sickness())],
    'nevinyrrals-disk': [Spell(TapCardEffect(), TF.self()),
                         Activated('1T', DestroyAll(TF.artifacts_creatures_enchantments()))],
    'niall-silvain': [Activated('GGGGT', Regenerate(), TF.creatures())],
    'nicol-bolas': [GenTrig(On(UpkeepEvent).where(EC.is_your_turn()).then(PayManaOr('UBR', SacSelf()))),
                    GenTrig(On(DamageResolvedEvent).where(EC.damage_target_in(TF.opp()),
                                                          EC.damage_source_in(TF.self())).then(DiscardHand()))],
    'nightmare': [Static(SelfPTEqualsFuncLen(TF.your_swamps()))],
    'northern-paladin': [Activated('WW', Destroy(), TF.black_permanents())],
    'oasis': [Activated('T', PreventNextDamageBy(preventable_amt=1), TF.creatures())],
    'obelisk-of-undoing': [Activated('6T', Bounce(), TF.perms_you_own_and_control())],
    'old-man-of-the-sea': [Activated('T', Steal(return_on_untap=True),
                                     TF.opp_creatures_power_not_greater_than_source()),
                           Triggered(OptionalUntap()), Static(OldManOfTheSeaPowerCheck())],
    'onulet': [GenTrig(On(DiesEvent).where(EC.self_is_dier()).then(GainLife(2)))],
    'orc-general': [Activated('T', Pump(1, 1, True), TF.your_other_orcs(),
                              extra_costs=[SacCardCost(TF.another_orc_or_goblin())])],
    'orcish-artillery': [Activated('T', Do(DealDamage(2), DealDamageToSourceOwner(3)), TF.all_creatures_and_players())],
    'orcish-mechanics': [Activated('T', DealDamage(2), TF.all_creatures_and_players(),
                                   extra_costs=[SacCardCost(TF.your_artifacts())])],
    'orcish-oriflamme': [Static(PumpApplies(TF.your_attackers(), (1, 0)))],
    'osai-vultures': [GenTrig(On(EndStepEvent).where(EC.any_creature_died_this_turn()).then(AddCounter(CARRION))),
                      Activated('', Pump(1, 1, True),
                                extra_costs=[RemoveCounterCost(CARRION, 2)], text='Remove 2 counters for +1/+1')],
}
