from __future__ import annotations

from .effect_spec_templates import dual_land_specs, MANA_BATTERY_ADD_CHARGE, mana_battery_add_mana, self_pump, \
    voodoo_doll_x, max_x_from_printed_card, target_spell_mv, On
from .card_filter_funcs import C_FUNCS, CF
from models.constants import COLOR_LETTERS, KW, Zone
from models.cost import SacSelfCost, PayLifeCost, RemoveCounterCost, SacCardCost
from models.game_card.counter_tokens import PLUS_ONE, CORPSE, MINUS_ONE, PIN, DREAM, HATCHLING, MINUS_ZERO_TWO
from models.effects.base import EffSpec, Activated, Triggered, Static, Spell, GenTrig
from .event_conditions import EC
from .target_funcs import ET
from ..effects.listeners_misc import PowerleechActivation, VerduranEnchantress, ScarwoodBanditsAAListener
from ..effects.modifiers_generic import PreventDamage, RedirectToSource
from ..events_all import DiesEvent, EndStepEvent, CastResolvedEvent, TapCardEvent, UpkeepEvent, CombatEndEvent, \
    DamageProposedEvent, DamageResolvedEvent, DrawCardEvent, BlockEvent
from ..target import TargetSpec
from ..effects.resolvers_p_to_z import ReversePolarity, Simulacrum, Telekinesis, VesuvanDoppelgangerCast, RapidFire, \
    RockHydraCast, StormSeeker, Tracker, Typhoon, RagMan, Visions, WheelOfFortune, PhantasmalTerrain, PrimalClay, \
    UrborgLoseFirstStrike, UrborgLoseSwampwalk, UrzasTrio, TriassicEggA, SingingTree, Rakalite, RocketLauncher, \
    SacrificeOnCast, SafeHaven, ShapeshifterCast, Subdue, SwordsToPlowshares, Timetwister, WallOfWonder, \
    WandOfIth, WindsOfChange, WinterBlast, WoodElemental, PriestOfYawgmoth, Twiddle, Sindbad, SirensCall, \
    VenarianGold, TriassicEggB, Stangg, WarBarge, PowerSink, UrzasAvenger
from models.effects.resolvers_generic import AddCounter, DealDamage, Destroy, DestroyAll, AddPoisonCounter, \
    AddCounterPerCreatureDeath, Regenerate, DrawCards, SetColor, KWAModEffect, AddMana, Bounce, Reanimate, Steal, \
    GraveyardToExileInItsEntirety, Pump, CreateTokenCreature, TapCardEffect, TapCards, \
    DeclareAColor, CounterSpell, RevealHands, BecomeCreaturePTEqualsManaValue, BasePT, MayPayMana, \
    GainLife, Do, PayManaOr, SacSelf, EmptyResolver, AddCounterToHost, DestroySelfCombatants, DestroyHostCombatants, \
    UntapCards, Exile, Tutor, Register
from ..effects.listeners_state_change import GlobalSac
from ..effects.listeners_zone_change import Revelation, TawnossCoffinZoneChange
from ..effects.listeners_upkeep import PowerSurge, PsychicAllergyDamage, PsychicAllergySac, RasputinDreamweaverUpkeep, \
    RogahhOfKherKeepUpkeep, SafeHavenUpkeep, SeasonOfTheWitchUpkeep, SpiritualSanctuary, StormWorld, TheAbyss, \
    TheFallen, TheRack, TheTabernacleAtPendrellVale, VesuvanDoppelgangerUpkeep, XenicPoltergeistRelease, YawgmothDemon, \
    PowerLeak, SerendibDjinn, ShapeshifterUpkeep, WormsOfTheEarthUpkeep, PrimordialOoze, TetravusUpkeepCreate, \
    TetravusUpkeepExile
from ..effects.listeners_tap_untap import TawnossCoffinUntap, RasputinDreamweaverUntap, TimeVaultOption, PhyrexianGremlinsUntaps
from ..effects.listeners_end_step import SeasonOfTheWitchEndStep, VoodooDollEndStep
from ..effects.listeners_draw_discard import PsychicPurgeDiscard, SylvanLibrary
from ..effects.listeners_dies import PersonalIncarnationDies, SengirVampire, PuppetMaster, \
    SandalsOfAbdallahIfCreatureDies
from ..effects.listeners_damage import RockHydraAutoDamagePrevent, SpiritLink, ReverseDamage
from ..effects.listeners_cost import PlanarGate, PowerArtifact, StoneCalendar
from ..effects.listeners_combat import Sentinel, YdwenEfreet, TheWretched
from ..effects.listeners_generic import UntapRemovesPumpFromAnotherCard, PreventAllDamageToEOT, \
    OptionalUntap, RedirectNextDamageToTarget, PayManaToUntapUpkeep, \
    PreventNextDamageTo, PreventNextDamageBy, RedirectNextDamageFromCardToOwnerEOT, TakeAnotherTurn, \
    CounterEnchantments, DestroyAtEndStep
from models.effects.listeners_permission import CantBeTargetedByAuras, SpectralCloak, WalkRuleRemoved, Smoke, \
    WinterOrb, DoesntUntapAtUntap, SkipUntapPhase, UnblockableCondition, UnblockableEOT, CantCastAppliesTo, \
    CantAttackIfAttackedLastTurn, DoesntUntapAtUntapIfItAttackedLastTurn, TowerOfCoireallEOT
from models.effects.listeners_mod_queries import RabidWombat, WallOfTombstonesPT, PumpApplies, SelfPTEqualsFuncLen, \
    KWAApplies, Transmutation, SunglassesOfUrza
from models.systems.phase import Phase

MAP: dict[str, list[EffSpec]] = {
    'palladia-mors': [GenTrig(On(UpkeepEvent).where(EC.is_your_turn()).then(PayManaOr('RGW', SacSelf())))],
    'paralyze': [Triggered(DoesntUntapAtUntap(CF.host())), Static(PayManaToUntapUpkeep('4', CF.host())),
                 Spell(TapCardEffect(), CF.host())],
    'part-water': [Spell(KWAModEffect('add', KW.ISLANDWALK, True), CF.creatures(), max_x_func=max_x_from_printed_card)],
    'pavel-maliki': [self_pump('BR', 1, 0)],
    'pendelhaven': [Activated('T', AddMana('G'), CF.owner(), is_mana_ability=True),
                    Activated('T', Pump(1, 2, True), CF.one_one_creatures())],
    'people-of-the-woods': [Static(SelfPTEqualsFuncLen(CF.your_forests(), t_only=True))],
    'personal-incarnation': [Triggered(PersonalIncarnationDies()),
                             Activated('', RedirectNextDamageFromCardToOwnerEOT(CF.self(), 1))],
    'pestilence': [Activated('B', DealDamage(1, CF.all_creatures_and_players())),
                   GenTrig(On(EndStepEvent).where(EC.no_creatures_in_play()).then(Destroy(CF.self())))],
    'phantasmal-forces': [GenTrig(On(UpkeepEvent).where(EC.is_your_turn()).then(PayManaOr('U', SacSelf())))],
    'phantasmal-terrain': [Spell(PhantasmalTerrain(), CF.lands())],
    'phyrexian-gremlins': [Triggered(OptionalUntap()),
                           Activated('T', Do(TapCardEffect(), Register(DoesntUntapAtUntap, target_attr='target')),
                                     CF.artifacts()),
                           Triggered(PhyrexianGremlinsUntaps())],
    'piety': [Spell(PumpApplies(CF.blockers(), (0, 3), True))],
    'pirate-ship': [Activated('T', DealDamage(1), CF.all_creatures_and_players())],
    'pit-scorpion': [GenTrig(On(DamageResolvedEvent).where(EC.source_damaged_opp()).then(AddPoisonCounter()))],
    'pixie-queen': [Activated('GGGT', KWAModEffect('add', KW.FLYING), CF.creatures())],
    'plague-rats': [Static(SelfPTEqualsFuncLen(CF.plague_rats()))],
    'planar-gate': [Static(PlanarGate())],
    'plateau': dual_land_specs('RW'),
    'power-artifact': [Spell(PowerArtifact(), CF.artifacts())],
    'power-leak': [Static(PowerLeak())],
    'power-sink': [Spell(PowerSink(), CF.spells())],
    'power-surge': [Triggered(PowerSurge())],
    'powerleech': [Triggered(PowerleechActivation()),
                   GenTrig(On(TapCardEvent).where(EC.card_is_artifact(), EC.card_is_opponents()).then(GainLife()))],
    'pradesh-gypsies': [Activated('1GT', Pump(-2, 0, True), CF.creatures())],
    'preacher': [Activated('T', Steal(return_on_untap=True), CF.opp_creatures()), Triggered(OptionalUntap())],
    'presence-of-the-master': [Static(CounterEnchantments())],
    'priest-of-yawgmoth': [Activated('T', PriestOfYawgmoth(), extra_costs=[SacCardCost(CF.your_artifacts())])],
    'primal-clay': [Spell(PrimalClay())],
    'primordial-ooze': [Triggered(PrimordialOoze())],
    'princess-lucrezia': [Activated('T', AddMana('U'), is_mana_ability=True)],
    'prodigal-sorcerer': [Activated('T', DealDamage(1), CF.all_creatures_and_players(), text="Deal 1 Damage}")],
    'psionic-blast': [Spell(Do(DealDamage(4), DealDamage(2, CF.owner())), CF.all_creatures_and_players())],
    'psionic-entity': [Activated('T', Do(DealDamage(2), DealDamage(3, CF.owner())), CF.all_creatures_and_players())],
    'psychic-allergy': [Triggered(PsychicAllergySac()), Triggered(DeclareAColor()), Spell(PsychicAllergyDamage())],
    'psychic-purge': [Triggered(PsychicPurgeDiscard()), Spell(DealDamage(1), CF.all_creatures_and_players())],
    'psychic-venom': [Spell(EmptyResolver(), CF.lands()),
                      GenTrig(On(TapCardEvent).where(EC.card_is_host()).then(DealDamage(2)).t(ET.host_owner()))],
    'puppet-master': [Spell(PuppetMaster(), CF.creatures())],
    'purelace': [Spell(SetColor('W'), CF.cards())],
    'pyrotechnics': [Spell(DealDamage(1), TargetSpec(CF.all_creatures_and_players(), 1, 4,
                                                     allow_duplicate_targets=True))],
    'quagmire': [Static(WalkRuleRemoved(KW.SWAMPWALK))],
    'rabid-wombat': [Static(RabidWombat())],
    'radjan-spirit': [Activated('T', KWAModEffect('remove', KW.FLYING, True), CF.creatures())],
    'rag-man': [Activated('BBBT', RagMan(), CF.opp(), allowed_p_turn_func=CF.owner())],
    'ragnar': [Activated('GWUT', Regenerate(), CF.creatures())],
    'raise-dead': [Spell(Bounce(), CF.creatures_in_your_graveyard())],
    'rakalite': [Activated('2', Rakalite(), CF.all_creatures_and_players())],
    'ramses-overdark': [Activated('T', Destroy(), CF.enchanted_creatures())],
    'rapid-fire': [Spell(RapidFire(), CF.creatures(), allowed_phases=[p for p in Phase if p < Phase.DECLARE_BLOCKERS])],
    'rasputin-dreamweaver': [Activated('', AddMana('C'), is_mana_ability=True, extra_costs=[RemoveCounterCost(DREAM)]),
                             Activated('', PreventNextDamageTo(1), CF.self(), extra_costs=[RemoveCounterCost(DREAM)]),
                             Triggered(RasputinDreamweaverUntap()), Triggered(RasputinDreamweaverUpkeep()),
                             Spell(AddCounter(DREAM, 7))],
    'reconstruction': [Spell(Bounce(), CF.artifacts_in_your_graveyard())],
    'red-elemental-blast': [Spell(CounterSpell(), CF.blue_spells()), Spell(Destroy(), CF.blue_permanents())],
    'red-mana-battery': [MANA_BATTERY_ADD_CHARGE, mana_battery_add_mana('R')],
    'red-ward': [Spell(KWAModEffect('add', KW.PROTECTION_FROM_RED), CF.creatures())],
    'regeneration': [Activated('G', Regenerate(), CF.host())],
    'regrowth': [Spell(Bounce(), CF.cards_in_your_graveyard())],
    'relic-barrier': [Activated('T', TapCardEffect(), CF.untapped_artifacts())],
    'remove-soul': [Spell(CounterSpell(), CF.creature_spells())],
    'reset': [Spell(UntapCards(CF.your_tapped_lands()),
                    allowed_p_turn_func=CF.opp(), allowed_phases=[p for p in Phase if p >= Phase.UPKEEP])],
    'resurrection': [Spell(Reanimate(), CF.creatures_in_your_graveyard())],
    'revelation': [Static(Revelation()), Spell(RevealHands())],
    'reverse-damage': [Spell(ReverseDamage(), CF.cards())],
    'reverse-polarity': [Spell(ReversePolarity())],
    'ring-of-immortals': [Activated('3T', CounterSpell(), CF.spells_aura_or_instant_targeting_your_perm())],
    'righteousness': [Spell(Pump(7, 7, True), CF.blockers())],
    'riptide': [Spell(TapCards(CF.blue_creatures()))],
    'riven-turnbull': [Activated('T', AddMana('B'), is_mana_ability=True)],
    'rock-hydra': [Static(RockHydraAutoDamagePrevent()),
                   Activated('R', PreventNextDamageTo(1), CF.self()), Activated('RRR', AddCounter(PLUS_ONE)),
                   Spell(RockHydraCast(), CF.self(), max_x_func=max_x_from_printed_card)],
    'rocket-launcher': [Activated('2', RocketLauncher(), CF.all_creatures_and_players())],
    'rod-of-ruin': [Activated('3T', DealDamage(1), CF.all_creatures_and_players())],
    'rohgahh-of-kher-keep': [Static(PumpApplies(CF.your_kobolds_of_kher_keep(), (2, 2))),
                             Triggered(RogahhOfKherKeepUpkeep())],
    'royal-assassin': [Activated('T', Destroy(), CF.tapped_creatures())],
    'rubinia-soulsinger': [Activated('T', Steal(return_on_untap=True), CF.opp_creatures()), Triggered(OptionalUntap())],
    'rukh-egg': [GenTrig(On(DiesEvent).where(EC.card_is_source()).then(CreateTokenCreature('rukh')))],
    'sacrifice': [Spell(SacrificeOnCast(), extra_costs=[SacCardCost(CF.your_creatures())])],
    'safe-haven': [Activated('2T', SafeHaven(), CF.your_creatures()), Triggered(SafeHavenUpkeep())],
    'sage-of-lat-nam': [Activated('T', DrawCards(), CF.owner(), extra_costs=[SacCardCost(CF.your_artifacts())])],
    'samite-healer': [Activated('T', PreventNextDamageBy(preventable_amt=1), CF.cards())],
    'sandals-of-abdallah': [Activated('2', Do(KWAModEffect('add', 'Islandwalk', True),
                                              Register(SandalsOfAbdallahIfCreatureDies, target_attr='target_creature')),
                                      CF.creatures())],
    'sandstorm': [Spell(DealDamage(1, CF.attackers()))],
    'savaen-elves': [Activated('GGT', Destroy(), CF.auras_on_lands())],
    'savannah': dual_land_specs('GW'),
    'scarecrow': [Activated('6T', On(DamageProposedEvent, 'EOT').
                            where(EC.damage_target_in(CF.owner()), EC.damage_source_in(CF.fliers())).
                            modify(PreventDamage()).build())],
    'scarwood-bandits': [Static(ScarwoodBanditsAAListener()), Activated('2GT', Steal(), CF.opp_artifacts())],
    'scarwood-hag': [Activated('GGGGT', KWAModEffect('add', KW.FORESTWALK, True), CF.creatures_wo_forestwalk()),
                     Activated('T', KWAModEffect('remove', KW.FORESTWALK, True), CF.forestwalkers())],
    'scavenger-folk': [Activated('GT', Destroy(), CF.artifacts(), extra_costs=[SacSelfCost()])],
    'scavenging-ghoul': [GenTrig(On(EndStepEvent).where(EC.any_creature_died_this_turn()).
                             then(AddCounterPerCreatureDeath(CORPSE))),
                         Activated('', Regenerate(), CF.self(), extra_costs=[RemoveCounterCost(CORPSE)])],
    'scrubland': dual_land_specs('BW'),
    'sea-kings-blessing': [Spell(SetColor('U', 'EOT'), TargetSpec(CF.creatures(), 1, None))],
    'season-of-the-witch': [Triggered(SeasonOfTheWitchUpkeep()), Triggered(SeasonOfTheWitchEndStep())],
    'sedge-troll': [Static(PumpApplies(CF.self(), (1, 2), cond=C_FUNCS['you_have_a_swamp'])),
                    Activated('B', Regenerate(), CF.self())],
    'seeker': [Static(UnblockableCondition(CF.host(), CF.non_artifact_non_white_creatures()))],
    'sengir-vampire': [Triggered(SengirVampire())],
    'sentinel': [Activated('', Sentinel())],
    'serendib-djinn': [Triggered(SerendibDjinn()), Static(GlobalSac(CF.self(), C_FUNCS['you_have_no_lands']))],
    'serendib-efreet': [GenTrig(On(UpkeepEvent).where(EC.is_your_turn()).then(DealDamage(1)).t(ET.s_owner()))],
    'serpent-generator': [Activated('4T', CreateTokenCreature('snake'))],
    'shapeshifter': [Spell(ShapeshifterCast()), Static(ShapeshifterUpkeep())],
    'shatter': [Spell(Destroy(), CF.artifacts())],
    'shatterstorm': [Spell(DestroyAll(CF.artifacts(), False))],
    'shield-wall': [Spell(PumpApplies(CF.your_creatures(), (0, 2), True))],
    'shimian-night-stalker': [Activated('BT', RedirectNextDamageToTarget(CF.owner(), CF.self()), CF.opp_attackers())],
    'shivan-dragon': [self_pump('R', 1, 0)],
    'silhouette': [Triggered(PreventAllDamageToEOT(combat_only=True), CF.creatures())],
    'simulacrum': [Spell(Simulacrum())],
    'sindbad': [Activated('T', Sindbad())],
    'singing-tree': [Activated('T', SingingTree(), CF.attackers())],
    'sinkhole': [Spell(Destroy(), CF.lands())],
    'sirens-call': [Spell(SirensCall(), allowed_p_turn_func=CF.opp(),
                          allowed_phases=[p for p in Phase if p < Phase.DECLARE_ATTACKERS])],
    'sisters-of-the-flame': [Activated('T', AddMana('R'), CF.owner(), is_mana_ability=True)],
    'skull-of-orm': [Activated('5T', Bounce(), CF.enchants_in_your_graveyard())],
    'smoke': [Triggered(Smoke())],
    'snake': [GenTrig(On(DamageResolvedEvent).where(EC.source_damaged_opp()).then(AddPoisonCounter()))],  # token
    'sol-ring': [Activated('T', AddMana('C', 2), CF.owner(), is_mana_ability=True)],
    'solkanar-the-swamp-king': [GenTrig(On(CastResolvedEvent).where(EC.card_is_color('B')).then(GainLife()))],
    'sorceress-queen': [Activated('T', BasePT(0, 2, True), CF.other_creatures())],
    'soul-net': [GenTrig(On(DiesEvent).where(EC.dier_is_creature()).then(MayPayMana('1', GainLife(1))))],
    'spectral-cloak': [Spell(SpectralCloak(), CF.creatures())],
    'spell-blast': [Spell(CounterSpell(), CF.spells(), min_x_func=target_spell_mv, max_x_func=target_spell_mv)],
    'spinal-villain': [Activated('T', Destroy(), CF.blue_creatures())],
    'spirit-link': [Spell(SpiritLink(), CF.creatures())],
    'spirit-shackle': [Spell(EmptyResolver(), CF.creatures()),
                       GenTrig(On(TapCardEvent).where(EC.card_is_host()).then(AddCounterToHost(MINUS_ZERO_TWO)))],
    'spiritual-sanctuary': [Triggered(SpiritualSanctuary())],
    'staff-of-zegon': [Activated('3T', Pump(-2, 0, True), CF.creatures())],
    'standing-stones': [Activated('1T', AddMana(c), is_mana_ability=True, text=f'Add {{{c}}}',
                                  extra_costs=[PayLifeCost()]) for c in COLOR_LETTERS],
    'stangg': [Spell(Stangg())],
    'stasis': [GenTrig(On(UpkeepEvent).where(EC.is_your_turn()).then(PayManaOr('U', SacSelf()))), Static(SkipUntapPhase())],
    'steal-artifact': [Spell(Steal(), CF.opp_artifacts())],
    'stone-calendar': [Static(StoneCalendar())],
    'stone-giant': [Activated('T', Do(KWAModEffect('add', 'Flying', True),
                                      Register(DestroyAtEndStep, target_attr='card_to_be_destroyed')),
                              CF.stone_giant())],
    'stone-rain': [Spell(Destroy(), CF.lands())],
    'storm-seeker': [Spell(StormSeeker(), CF.all_players())],
    'storm-world': [Triggered(StormWorld())],
    'stream-of-life': [Spell(GainLife(), CF.all_players(), max_x_func=max_x_from_printed_card)],
    'strip-mine': [Activated('T', AddMana('C'), CF.owner(), is_mana_ability=True),
                   Activated('T', Destroy(), CF.lands(), extra_costs=[SacSelfCost()])],
    'su-chi': [GenTrig(On(DiesEvent).where(EC.card_is_source()).then(AddMana('C', 4)))],
    'subdue': [Spell(Subdue(), CF.creatures())],
    'sunastian-falconer': [Activated('T', AddMana('C', 2), is_mana_ability=True)],
    'sunglasses-of-urza': [Static(SunglassesOfUrza())],
    'sunken-city': [Static(PumpApplies(CF.blue_creatures(), (1, 1))),
                    GenTrig(On(UpkeepEvent).where(EC.is_your_turn()).then(PayManaOr('UU', SacSelf())))],
    'swords-to-plowshares': [Spell(SwordsToPlowshares(), CF.creatures())],
    'sylvan-library': [Triggered(SylvanLibrary())],
    'sylvan-paradise': [Spell(SetColor('G', 'EOT'), TargetSpec(CF.creatures(), 1, None))],
    'syphon-soul': [Spell(Do(DealDamage(2, CF.opp()), GainLife(2, CF.owner())))],
    'tablet-of-epityr': [GenTrig(On(DiesEvent).where(EC.dier_is_your_artifact()).then(MayPayMana('1', GainLife(1))))],
    'taiga': dual_land_specs('RG'),
    'tangle-kelp': [Spell(Do(TapCardEffect(), Register(DoesntUntapAtUntapIfItAttackedLastTurn, target_attr='target')),
                          CF.creatures())],
    'tawnoss-coffin': [Triggered(OptionalUntap()), Triggered(TawnossCoffinUntap()),
                       Triggered(TawnossCoffinZoneChange())],
    'tawnoss-wand': [Activated('2T', UnblockableEOT(), CF.creatures_power_two_or_less())],
    'tawnoss-weaponry': [Triggered(OptionalUntap()), Triggered(UntapRemovesPumpFromAnotherCard()),
                         Activated('2T', Pump(1, 1, True), CF.creatures())],
    'telekinesis': [Spell(Telekinesis(), CF.creatures())],
    'teleport': [Spell(UnblockableEOT(), CF.creatures(), allowed_phases=[Phase.DECLARE_COMBAT])],
    'terror': [Spell(Destroy(allow_regen=False), CF.non_artifact_non_black_creatures())],
    'tetravite': [Static(CantBeTargetedByAuras(CF.self()))],  # token creature created by tetravus
    'tetravus': [Spell(AddCounter(PLUS_ONE, 3), CF.self()),
                 Triggered(TetravusUpkeepCreate()), Triggered(TetravusUpkeepExile())],
    'tetsuo-umezawa': [Activated('UBBRT', Destroy(), CF.tapped_or_blocking_creatures()),
                       Static(CantBeTargetedByAuras(CF.self()))],
    'the-abyss': [Triggered(TheAbyss())],
    'the-brute': [Activated('RRR', Regenerate(), CF.host()), Spell(Pump(1, 0), CF.creatures())],
    'the-fallen': [Static(TheFallen())],
    'the-hive': [Activated('5T', CreateTokenCreature('wasp'))],
    'the-rack': [Static(TheRack())],
    'the-tabernacle-at-pendrell-vale': [Static(TheTabernacleAtPendrellVale())],
    'the-wretched': [Triggered(TheWretched())],
    'thicket-basilisk': [GenTrig(On(CombatEndEvent).where(EC.self_is_combatant()).
                                 then(DestroySelfCombatants(filter_func=CF.non_wall_creatures())))],
    'thoughtlace': [Spell(SetColor('U'), CF.cards())],
    'throne-of-bone': [GenTrig(On(CastResolvedEvent).where(EC.card_is_color('B')).then(MayPayMana('1', GainLife(1))))],
    'time-elemental': [GenTrig(On(CombatEndEvent).where(EC.self_is_combatant()).
                               then(Do(SacSelf(), DealDamage(5, CF.owner())))),
                       Activated('2UUT', Bounce(), CF.unenchanted_perms())],
    'time-vault': [Triggered(DoesntUntapAtUntap(CF.self())), Triggered(TimeVaultOption()),
                   Activated('T', TakeAnotherTurn()), Spell(TapCardEffect(), CF.self())],
    'time-walk': [Spell(TakeAnotherTurn())],
    'timetwister': [Spell(Timetwister())],
    'tivadars-crusade': [Spell(DestroyAll(CF.goblins()))],
    'tor-wauki': [Activated('T', DealDamage(2), CF.combatants())],
    'tormods-crypt': [Activated('T', GraveyardToExileInItsEntirety(), CF.all_players(), extra_costs=[SacSelfCost()])],
    'touch-of-darkness': [Spell(SetColor('B', 'EOT'), TargetSpec(CF.creatures(), 1, None))],
    'tower-of-coireall': [Activated('T', Register(TowerOfCoireallEOT, target_attr='target'), CF.creatures())],
    'tracker': [Activated('GGT', Tracker(), CF.creatures())],
    'tranquility': [Spell(DestroyAll(CF.enchants()))],
    'transmutation': [Spell(Transmutation(), CF.creatures())],
    'triassic-egg': [Activated('3T', AddCounter(HATCHLING)),
                     Activated('', TriassicEggA(), extra_costs=[SacSelfCost()],
                               text='Sac to move a creature card from your hand to the battlefield'),
                     Activated('', TriassicEggB(), extra_costs=[SacSelfCost()],
                               text='Sac to reanimate a creature card from your graveyard')],
    'triskelion': [Activated('', DealDamage(1), CF.all_creatures_and_players(), extra_costs=[RemoveCounterCost(PLUS_ONE)]),
                   Spell(AddCounter(PLUS_ONE, 3), CF.self())],
    'tropical-island': dual_land_specs('GU'),
    'tsunami': [Spell(DestroyAll(CF.islands()))],
    'tuknir-deathlock': [Activated('RGT', Pump(2, 2, True), CF.creatures())],
    'tundra': dual_land_specs('WU'),
    'tunnel': [Spell(Destroy(allow_regen=False), CF.walls())],
    'twiddle': [Spell(Twiddle(), CF.artifacts_creatures_lands())],
    'typhoon': [Spell(Typhoon(), CF.opp())],
    'uncle-istvan': [GenTrig(On(DamageProposedEvent).
                             where(EC.damage_target_in(CF.self()), EC.damage_source_in(CF.creatures())).
                             modify(PreventDamage()))],
    'undertow': [Static(WalkRuleRemoved(KW.ISLANDWALK))],
    'underground-sea': dual_land_specs('BU'),
    'underworld-dreams': [GenTrig(On(DrawCardEvent).where(EC.opp_is_drawer()).then(DealDamage(1)).t(ET.opp()))],
    'unholy-strength': [Spell(Pump(2, 1), CF.creatures())],
    'unstable-mutation': [GenTrig(On(UpkeepEvent).where(EC.is_host_turn()).then(AddCounterToHost(MINUS_ONE))),
                          Spell(Pump(3, 3), CF.creatures())],
    'unsummon': [Spell(Bounce(), CF.creatures())],
    'ur-drago': [Static(WalkRuleRemoved(KW.SWAMPWALK))],
    'urborg': [Activated('T', AddMana('B'), is_mana_ability=True),
               Activated('T', UrborgLoseFirstStrike(), CF.creatures_with_first_strike()),
               Activated('T', UrborgLoseSwampwalk(), CF.creatures_with_swampwalk())],
    'untamed-wilds': [Spell(Tutor(CF.basic_lands_in_your_library(), Zone.BATTLEFIELD))],
    'urzas-avenger': [Activated('', UrzasAvenger())],
    'urzas-chalice': [GenTrig(On(CastResolvedEvent).where(EC.card_is_artifact()).then(MayPayMana('1', GainLife(1))))],
    'urzas-mine': [Activated('T', UrzasTrio())],
    'urzas-miter': [GenTrig(On(DiesEvent).where(EC.dier_is_your_artifact()).then(MayPayMana('3', DrawCards(1))))],
    'urzas-power-plant': [Activated('T', UrzasTrio())],
    'urzas-tower': [Activated('T', UrzasTrio())],
    'uthden-troll': [Activated('R', Regenerate(), CF.self())],
    'vaevictis-asmadi': [GenTrig(On(UpkeepEvent).where(EC.is_your_turn()).then(PayManaOr('BRG', SacSelf())))] + \
                        [self_pump(c, 1, 0) for c in 'BRG'],
    'vampire-bats': [Activated('B', Pump(1, 0, True), CF.self(), max_activations_per_turn=2)],
    'venarian-gold': [Spell(VenarianGold(), CF.creatures(), max_x_func=max_x_from_printed_card)],
    'venom': [Spell(EmptyResolver(), CF.creatures()),
              GenTrig(On(CombatEndEvent).where(EC.host_is_combatant()).
                      then(DestroyHostCombatants(filter_func=CF.non_wall_creatures())))],
    'verduran-enchantress': [Static(VerduranEnchantress())],
    'vesuvan-doppelganger': [Triggered(VesuvanDoppelgangerUpkeep()), Spell(VesuvanDoppelgangerCast())],
    # TODO: despite being the same code, VesuvanDoppelgangerUpkeep doesn't trigger;
    #  the card goes to the graveyard during cast as well but gets pulled out somehow;
    #  the SBA looking at 0 toughness may be the culprit
    'veteran-bodyguard': [GenTrig(On(DamageProposedEvent).
                                  where(EC.self_is_untapped(), EC.damage_source_in(CF.unblocked_attackers()),
                                        EC.damage_target_in(CF.owner())).modify(RedirectToSource()))],
    'visions': [Spell(Visions(), CF.all_players())],
    'volcanic-island': dual_land_specs('RU'),
    'voodoo-doll': [GenTrig(On(UpkeepEvent).where(EC.is_your_turn()).then(AddCounter(PIN))), Triggered(VoodooDollEndStep()),
                    Activated('XXT', DealDamage(), CF.all_creatures_and_players(),
                              min_x_func=voodoo_doll_x, max_x_func=voodoo_doll_x)],
    'walking-dead': [Activated('B', Regenerate(), CF.self())],
    'wall-of-bone': [Activated('B', Regenerate(), CF.self())],
    'wall-of-brambles': [Activated('G', Regenerate(), CF.self())],
    'wall-of-dust': [GenTrig(On(BlockEvent).where(EC.self_is_blocker()).
                             then(Register(CantAttackIfAttackedLastTurn, event_arg_func=ET.attacker())))],
    'wall-of-opposition': [self_pump('1', 1, 0)],
    'wall-of-putrid-flesh': [GenTrig(On(DamageProposedEvent).
                                     where(EC.damage_target_in(CF.self()),
                                           EC.damage_source_in(CF.enchanted_creatures())).modify(PreventDamage()))],
    'wall-of-tombstones': [Static(WallOfTombstonesPT())],
    'wall-of-vapor': [GenTrig(On(DamageProposedEvent).where(EC.is_combat_damage(), EC.self_is_a_blocker()).
                              modify(PreventDamage()))],
    'wall-of-water': [self_pump('U', 1, 0)],
    'wall-of-wonder': [Activated('2UU', WallOfWonder())],
    'wand-of-ith': [Activated('3T', WandOfIth(), allowed_p_turn_func=CF.owner())],
    'wanderlust': [Spell(EmptyResolver(), CF.creatures()),
                   GenTrig(On(UpkeepEvent).where(EC.is_host_turn()).then(DealDamage(1)).t(ET.host_owner()))],
    'war-barge': [Activated('3', WarBarge(), CF.creatures())],
    'warp-artifact': [Spell(EmptyResolver(), CF.artifacts()),
                      GenTrig(On(UpkeepEvent).where(EC.is_host_turn()).then(DealDamage(1)).t(ET.host_owner()))],
    'water-wurm': [Static(PumpApplies(CF.self(), (0, 1), cond=C_FUNCS['opp_has_island']))],
    'weakness': [Spell(Pump(-2, -1), CF.creatures())],
    'weakstone': [Static(PumpApplies(CF.attackers(), (-1, 0)))],
    'web': [Spell(Do(Pump(0, 2), KWAModEffect('add', 'Reach')), CF.creatures())],
    'wheel-of-fortune': [Spell(WheelOfFortune())],
    'whirling-dervish': [GenTrig(On(EndStepEvent).where(EC.source_damaged_opp()).then(AddCounter(PLUS_ONE)))],
    'white-mana-battery': [MANA_BATTERY_ADD_CHARGE, mana_battery_add_mana('W')],
    'white-ward': [Spell(KWAModEffect('add', KW.PROTECTION_FROM_WHITE), CF.creatures())],
    'wild-growth': [Spell(EmptyResolver(), CF.lands()),
                    GenTrig(On(TapCardEvent).where(EC.card_is_host()).then(AddMana('G')))],
    'will-o-the-wisp': [Activated('B', Regenerate(), CF.self())],
    'willow-satyr': [Activated('T', Steal(return_on_untap=True), CF.opp_legendary_creatures()), Static(OptionalUntap())],
    'winds-of-change': [Spell(WindsOfChange())],
    'winter-blast': [Spell(WinterBlast(), TargetSpec(CF.untapped_creatures(), 1, None),
                           max_x_func=max_x_from_printed_card)],
    'winter-orb': [Static(WinterOrb())],
    'witch-hunter': [Activated('T', DealDamage(1), CF.all_players()), Activated('1WWT', Bounce(), CF.opp_creatures())],
    'wood-elemental': [Spell(WoodElemental())],
    'wooden-sphere': [GenTrig(On(CastResolvedEvent).where(EC.card_is_color('G')).then(MayPayMana('1', GainLife(1))))],
    'word-of-binding': [Spell(TapCards(), TargetSpec(CF.untapped_creatures(), 1, None),
                              max_x_func=max_x_from_printed_card)],
    'worms-of-the-earth': [Static(CantCastAppliesTo(CF.all_lands_in_game())),
                           Static(GlobalSac(CF.all_lands_in_game())), Triggered(WormsOfTheEarthUpkeep())],
    'wormwood-treefolk': [Activated('GG', Do(KWAModEffect('add', 'Forestwalk', True), DealDamage(2, CF.owner()))),
                          Activated('BB', Do(KWAModEffect('add', 'Swampwalk', True), DealDamage(2, CF.owner())))],
    'wrath-of-god': [Spell(Exile(CF.creatures()))],
    'wyluli-wolf': [Activated('T', Pump(1, 1, True), CF.creatures())],
    'xira-arien': [Activated('BRGT', DrawCards(), CF.all_players())],
    'yawgmoth-demon': [Static(YawgmothDemon())],
    'ydwen-efreet': [Static(YdwenEfreet())],
    'xenic-poltergeist': [Activated('T', BecomeCreaturePTEqualsManaValue(), CF.non_creature_artifacts()),
                          Triggered(XenicPoltergeistRelease())],
    'zombie-master': [Static(KWAApplies(CF.other_zombies(), 'add', KW.SWAMPWALK))],
    # TODO: giving other zombies an activated ability
}
