from __future__ import annotations

from .effect_spec_templates import dual_land_specs, MANA_BATTERY_ADD_CHARGE, mana_battery_add_mana, self_pump, \
    voodoo_doll_x, max_x_from_printed_card, target_spell_mv, On
from .card_filter_funcs import C_FUNCS, TF
from models.constants import COLOR_LETTERS, KW
from models.cost import SacSelfCost, PayLifeCost, RemoveCounterCost, SacCardCost
from models.game_card.counter_tokens import PLUS_ONE, CORPSE, MINUS_ONE, PIN, DREAM, HATCHLING
from models.effects.base import EffSpec, Activated, Triggered, Static, Spell, GenTrig
from .event_conditions import SelfIsDier, NoCreaturesInPlay, SelfDamagedOpponent, DierIsYourArtifact, DierIsCreature, \
    CastCardIsArtifact, CastCardIsBlack, CastCardIsGreen, CardIsArtifact, CardIsOpponents, IsYourTurn, IsHostTurn, \
    SelfIsCombatant, HostIsCombatant, CardIsColor, IsBlocker, IsCombatDamage
from ..effects.listeners_misc import PowerleechActivation, VerduranEnchantress, ScarwoodBanditsAAListener
from ..events_all import DiesEvent, EndStepEvent, CastResolvedEvent, TapCardEvent, UpkeepEvent, CombatEndEvent, \
    DamageProposedEvent
from ..target import TargetSpec
from ..effects.resolvers_p_to_z import ReversePolarity, Simulacrum, TangleKelp, Telekinesis, TowerOfCoireall, \
    RockHydraCast, Sandstorm, StormSeeker, Tracker, Typhoon, RagMan, UntamedWilds, Visions, WheelOfFortune, \
    PhantasmalTerrain, PrimalClay, VesuvanDoppelgangerCast, RapidFire, SandalsOfAbdallahIslandWalk, \
    UrborgLoseFirstStrike, UrborgLoseSwampwalk, StreamOfLife, UrzasTrio, TriassicEggA, \
    SingingTree, Rakalite, RocketLauncher, \
    SacrificeOnCast, SafeHaven, ShapeshifterCast, StoneGiant, Subdue, SwordsToPlowshares, SyphonSoul, \
    Timetwister, UrzasAvengerFlying, UrzasAvengerFirstStrike, UrzasAvengerTrample, WallOfWonder, WandOfIth, \
    WindsOfChange, WinterBlast, WoodElemental, Reset, Riptide, PriestOfYawgmoth, \
    Twiddle, Sindbad, SirensCall, VenarianGold, TriassicEggB, Stangg, WarBarge, PhyrexianGremlinsTap, PowerSink
from models.effects.resolvers_generic import AddCounter, DealDamage, DealOneDamageToTargetList, \
    DealDamageToAllCreaturesAndPlayers, Destroy, DestroyAll, \
    ExileAllCreatures, Regenerate, DrawCards, SetColor, KWAModEffect, AddMana, Bounce, Reanimate, Steal, \
    GraveyardToExileInItsEntirety, Pump, CreateTokenCreature, TapCardEffect, TapCardsEffect, \
    DeclareAColor, CounterSpell, RevealHands, BecomeCreaturePTEqualsManaValue, BasePT, DestroySelf, MayPayMana, \
    GainLife, Do, DealDamageToSourceOwner, PayManaOr, SacSelf, EmptyResolver, DealDamageToHostOwner, AddCounterToHost, \
    DestroySelfCombatants, DestroyHostCombatants
from ..effects.listeners_state_change import GlobalSac
from ..effects.listeners_zone_change import Revelation, TawnossCoffinZoneChange
from ..effects.listeners_upkeep import PowerSurge, PsychicAllergyDamage, PsychicAllergySac, RasputinDreamweaverUpkeep, \
    RogahhOfKherKeepUpkeep, SafeHavenUpkeep, SeasonOfTheWitchUpkeep, SpiritualSanctuary, StormWorld, TheAbyss, \
    TheFallen, TheRack, TheTabernacleAtPendrellVale, VesuvanDoppelgangerUpkeep, XenicPoltergeistRelease, YawgmothDemon, \
    PowerLeak, SerendibDjinn, ShapeshifterUpkeep, WormsOfTheEarthUpkeep, PrimordialOoze, TetravusUpkeepCreate, \
    TetravusUpkeepExile
from ..effects.listeners_tap_untap import PsychicVenom, SpiritShackle, WildGrowth, TawnossCoffinUntap, \
    RasputinDreamweaverUntap, TimeVaultOption, PhyrexianGremlinsUntaps
from ..effects.listeners_end_step import SeasonOfTheWitchEndStep, VoodooDollEndStep
from ..effects.listeners_draw_discard import PsychicPurgeDiscard, SylvanLibrary
from ..effects.listeners_dies import PersonalIncarnationDies, SengirVampire, PuppetMaster
from ..effects.listeners_damage import RockHydraAutoDamagePrevent, VeteranBodyguard, SpiritLink, ReverseDamage
from ..effects.listeners_cost import PlanarGate, PowerArtifact, StoneCalendar
from ..effects.listeners_combat import Sentinel, WallOfDust, YdwenEfreet, TimeElementalAttackedOrBlocked, \
    TheWretched
from ..effects.listeners_generic import AddPoisonCounter, UntapRemovesPumpFromAnotherCard, PreventAllDamageToEOT, \
    OptionalUntap, PreventCombatDamageFromItsAttackers, RedirectNextDamageToTarget, \
    AddCounterPerCreatureDeathAtEndStep, PayManaToUntapUpkeep, PreventAllDamage, PreventAllDamageEOT, \
    PreventNextDamageTo, PreventNextDamageBy, RedirectNextDamageFromCardToOwnerEOT, TakeAnotherTurn, CounterEnchantments
from models.effects.listeners_permission import CantBeTargetedByAuras, SpectralCloak, WalkRuleRemoved, Smoke, \
    WinterOrb, DoesntUntapAtUntap, SkipUntapPhase, UnblockableCondition, UnblockableEOT, CantCastAppliesTo
from models.effects.listeners_mod_queries import RabidWombat, WallOfTombstonesPT, PumpApplies, SelfPTEqualsFuncLen, \
    KWAApplies, Transmutation, SunglassesOfUrza
from models.systems.phase import Phase

MAP: dict[str, list[EffSpec]] = {
    'palladia-mors': [GenTrig(On(UpkeepEvent).where(IsYourTurn()).then(PayManaOr('RGW', SacSelf())))],
    'paralyze': [Triggered(DoesntUntapAtUntap(TF.host())), Static(PayManaToUntapUpkeep('4', TF.host())),
                 Spell(TapCardEffect(), TF.host())],
    'part-water': [Spell(KWAModEffect('add', KW.ISLANDWALK, True), TF.creatures(), max_x_func=max_x_from_printed_card)],
    'pavel-maliki': [self_pump('BR', 1, 0)],
    'pendelhaven': [Activated('T', AddMana('G'), TF.owner(), is_mana_ability=True),
                    Activated('T', Pump(1, 2, True), TF.one_one_creatures())],
    'people-of-the-woods': [Static(SelfPTEqualsFuncLen(TF.your_forests(), t_only=True))],
    'personal-incarnation': [Triggered(PersonalIncarnationDies()),
                             Activated('', RedirectNextDamageFromCardToOwnerEOT(TF.self(), 1))],
    'pestilence': [Activated('B', DealDamageToAllCreaturesAndPlayers(1)),
                   GenTrig(On(EndStepEvent).where(NoCreaturesInPlay()).then(DestroySelf()))],
    'phantasmal-forces': [GenTrig(On(UpkeepEvent).where(IsYourTurn()).then(PayManaOr('U', SacSelf())))],
    'phantasmal-terrain': [Spell(PhantasmalTerrain(), TF.lands())],
    'phyrexian-gremlins': [Triggered(OptionalUntap()), Activated('T', PhyrexianGremlinsTap(), TF.artifacts()),
                           Triggered(PhyrexianGremlinsUntaps())],
    'piety': [Spell(PumpApplies(TF.blockers(), (0, 3), True))],
    'pirate-ship': [Activated('T', DealDamage(1), TF.all_creatures_and_players())],
    'pit-scorpion': [Triggered(AddPoisonCounter())],
    'pixie-queen': [Activated('GGGT', KWAModEffect('add', KW.FLYING), TF.creatures())],
    'plague-rats': [Static(SelfPTEqualsFuncLen(TF.plague_rats()))],
    'planar-gate': [Static(PlanarGate())],
    'plateau': dual_land_specs('RW'),
    'power-artifact': [Spell(PowerArtifact(), TF.artifacts())],
    'power-leak': [Static(PowerLeak())],
    'power-sink': [Spell(PowerSink(), TF.spells())],
    'power-surge': [Triggered(PowerSurge())],
    'powerleech': [Triggered(PowerleechActivation()),
                   GenTrig(On(TapCardEvent).where(CardIsArtifact(), CardIsOpponents()).then(GainLife()))],
    'pradesh-gypsies': [Activated('1GT', Pump(-2, 0, True), TF.creatures())],
    'preacher': [Activated('T', Steal(return_on_untap=True), TF.opp_creatures()), Triggered(OptionalUntap())],
    'presence-of-the-master': [Static(CounterEnchantments())],
    'priest-of-yawgmoth': [Activated('T', PriestOfYawgmoth(), extra_costs=[SacCardCost(TF.your_artifacts())])],
    'primal-clay': [Spell(PrimalClay())],
    'primordial-ooze': [Triggered(PrimordialOoze())],
    'princess-lucrezia': [Activated('T', AddMana('U'), is_mana_ability=True)],
    'prodigal-sorcerer': [Activated('T', DealDamage(1), TF.all_creatures_and_players(), text="Deal 1 Damage}")],
    'psionic-blast': [Spell(Do(DealDamage(4), DealDamageToSourceOwner(2)), TF.all_creatures_and_players())],
    'psionic-entity': [Activated('T', Do(DealDamage(2), DealDamageToSourceOwner(3)), TF.all_creatures_and_players())],
    'psychic-allergy': [Triggered(PsychicAllergySac()), Triggered(DeclareAColor()), Spell(PsychicAllergyDamage())],
    'psychic-purge': [Triggered(PsychicPurgeDiscard()), Spell(DealDamage(1), TF.all_creatures_and_players())],
    'psychic-venom': [Spell(PsychicVenom(), TF.lands())],
    'puppet-master': [Spell(PuppetMaster(), TF.creatures())],
    'purelace': [Spell(SetColor('W'), TF.cards())],
    'pyrotechnics': [Spell(DealOneDamageToTargetList(), TargetSpec(TF.all_creatures_and_players(), 1, 4,
                                                                   allow_duplicate_targets=True))],
    'quagmire': [Static(WalkRuleRemoved(KW.SWAMPWALK))],
    'rabid-wombat': [Static(RabidWombat())],
    'radjan-spirit': [Activated('T', KWAModEffect('remove', KW.FLYING, True), TF.creatures())],
    'rag-man': [Activated('BBBT', RagMan(), TF.opp(), allowed_p_turn_func=TF.owner())],
    'ragnar': [Activated('GWUT', Regenerate(), TF.creatures())],
    'raise-dead': [Spell(Bounce(), TF.creatures_in_your_graveyard())],
    'rakalite': [Activated('2', Rakalite(), TF.all_creatures_and_players())],
    'ramses-overdark': [Activated('T', Destroy(), TF.enchanted_creatures())],
    'rapid-fire': [Spell(RapidFire(), TF.creatures(), allowed_phases=[p for p in Phase if p < Phase.DECLARE_BLOCKERS])],
    'rasputin-dreamweaver': [Activated('', AddMana('C'), is_mana_ability=True, extra_costs=[RemoveCounterCost(DREAM)]),
                             Activated('', PreventNextDamageTo(1), TF.self(), extra_costs=[RemoveCounterCost(DREAM)]),
                             Triggered(RasputinDreamweaverUntap()), Triggered(RasputinDreamweaverUpkeep()),
                             Spell(AddCounter(DREAM, 7))],
    'reconstruction': [Spell(Bounce(), TF.artifacts_in_your_graveyard())],
    'red-elemental-blast': [Spell(CounterSpell(), TF.blue_spells()), Spell(Destroy(), TF.blue_permanents())],
    'red-mana-battery': [MANA_BATTERY_ADD_CHARGE, mana_battery_add_mana('R')],
    'red-ward': [Spell(KWAModEffect('add', KW.PROTECTION_FROM_RED), TF.creatures())],
    'regeneration': [Activated('G', Regenerate(), TF.host())],
    'regrowth': [Spell(Bounce(), TF.cards_in_your_graveyard())],
    'relic-barrier': [Activated('T', TapCardEffect(), TF.untapped_artifacts())],
    'remove-soul': [Spell(CounterSpell(), TF.creature_spells())],
    'reset': [Spell(Reset(), allowed_p_turn_func=TF.opp(), allowed_phases=[p for p in Phase if p >= Phase.UPKEEP])],
    'resurrection': [Spell(Reanimate(), TF.creatures_in_your_graveyard())],
    'revelation': [Static(Revelation()), Spell(RevealHands())],
    'reverse-damage': [Spell(ReverseDamage(), TF.cards())],
    'reverse-polarity': [Spell(ReversePolarity())],
    'ring-of-immortals': [Activated('3T', CounterSpell(), TF.spells_aura_or_instant_targeting_your_perm())],
    'righteousness': [Spell(Pump(7, 7, True), TF.blockers())],
    'riptide': [Spell(Riptide())],
    'riven-turnbull': [Activated('T', AddMana('B'), is_mana_ability=True)],
    'rock-hydra': [Static(RockHydraAutoDamagePrevent()),
                   Activated('R', PreventNextDamageTo(1), TF.self()), Activated('RRR', AddCounter(PLUS_ONE)),
                   Spell(RockHydraCast(), TF.self(), max_x_func=max_x_from_printed_card)],
    'rocket-launcher': [Activated('2', RocketLauncher(), TF.all_creatures_and_players())],
    'rod-of-ruin': [Activated('3T', DealDamage(1), TF.all_creatures_and_players())],
    'rohgahh-of-kher-keep': [Static(PumpApplies(TF.your_kobolds_of_kher_keep(), (2, 2))),
                             Triggered(RogahhOfKherKeepUpkeep())],
    'royal-assassin': [Activated('T', Destroy(), TF.tapped_creatures())],
    'rubinia-soulsinger': [Activated('T', Steal(return_on_untap=True), TF.opp_creatures()), Triggered(OptionalUntap())],
    'rukh-egg': [GenTrig(On(DiesEvent).where(SelfIsDier()).then(CreateTokenCreature('rukh')))],
    'sacrifice': [Spell(SacrificeOnCast(), extra_costs=[SacCardCost(TF.your_creatures())])],
    'safe-haven': [Activated('2T', SafeHaven(), TF.your_creatures()), Triggered(SafeHavenUpkeep())],
    'sage-of-lat-nam': [Activated('T', DrawCards(), TF.owner(), extra_costs=[SacCardCost(TF.your_artifacts())])],
    'samite-healer': [Activated('T', PreventNextDamageBy(preventable_amt=1), TF.cards())],
    'sandals-of-abdallah': [Activated('2', SandalsOfAbdallahIslandWalk(), TF.creatures())],
    'sandstorm': [Spell(Sandstorm())],
    'savaen-elves': [Activated('GGT', Destroy(), TF.auras_on_lands())],
    'savannah': dual_land_specs('GW'),
    'scarecrow': [Activated('6T', PreventAllDamageEOT(TF.owner(), TF.fliers()))],
    'scarwood-bandits': [Static(ScarwoodBanditsAAListener()), Activated('2GT', Steal(), TF.opp_artifacts())],
    'scarwood-hag': [Activated('GGGGT', KWAModEffect('add', KW.FORESTWALK, True), TF.creatures_wo_forestwalk()),
                     Activated('T', KWAModEffect('remove', KW.FORESTWALK, True), TF.forestwalkers())],
    'scavenger-folk': [Activated('GT', Destroy(), TF.artifacts(), extra_costs=[SacSelfCost()])],
    'scavenging-ghoul': [Triggered(AddCounterPerCreatureDeathAtEndStep(CORPSE)),
                         Activated('', Regenerate(), TF.self(), extra_costs=[RemoveCounterCost(CORPSE)])],
    'scrubland': dual_land_specs('BW'),
    'sea-kings-blessing': [Spell(SetColor('U', 'EOT'), TargetSpec(TF.creatures(), 1, None))],
    'season-of-the-witch': [Triggered(SeasonOfTheWitchUpkeep()), Triggered(SeasonOfTheWitchEndStep())],
    'sedge-troll': [Static(PumpApplies(TF.self(), (1, 2), cond=C_FUNCS['you_have_a_swamp'])),
                    Activated('B', Regenerate(), TF.self())],
    'seeker': [Static(UnblockableCondition(TF.host(), TF.non_artifact_non_white_creatures()))],
    'sengir-vampire': [Triggered(SengirVampire())],
    'sentinel': [Activated('', Sentinel())],
    'serendib-djinn': [Triggered(SerendibDjinn()), Static(GlobalSac(TF.self(), C_FUNCS['you_have_no_lands']))],
    'serendib-efreet': [GenTrig(On(UpkeepEvent).where(IsYourTurn()).then(DealDamageToSourceOwner()))],
    'serpent-generator': [Activated('4T', CreateTokenCreature('snake'))],
    'shapeshifter': [Spell(ShapeshifterCast()), Static(ShapeshifterUpkeep())],
    'shatter': [Spell(Destroy(), TF.artifacts())],
    'shatterstorm': [Spell(DestroyAll(TF.artifacts(), False))],
    'shield-wall': [Spell(PumpApplies(TF.your_creatures(), (0, 2), True))],
    'shimian-night-stalker': [Activated('BT', RedirectNextDamageToTarget(TF.owner(), TF.self()), TF.opp_attackers())],
    'shivan-dragon': [self_pump('R', 1, 0)],
    'silhouette': [Triggered(PreventAllDamageToEOT(combat_only=True), TF.creatures())],
    'simulacrum': [Spell(Simulacrum())],
    'sindbad': [Activated('T', Sindbad())],
    'singing-tree': [Activated('T', SingingTree(), TF.attackers())],
    'sinkhole': [Spell(Destroy(), TF.lands())],
    'sirens-call': [Spell(SirensCall(), allowed_p_turn_func=TF.opp(),
                          allowed_phases=[p for p in Phase if p < Phase.DECLARE_ATTACKERS])],
    'sisters-of-the-flame': [Activated('T', AddMana('R'), TF.owner(), is_mana_ability=True)],
    'skull-of-orm': [Activated('5T', Bounce(), TF.enchants_in_your_graveyard())],
    'smoke': [Triggered(Smoke())],
    'snake': [Triggered(AddPoisonCounter())],  # token creature created by serpent-generator
    'sol-ring': [Activated('T', AddMana('C', 2), TF.owner(), is_mana_ability=True)],
    'solkanar-the-swamp-king': [GenTrig(On(CastResolvedEvent).where(CardIsColor('B')).then(GainLife()))],
    'sorceress-queen': [Activated('T', BasePT(0, 2, True), TF.other_creatures())],
    'soul-net': [GenTrig(On(DiesEvent).where(DierIsCreature()).then(MayPayMana('1', GainLife(1))))],
    'spectral-cloak': [Spell(SpectralCloak(), TF.creatures())],
    'spell-blast': [Spell(CounterSpell(), TF.spells(), min_x_func=target_spell_mv, max_x_func=target_spell_mv)],
    'spinal-villain': [Activated('T', Destroy(), TF.blue_creatures())],
    'spirit-link': [Spell(SpiritLink(), TF.creatures())],
    'spirit-shackle': [Spell(SpiritShackle(), TF.creatures())],
    'spiritual-sanctuary': [Triggered(SpiritualSanctuary())],
    'staff-of-zegon': [Activated('3T', Pump(-2, 0, True), TF.creatures())],
    'standing-stones': [Activated('1T', AddMana(c), is_mana_ability=True, text=f'Add {{{c}}}',
                                  extra_costs=[PayLifeCost()]) for c in COLOR_LETTERS],
    'stangg': [Spell(Stangg())],
    'stasis': [GenTrig(On(UpkeepEvent).where(IsYourTurn()).then(PayManaOr('U', SacSelf()))), Static(SkipUntapPhase())],
    'steal-artifact': [Spell(Steal(), TF.opp_artifacts())],
    'stone-calendar': [Static(StoneCalendar())],
    'stone-giant': [Activated('T', StoneGiant(), TF.stone_giant())],
    'stone-rain': [Spell(Destroy(), TF.lands())],
    'storm-seeker': [Spell(StormSeeker(), TF.all_players())],
    'storm-world': [Triggered(StormWorld())],
    'stream-of-life': [Spell(StreamOfLife(), TF.all_players(), max_x_func=max_x_from_printed_card)],
    'strip-mine': [Activated('T', AddMana('C'), TF.owner(), is_mana_ability=True),
                   Activated('T', Destroy(), TF.lands(), extra_costs=[SacSelfCost()])],
    'su-chi': [GenTrig(On(DiesEvent).where(SelfIsDier()).then(AddMana('C', 4)))],
    'subdue': [Spell(Subdue(), TF.creatures())],
    'sunastian-falconer': [Activated('T', AddMana('C', 2), is_mana_ability=True)],
    'sunglasses-of-urza': [Static(SunglassesOfUrza())],
    'sunken-city': [Static(PumpApplies(TF.blue_creatures(), (1, 1))),
                    GenTrig(On(UpkeepEvent).where(IsYourTurn()).then(PayManaOr('UU', SacSelf())))],
    'swords-to-plowshares': [Spell(SwordsToPlowshares(), TF.creatures())],
    'sylvan-library': [Triggered(SylvanLibrary())],
    'sylvan-paradise': [Spell(SetColor('G', 'EOT'), TargetSpec(TF.creatures(), 1, None))],
    'syphon-soul': [Spell(SyphonSoul(), TF.opp())],
    'tablet-of-epityr': [GenTrig(On(DiesEvent).where(DierIsYourArtifact()).then(MayPayMana('1', GainLife(1))))],
    'taiga': dual_land_specs('RG'),
    'tangle-kelp': [Spell(TangleKelp(), TF.creatures())],
    'tawnoss-coffin': [Triggered(OptionalUntap()), Triggered(TawnossCoffinUntap()),
                       Triggered(TawnossCoffinZoneChange())],
    'tawnoss-wand': [Activated('2T', UnblockableEOT(), TF.creatures_power_two_or_less())],
    'tawnoss-weaponry': [Triggered(OptionalUntap()), Triggered(UntapRemovesPumpFromAnotherCard()),
                         Activated('2T', Pump(1, 1, True), TF.creatures())],
    'telekinesis': [Spell(Telekinesis(), TF.creatures())],
    'teleport': [Spell(UnblockableEOT(), TF.creatures(), allowed_phases=[Phase.DECLARE_COMBAT])],
    'terror': [Spell(Destroy(allow_regen=False), TF.non_artifact_non_black_creatures())],
    'tetravite': [Static(CantBeTargetedByAuras(TF.self()))],  # token creature created by tetravus
    'tetravus': [Spell(AddCounter(PLUS_ONE, 3), TF.self()),
                 Triggered(TetravusUpkeepCreate()), Triggered(TetravusUpkeepExile())],
    'tetsuo-umezawa': [Activated('UBBRT', Destroy(), TF.tapped_or_blocking_creatures()),
                       Static(CantBeTargetedByAuras(TF.self()))],
    'the-abyss': [Triggered(TheAbyss())],
    'the-brute': [Activated('RRR', Regenerate(), TF.host()), Spell(Pump(1, 0), TF.creatures())],
    'the-fallen': [Static(TheFallen())],
    'the-hive': [Activated('5T', CreateTokenCreature('wasp'))],
    'the-rack': [Static(TheRack())],
    'the-tabernacle-at-pendrell-vale': [Static(TheTabernacleAtPendrellVale())],
    'the-wretched': [Triggered(TheWretched())],
    'thicket-basilisk': [GenTrig(On(CombatEndEvent).where(SelfIsCombatant()).
                                 then(DestroySelfCombatants(filter_func=TF.non_wall_creatures())))],
    'thoughtlace': [Spell(SetColor('U'), TF.cards())],
    'throne-of-bone': [GenTrig(On(CastResolvedEvent).where(CastCardIsBlack()).then(MayPayMana('1', GainLife(1))))],
    'time-elemental': [Triggered(TimeElementalAttackedOrBlocked()),
                       Activated('2UUT', Bounce(), TF.unenchanted_perms())],
    'time-vault': [Triggered(DoesntUntapAtUntap(TF.self())), Triggered(TimeVaultOption()),
                   Activated('T', TakeAnotherTurn()), Spell(TapCardEffect(), TF.self())],
    'time-walk': [Spell(TakeAnotherTurn())],
    'timetwister': [Spell(Timetwister())],
    'tivadars-crusade': [Spell(DestroyAll(TF.goblins()))],
    'tor-wauki': [Activated('T', DealDamage(2), TF.combatants())],
    'tormods-crypt': [Activated('T', GraveyardToExileInItsEntirety(), TF.all_players(), extra_costs=[SacSelfCost()])],
    'touch-of-darkness': [Spell(SetColor('B', 'EOT'), TargetSpec(TF.creatures(), 1, None))],
    'tower-of-coireall': [Activated('T', TowerOfCoireall(), TF.creatures())],
    'tracker': [Activated('GGT', Tracker(), TF.creatures())],
    'tranquility': [Spell(DestroyAll(TF.enchants()))],
    'transmutation': [Spell(Transmutation(), TF.creatures())],
    'triassic-egg': [Activated('3T', AddCounter(HATCHLING)),
                     Activated('', TriassicEggA(), extra_costs=[SacSelfCost()],
                               text='Sac to move a creature card from your hand to the battlefield'),
                     Activated('', TriassicEggB(), extra_costs=[SacSelfCost()],
                               text='Sac to reanimate a creature card from your graveyard')],
    'triskelion': [Activated('', DealDamage(1), TF.all_creatures_and_players(), extra_costs=[RemoveCounterCost(PLUS_ONE)]),
                   Spell(AddCounter(PLUS_ONE, 3), TF.self())],
    'tropical-island': dual_land_specs('GU'),
    'tsunami': [Spell(DestroyAll(TF.islands()))],
    'tuknir-deathlock': [Activated('RGT', Pump(2, 2, True), TF.creatures())],
    'tundra': dual_land_specs('WU'),
    'tunnel': [Spell(Destroy(False), TF.walls())],
    'twiddle': [Spell(Twiddle(), TF.artifacts_creatures_lands())],
    'typhoon': [Spell(Typhoon(), TF.opp())],
    'uncle-istvan': [Static(PreventAllDamage(TF.self(), TF.creatures()))],
    'undertow': [Static(WalkRuleRemoved(KW.ISLANDWALK))],
    'underground-sea': dual_land_specs('BU'),
    'unholy-strength': [Spell(Pump(2, 1), TF.creatures())],
    'unstable-mutation': [GenTrig(On(UpkeepEvent).where(IsHostTurn()).then(AddCounterToHost(MINUS_ONE))),
                          Spell(Pump(3, 3), TF.creatures())],
    'unsummon': [Spell(Bounce(), TF.creatures())],
    'ur-drago': [Static(WalkRuleRemoved(KW.SWAMPWALK))],
    'urborg': [Activated('T', AddMana('B'), is_mana_ability=True),
               Activated('T', UrborgLoseFirstStrike(), TF.creatures_with_first_strike()),
               Activated('T', UrborgLoseSwampwalk(), TF.creatures_with_swampwalk())],
    'untamed-wilds': [Spell(UntamedWilds())],
    'urzas-avenger': [Activated('', UrzasAvengerFlying()), Activated('', UrzasAvengerFirstStrike()),
                      Activated('', UrzasAvengerTrample())],
    'urzas-chalice': [GenTrig(On(CastResolvedEvent).where(CastCardIsArtifact()).then(MayPayMana('1', GainLife(1))))],
    'urzas-mine': [Activated('T', UrzasTrio())],
    'urzas-miter': [GenTrig(On(DiesEvent).where(DierIsYourArtifact()).then(MayPayMana('3', DrawCards(1))))],
    'urzas-power-plant': [Activated('T', UrzasTrio())],
    'urzas-tower': [Activated('T', UrzasTrio())],
    'uthden-troll': [Activated('R', Regenerate(), TF.self())],
    'vaevictis-asmadi': [GenTrig(On(UpkeepEvent).where(IsYourTurn()).then(PayManaOr('BRG', SacSelf())))] + \
                        [self_pump(c, 1, 0) for c in 'BRG'],
    'vampire-bats': [Activated('B', Pump(1, 0, True), TF.self(), max_activations_per_turn=2)],
    'venarian-gold': [Spell(VenarianGold(), TF.creatures(), max_x_func=max_x_from_printed_card)],
    'venom': [Spell(EmptyResolver(), TF.creatures()),
              GenTrig(On(CombatEndEvent).where(HostIsCombatant()).
                      then(DestroyHostCombatants(filter_func=TF.non_wall_creatures())))],
    'verduran-enchantress': [Static(VerduranEnchantress())],
    'vesuvan-doppelganger': [Triggered(VesuvanDoppelgangerUpkeep()), Spell(VesuvanDoppelgangerCast())],
    # TODO: despite being the same code, VesuvanDoppelgangerUpkeep doesn't trigger;
    #  the card goes to the graveyard during cast as well but gets pulled out somehow;
    #  the SBA looking at 0 toughness may be the culprit
    'veteran-bodyguard': [Triggered(VeteranBodyguard())],
    'visions': [Spell(Visions(), TF.all_players())],
    'volcanic-island': dual_land_specs('RU'),
    'voodoo-doll': [GenTrig(On(UpkeepEvent).where(IsYourTurn()).then(AddCounter(PIN))), Triggered(VoodooDollEndStep()),
                    Activated('XXT', DealDamage(), TF.all_creatures_and_players(),
                              min_x_func=voodoo_doll_x, max_x_func=voodoo_doll_x)],
    'walking-dead': [Activated('B', Regenerate(), TF.self())],
    'wall-of-bone': [Activated('B', Regenerate(), TF.self())],
    'wall-of-brambles': [Activated('G', Regenerate(), TF.self())],
    'wall-of-dust': [Triggered(WallOfDust())],
    'wall-of-opposition': [self_pump('1', 1, 0)],
    'wall-of-putrid-flesh': [Static(PreventAllDamage(TF.self(), TF.enchanted_creatures()))],
    'wall-of-tombstones': [Static(WallOfTombstonesPT())],
    'wall-of-vapor': [Triggered(PreventCombatDamageFromItsAttackers())],
    'wall-of-water': [self_pump('U', 1, 0)],
    'wall-of-wonder': [Activated('2UU', WallOfWonder())],
    'wand-of-ith': [Activated('3T', WandOfIth(), allowed_p_turn_func=TF.owner())],
    'wanderlust': [Spell(EmptyResolver(), TF.creatures()),
                   GenTrig(On(UpkeepEvent).where(IsHostTurn()).then(DealDamageToHostOwner()))],
    'war-barge': [Activated('3', WarBarge(), TF.creatures())],
    'warp-artifact': [Spell(EmptyResolver(), TF.artifacts()),
                      GenTrig(On(UpkeepEvent).where(IsHostTurn()).then(DealDamageToHostOwner()))],
    'water-wurm': [Static(PumpApplies(TF.self(), (0, 1), cond=C_FUNCS['opp_has_island']))],
    'weakness': [Spell(Pump(-2, -1), TF.creatures())],
    'weakstone': [Static(PumpApplies(TF.attackers(), (-1, 0)))],
    'web': [Spell(Do(Pump(0, 2), KWAModEffect('add', 'Reach')), TF.creatures())],
    'wheel-of-fortune': [Spell(WheelOfFortune())],
    'whirling-dervish': [GenTrig(On(EndStepEvent).where(SelfDamagedOpponent()).then(AddCounter(PLUS_ONE)))],
    'white-mana-battery': [MANA_BATTERY_ADD_CHARGE, mana_battery_add_mana('W')],
    'white-ward': [Spell(KWAModEffect('add', KW.PROTECTION_FROM_WHITE), TF.creatures())],
    'wild-growth': [Spell(WildGrowth(), TF.lands())],
    'will-o-the-wisp': [Activated('B', Regenerate(), TF.self())],
    'willow-satyr': [Activated('T', Steal(return_on_untap=True), TF.opp_legendary_creatures()), Static(OptionalUntap())],
    'winds-of-change': [Spell(WindsOfChange())],
    'winter-blast': [Spell(WinterBlast(), TargetSpec(TF.untapped_creatures(), 1, None),
                           max_x_func=max_x_from_printed_card)],
    'winter-orb': [Static(WinterOrb())],
    'witch-hunter': [Activated('T', DealDamage(1), TF.all_players()), Activated('1WWT', Bounce(), TF.opp_creatures())],
    'wood-elemental': [Spell(WoodElemental())],
    'wooden-sphere': [GenTrig(On(CastResolvedEvent).where(CastCardIsGreen()).then(MayPayMana('1', GainLife(1))))],
    'word-of-binding': [Spell(TapCardsEffect(), TargetSpec(TF.untapped_creatures(), 1, None),
                              max_x_func=max_x_from_printed_card)],
    'worms-of-the-earth': [Static(CantCastAppliesTo(TF.all_lands_in_game())),
                           Static(GlobalSac(TF.all_lands_in_game())), Triggered(WormsOfTheEarthUpkeep())],
    'wormwood-treefolk': [Activated('GG', Do(KWAModEffect('add', 'Forestwalk', True), DealDamageToSourceOwner(2))),
                          Activated('BB', Do(KWAModEffect('add', 'Swampwalk', True), DealDamageToSourceOwner(2)))],
    'wrath-of-god': [Spell(ExileAllCreatures())],
    'wyluli-wolf': [Activated('T', Pump(1, 1, True), TF.creatures())],
    'xira-arien': [Activated('BRGT', DrawCards(), TF.all_players())],
    'yawgmoth-demon': [Static(YawgmothDemon())],
    'ydwen-efreet': [Static(YdwenEfreet())],
    'xenic-poltergeist': [Activated('T', BecomeCreaturePTEqualsManaValue(), TF.non_creature_artifacts()),
                          Triggered(XenicPoltergeistRelease())],
    'zombie-master': [Static(KWAApplies(TF.other_zombies(), 'add', KW.SWAMPWALK))],
    # TODO: giving other zombies an activated ability
}
